---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Вишневые сады {#01}

Тем утром я открыла глаза за пару минут до сигнала пробуждения. Вчерашний кофе, как всегда, стоял у постели нетронутым. Лениво протянув за ним руку, я слегка поежилась от утреннего холода, к которому мне так не удалось привыкнуть даже за десять лет жизни здесь.

«Нужно проверить термостат, - пронеслось в голове, - и поговорить с Корнуэллом».

Последнего мне особенно не хотелось. Существуют такие необходимые типы разговоров, совершенно не подходящих для начала выходного дня, и этот как раз не был исключением.

Ступая по холодному полу, я подошла к округлому окну, занимавшему практически всю стену, из которого открывался чудесный вид на наши трассы и, конечно же, саму Землю. Сознание упорно отказывалось просыпаться, но у меня не было на это времени.

Спустя час, кое-как приведя мысли в порядок, я стояла около ворот, ведущих к вишневым садам, и размышляла о том, как бы мне стоило изложить суть предстоящего разговора и с чего правильней будет начать.

Джуд Корнуэлл был одним из первых инженеров, работающих с лунной поверхностью и старшим обитателем м83. Прежде он никогда не называл своего возраста, но, сопоставив даты, можно было с легкостью предположить, что тот уже давно перевалил за сотню. Для человеческого организма время здесь течет гораздо медленней земного, так что выглядел Корнуэлл лет на шестьдесят. Еще задолго до моего рождения срок его двадцати пяти летнего контракта истек, но Корнуэлл не вернулся на Землю вместе со своими сослуживцами, а проявил инициативу остаться, дабы консультировать молодых последователей. По сути, среди нас Джуд был единственным, кто видел весь путь зарождения лунной жизни своими глазами, оттого его помощь была неоценимым вкладом в модернизацию оной. Проблема заключалась в том, что старик провел здесь практически втрое больше положенного по контракту времени. На этой почве между властями штатов и сенатором Куинном назревал скандал, которого последний всеми силами старался избежать.

По окончании минувшего заседания ЭСКМО, сенатор ясно дал понять мне, что Корнуэлл в любом случае будет вынужден покинуть базу, иначе мы окажемся втянутыми в политический конфликт. Будучи капитаном м83, я отлично осознавала, что сейчас моей первой задачей было всеми силами воспрепятствовать этому, так что чем бы ни руководствовался Корнуэлл, оставаясь здесь все это время, вскоре ему предстояло вернуться домой.

– Доброе утро, Капитан. 

Я обернулась и увидела приближающегося ко мне Корнуэлла. Он, как обычно, рассеяно приветствовал меня своей старческой улыбкой.

Перекинувшись с ним парой привычных фраз, я предложила немного прогуляться.

Мы неспешно шагали вдоль цветущих деревьев, удаляясь вглубь сада. Пурпурные лепестки Сакуры игриво парили в воздухе. Несколько, покружив, задержались на плече моего спутника.

– Подумать только…– протянул он, разглядывая один из лепестков так, словно видел его впервые. – Сложно представить, что меньше века назад это место было абсолютно лишено жизни, и я стоял здесь среди той пустоты в компании друзей, которых уже давно нет, так же, как стою сейчас с тобой, и вспоминал о вишневом саде у моего дома…

Мне подумалось, что это был удачный для того, чтобы перевести разговор в нужное мне русло, как вдруг Корнуэлл замолчал и коснулся моего плеча.

Подобное поведение обескуражило меня, но прежде, чем я успела что-либо ответить, он произнес:

– Я знаю, о чем ты хочешь поговорить со мной, Капитан. Мое время уже давно пришло.

Я кивнула.

– Боюсь, что так.

– Я и без того слишком здесь задержался, да и консультант из меня так себе. Ничего я не смыслю в современных технологиях, – он все так же рассеяно улыбался.

– Могу я узнать настоящую причину? – неожиданно для себя спросила я.

– Причину чего?

– Почему Вы все еще здесь?

В этот момент Корнуэлл вдруг показался мне невероятно беспомощным. Пауза слишком затянулась, и мне показалось, что на этом наш разговор будет окончен.

– Мне больше не хочется возвращаться назад, – наконец сказал он. – Я не был дома так давно, что сомневаюсь, стоит ли мне вообще называть Землю своим домом.

– Если все дело и впрямь из-за нелюбви к развивающимся технологиям, поверьте, здесь их ничуть не меньше.

– Нет. Дело совсем не в этом, – еще одна пауза. – Скоро мне исполнится сто двадцать один год, на Земле столько не живут. Я просто невероятно сильно боюсь возвращения и того, что непременно последует за ним.

Теперь уже я не находила, что и сказать. После его слов все мои мысли спутались.

«Страх? – думала я, – Но как он может чувствовать страх, проведя на м83 так много десятилетий?»

Этот вопрос не выходил у меня из головы, ведь подобной действительно было чем-то невозможным. Благодаря синему воздуху, мы практически не ощущали эмоций, будучи вне Земли, и с каждым годом его влияние только усиливалось.

Корнуэлл определенно застал меня врасплох, а я по-прежнему не находила нужных слов. Он, казалось, понял это, и, не дожидаясь моего ответа, продолжал:

– Все эти годы я невероятно тосковал по дому, и все, чего мне хочется, это вновь оказаться на своей улице, увидеть родные улыбки. Но вряд ли кто-то ждет меня там, ведь теперь я одинок. Наверное, стоило вернуться назад вместе с остальными, но мне предложили продлить контракт, и я ухватился за первую же возможность задержаться. Но кто знал, что мой путь домой окажется столь долгим?

Я увидела, что глаза старика покраснели, словно от ветра. Я постаралась собрать все свое понимание в горстку нужных слов.

– Послушайте, Джуд, Вам нечего бояться. Стоит лишь сделать правильный выбор, и Вы сможете вновь вернуться к вещам, о которых так тоскуете. В любом случае, я постараюсь сделать так, чтоб Вам позволили задержаться здесь ровно только, столько понадобится для подготовки к возвращению.

Корнуэлл молча протянул мне ладонь, и я вдруг почувствовала, какие уставшие и слабые теперь у него были руки. После чего я уже более спокойно добавила:

– Мне совсем не хотелось начинать этот разговор, но дело в том, что власти очень взволнованы. Сенатор Куинн лично просил меня об этом. Вам ведь давно полагается быть на отдыхе.

Мой собеседник понимающе кивнул.

– Спасибо тебе. За все время, проведенное на базе, я трудился под началом тринадцати капитанов. Ты единственная, кто проявил сочувствие. Теперь я вижу, что Луна не влияет на тебя так, как на остальных.

Всю дорогу до м83 я размышляла о его последних словах и не никак не могла решить, стоит ли воспринимать их всерьез. Всем известно, что, проведя некоторое время около Луны, людям приходится дышать синим кислородом, из-за которого они постепенно остывают, ведь м83 – неподходящее для чувств место. Возможно, частично в этом и заключается успешность нашей работы: разум остается чистым, что позволяет всецело сконцентрироваться на общем деле во благо нашей страны.

Корнуэлл же проявил этим утром немалую эмоциональность, которая удивила и одновременно насторожила меня. Тогда я решила, что стоит спросить его об этом до того, как Джуд вернется на Землю.