---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Как мы жили на м83 {#02}

Если однажды вам захочется повидать Луну такой, какой вижу ее я, непременно воспользуйтесь услугами нашей транспортной компании. Добраться до этого места в одиночку сейчас практически не представляется реальным. Из-за постоянного перемещения звезд, строительство космических трасс и по сей день является невозможным, а, следуя нашими маршрутами, вы окажитесь в нужном месте спустя всего восемьдесят три минуты.

Глядя в иллюминатор пассажирского корабля на протяжении первого часа, можно увидеть лишь бесконечно мелькающие вокруг звезды, но по мере окончания пути открывается невероятно сказочный вид. Таким образом работают наши отражатели: увидеть базу возможно только за несколько минут до снижения. Сначала вы заметите лишь лиловый луч, пересекающий звездное небо, приближаясь к которому различите и саму поверхность, усыпанную уютными коттеджными домиками, что словно явились из далеких 1950-х. Их численность вдвое превышает количество домов в среднестатистическом американском городке. Рядом находится здание туристического космодрома, его площадки и стоянки. Это и есть м83, точнее, часть ее, отведенная для туристов.

Сам лишь вид такого городка, зависшего в космосе, способен вызвать восторг даже у самого прихотливого обитателя Земли, однако, и он не сравнится с тем, что ожидает вас за пределами базы – с Луной.

Все это расположено по левую сторону м83 и заканчивается двумя масштабными мостовыми трассами, ведущими к Луне.

По другую сторону луча находится основная техническая часть м83, открытая лишь для наших сотрудников: блоки (ими являются здания для работников базы, насчитывающие несколько сотен этажей), Институт Исследования и Сканирования Лунной Поверхности, штаб м83, где были размещены площади для солдат, залы переговоров и пр.; транспортные стоянки, и еще один космодром.

Сам штаб представляет собой огромное стальное здание в форме эллипса. Он расположен поперек лучу и тянется через космическое пространство, практически соприкасаясь с поверхностью Луны. Остальное место отведено под два небольших моста. Первый ведет к открытой части Луны, занимающей 17%. Им может воспользоваться любой сотрудник м83. Второй – это дорога к другим 22% поверхности Луны, что уже есть в нашем доступе. Именно здесь докторами ежедневно проводятся исследования с целью внедрения жизни. Доступ ко второму мосту на базе имеют только инженеры, некоторые военные и я.

На м83 предусмотрительно нет пути, ведущего к закрытой части Луны – ее «темной» стороне, на которой проводится постоянное сканирование. Попасть туда можно лишь через надземный стеклянный тоннель, находящийся в исследуемой части.

Все это являет собой поразительный контраст с той половиной м83, что открыта для штатских. Здесь нет ничего хоть отдаленно напоминающего о доме, лишь угрюмые серые здания вокруг. Думаю, будь это Луной, так бы выглядела ее «темная» половина.

\*

Обычное утро вторника. Я шагала вдоль шеренги выстроившихся солдат.

– Доброе утро, десант.

Все, как один, отдали часть, и я подумала, что не зря этих ребят готовят в Космической Академии целых пять лет. Рядовой Кэрролл доложил обстановку, и весь строй отправился завтракать. Все шло по плану, как и всегда.

После утренней проверки я прошла в правое крыло здания, где меня уже ждал Сириус.

Сириус Уайт занимал пост моего старшего помощника и заместителя. Он был младше меня года на два и провел здесь последние семь лет.

Мы зашли в одну из комнат отдыха и заняли столик у окна, из которого когда-то открывался вид на коттеджный городок. Сейчас весь обзор закрывали небоскребы, зовущиеся здесь блоками.

– Готова к совету, Отем? – прервал мои мысли Сириус.

Всего на мгновенье я задумалась, после чего ответила утвердительно.

– Ты повременила с ответом, все в порядке?

Я кивнула.

– На прошлой неделе сенатор поручил мне одно внеплановое дело, и это навело меня на определенные мысли, – объяснила я, наполняя стакан соком.

– Но ты ведь все уладила?

– Да. С этим практически покончено. Я просто вспомнила, что хотела кое в чем разобраться.

Сириус понимающе кивнул. Я спросила, как обстоят дела со сканированием.

– Без изменений, – ответил спарпом. – Докладывают, что ничего нового не было обнаружено, только камни да дыры, как когда-то и на этой стороне. Через пару лет можно будет смело начинать строительство.

– Что ж, надеюсь, так и будет.

После завтрака я отправилась прямиком на стоянку, у входа к которой меня ожидал корабль с живописным названием «Лунная Волна», восемьдесят седьмого года выпуска.

– Прошлой ночью звезды были особенно непостоянны, – услышала я позади себя голос одного из наших смотрителей. – Будьте внимательны, Капитан.

– Спасибо, Билл, – произнесла я, поднимаясь на борт. – Хорошего дня.

Завершив авторизацию и выбрав маршрут, я переключила управление на автопилот и откинулась на мягкую спинку кресла.

На протяжении своего (весьма короткого по местным меркам) пути я лениво наблюдала за проносящимися мимо огнями, думая о том, что вокруг нет никаких примечательных ориентиров и, не имея маршрута, заблудиться в открытом космосе было бы действительно легко.

«Три минуты до снижения» – возвестил меня привычный монотонный голос.

Корабль приближался к немыслимых размеров платформе, на которой величественно возвышались пять стальных зданий, прежде скрываемые отражателями – ЭСКМО.

«Минута до снижения» – и я отключила обратный отсчет.

ЛВ-87 на мгновенье завис около центрального здания, где и проводились еженедельные советы, после чего вошел в один из туннелей и вскоре приземлился.

Я отключила систему и сошла с корабля.

Сейчас мне предстояло пройти вдоль всей внутренней стоянки до одного из лифтов. Подле себя я насчитала шесть кораблей, а значит, практически все капитаны уже прибыли. Я взглянула на свой браслет, но время еще было.

Шагая через безлюдную стоянку, я пожалела, что не прихватила плащ, ведь здесь было значительно холодней, чем на м83. Оставалось лишь посильней укутаться в шарф.

Прибыв на ЭСКМО впервые, я ужаснулась бесконечным лифтам и коридорам, и думала, что вряд ли когда-то сумею проделать этот путь самостоятельно. Для этого мне еще приходилось пользоваться своим браслетом.

С того дня прошло чуть более двух лет, и теперь я даже не задумывалась о том, куда сворачивала. Вскоре передо мной уже открывались громоздкие двери, ведущие в Зал Совета. Сенатор Куинн по обыкновению сидел во главе стола, скрестив перед собой руки. Шесть Капитанов тоже были здесь. Не хватало лишь Фостера.

– Капитан Раст, – произнес Сенатор, – Вы как раз вовремя. Мы начинаем через минуту.

Мы обменялись рукопожатиями, после чего я опустилась в кресло около Джеймса Дискейна.

– Кофе? –как всегда предложил тот.

– Можно.

Через несколько секунд Дискейн протянул мне чашку. Я лишь успела поблагодарить его, как дверь открылась, и в зал вошел Фостер. Извинившись, он поспешно занял место напротив.

Как и все советы, на которых мне довелось побывать, этот прошел совершенно спокойно и сенатор остался доволен полученными отчетами.

– Между прочим, – произнес он, просматривая данные о численности туристов за прошлые выходные, – в конце следующей недели на м83 прибудет новый сотрудник. В ходе экспериментальной программы.

– Еще один солдат? – уточнила я.

– Нет, – покачал головой сенатор, – инженер-астроном из Калифорнийского Космического Университета. Возможно, ему удастся разрешить проблему отсутствия лунных дорог. Планирует задержаться у вас на год. Это не вызывает осложнений?

– Никак нет.

– Тогда после собрания получите в свое распоряжение более детальную информацию об этом проекте и личное дело…, – он перевел взгляд на бумаги. – Его имя Старлайт Рок.

Немного погодя Куинн спросил, как обстоит дело с вопросом, о котором мы говорили неделей ранее, и я заверила его, что все улажено.

Дорогой назад я решила просмотреть полученные бумаги. Вновь передав управление автопилоту, я поднесла запястье с браслетом к панели управления и, выведя файлы на экран, принялась копаться в документах. Дойдя до личного дела Рока, мой взгляд непроизвольно задержался на фотографии последнего.

Старлайт Рок значительно отличался от всех тех, с кем мне приходилось работать все эти годы здесь, на м83. Его карие глаза, темные волосы и естественно смуглый тон кожи напоминали мне саму себя каких-то десять лет назад. Его внешность определенно была очаровывающей, в ней угадывалось что-то далекое и забытое, напоминающее о доме.

Откинув упавшую на глаза прядь волос, я перевернула страницу, когда электронный голос возвестил меня о предстоящем снижении.

\*

Вечером следующего дня я стояла у окна своей комнаты, наблюдая за мирно дремлющей Землей, когда раздался звонок и один из солдат оповестил, что меня ожидают в комнате для отдыха под номером восемь.

«Той, что расположена в правом крыле здания» – уточнил он.

Войдя, я увидела силуэт старика, так же как и я за минуту до этого, смотрящего на Землю сквозь иллюминатор.

– Мистер Корнуэлл, – произнесла я, закрывая за собой дверь, – хотите что-нибудь выпить?

За эти несколько дней в нем, словно, произошла какая-то неуловимая перемена.

– Я лишь зашел сказать, что спустя две недели возвращаюсь домой. Как только юные помощники доктора Хартрайта закончат проект, за которым я сейчас слежу.

И тут я поняла, что навело меня на подобные мысли: взгляд его ясно голубых глаз уже не казался таким затуманенным и рассеянным как прежде. Мне вдруг стало интересно, каким цветом глаз Корнуэлл обладал на Земле. Возможно, серым…

Но я лишь сказала ему, что непременно доложу сенатору.

– Что ж, уже поздно. Не буду задерживать, Капитан, даже в молодые годы отдых не помешает, – с этими словами Корнуэлл направился к выходу.

– Постойте, – остановила его я. – Присядьте еще на минуту, мистер Корнуэлл.

– Всего лишь Джуд, Капитан, – улыбнулся он.

– Джуд, я хочу задать Вам еще один вопрос, прежде чем Вы покинете мою базу.

Инженер с интересом посмотрел на меня.

– Вам лучше меня известно, как жизнь у нас сказывается на людях, – начала я. – Дело в том, что я не могла не заметить неких метаморфоз, что произошли в Вашем поведении за последнее время. Не подумайте, что я упрекаю, но ведь для меня это просто не представляется возможным.

Какое-то время он смотрел на меня, не отводя взгляда, после чего произнес:

– Я очарован.

– Простите?

– Я очарован, Капитан, тем, что ты, наконец, заметила это, – видимо, я взглянула на Корнуэлла с недоверием, потому что он поспешил добавить: – Нет-нет, не стоит так удивляться. Я жил в страхе задолго до твоего рождения и мне практически не приходилось этого скрывать. У местных жителей невероятно низкий эмоциональный диапазон: они слышат текст, но не замечают интонации.

– Все это мне ясно, но я все еще не могу понять одного: почему это так и не коснулось Вас?

Глаза Корнуэлла сверкнули синим пламенем, и я вновь подумала, что никогда прежде не видела его таким.

– Я отвечу на твой вопрос, если ты ответишь на мой, – весело сказал он.

Я вскинула брови.

– Ладно, почему бы и нет. Что Вы хотите узнать?

– Для чего ты здесь? – тихо спросил Корнуэлл.

Меня удивил такой легкий вопрос, но ответ на него был еще более прост.

– Для того же, что и все остальные, конечно. Мой долг – помочь своей стране.

Корнуэлл явно выглядел разочарованным.

– Возможно, – говорил он, – ты еще не осознаешь настоящих причин, но пообещай, что дашь мне знать, когда поймешь.

И я пообещала, хоть и понимала, что едва ли мы снова встретимся после его возвращения на Землю.

\*

Мой спутник поднес запястье к замку и мгновеньем позже мы вошли в небольшое помещение, расположившееся на двенадцатом этаже хмурого институтского небоскреба, именуемого пятым сектором.

Раньше я частенько бывала здесь. Размышляла о жизни и слушала игру Корнуэлла на рояле, что всегда стоял в дальней спальне.

Я откинула капюшон и осмотрелась – внутри было гораздо уютней. Здесь все выглядело так, словно я перенеслась на пару столетий назад. Мое внимание сразу же привлекло плетеное кресло, стоящее в дальнем углу комнаты, в последний раз я видела подобное лишь в детстве, в небольшой антикварной лавке на другой стороне моей родной улицы. Я медленно провела рукой вдоль соломенных перил, казалось, они могут развалиться лишь от одного моего прикосновения.

– Пойдем, я покажу тебе, – говорил Корнуэлл.

Взглянув на него, я увидела, что тот стоит около резной арки, вероятно, ведущей еще в одну комнату.

Я сделала несколько шагов в его сторону, и моему взгляду открылась небольшая ниша, что-то вроде подсобки, в центре которой стоял стеллаж, уставленный…

– Книги, – тихо произнесла я.

– Привез их из дома много лет назад, – объяснил Корнуэлл. – Тогда они еще не были такой редкостью. Укладывал в рюкзаки с одеждой, чтоб не растерять.

Я все еще не могла поверить своим глазам. Должно быть, на всей Земле сохранилось не больше книг, чем сейчас было передо мной.

Старик снял небольшое издание с полки и ласково провел по нему рукой.

– Сколько бы лет тебе не исполнилось, нет ничего лучше хорошей книги в руках.

– В этом и заключается ответ, – догадалась я, – Вы перечитываете их постоянно.

Джуд лишь улыбнулся и протянул мне небольшую потрепанную книгу. Мгновенье поколебавшись, я взяла ее.

«Как же это непривычно – держать в руках текст», – пронеслось в голове.

– Сердца в Атлантиде, – гласило название.

– Прочти ее, – попросил Корнуэлл.

– Хорошо. Мне ведь когда-то тоже нравилось читать. Правда, я прежде никогда не держала в руках настоящую книгу.

Я вновь взглянула на Корнуэлла, казалось, он хотел добавить еще что-то, но никак не мог решиться.

– Послушай, – наконец начал он, – я не могу забрать все эти книги с собой, да и не вижу смысла.

– Хотите, чтобы я за ними присмотрела?

– Просто хочу оставить все это тебе.

– Что ж, обещаю найти для этого время, – сказала я, продолжая разглядывать книгу.

Широкая улыбка осветила лицо старика, на минуту лишив меня дара речи, ведь только сейчас я поняла, что, должно быть, не видела подобного все эти десять лет.

– О, я совершенно не волнуюсь на этот счет, – все еще улыбаясь, сказал Корнуэлл. – Стоит тебе открыть лишь одну, и ты не заметишь, как прочтешь остальные.