---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Старлайт Рок {#03}

Меня разбудил гул восторженных голосов, и я не сразу вспомнил, где нахожусь.

Открыв глаза, я взглянул в иллюминатор и увидел, что мы приближаемся к волшебному городку, зависшему на основании луча. Это место словно только-только перенеслось сюда со старых кинолент.

«Настоящий рай для поклонников эпохи Элвиса», - подумал я, и улыбнулся.

Сойдя с корабля, я сразу же заметил машущего мне солдата. Человека такой необычной внешности я видел впервые: черты его лица выдавали явное афроамериканское происхождение, однако кожа так и светилась бледно оливковым цветом.

Мужчина подошел ко мне.

– Приветствую на м83, профессор Рок, – кивнул он, протягивая руку. – Старший помощник капитана, Сириус Уайт.

Мы обменялись рукопожатиям, и Сириус повел меня за собой через немыслимых масштабов холл космодрома. Мимо пронеслась толпа смеющихся ребятишек, и я в очередной раз восхитился чудесами этого места.

Ступая вслед за Сириусом я то и дело задерживал взгляд на людях, работающих здесь. Мужчины и женщины с чуть ли не прозрачной кожей и невообразимого цвета глазами поразительно выделялись среди туристов и казались мне какими-то нереальными сказочными персонажами. Сложно было поверить, что когда-то все они прибыли с той же планеты, что и я сам.

– Мы с Капитаном решили, что для начала Вам удобней будет осмотреться на технической части луча, – сказал Сириус, когда мы уже практически пересекли холл космодрома. – После, если пожелаете, Капитан Раст лично покажет здесь все и расскажет об интересующих аспектах. Вы согласны, Профессор?

– Конечно. Признаться, я уже восхищен этим местом.

Лицо старпома обрело странное выражение, которое едва ли можно было принять за улыбку, но, кажется, он был вполне доволен моими словами.

Наконец, миновав пункт выдачи багажа, мы оказались около высоких стеклянных дверей, за которыми виднелось бесконечное количество лунного транспорта.

– Эти двери ведут к стоянке для гостей, – объяснил Уайт. – При выходе из здания туристам обычно предлагают занять один из кораблей, который, миновав мосты, вскоре доставит их на Луну.

Я попытался разглядеть за стеклом хоть что-то, напоминающее Луну, но из-за невероятно огромного количества людей это оказалось невозможным.

– Дабы попасть в коттеджный городок нужно воспользоваться вторым выходом, – Уайт указал на такие же двери, находящиеся в противоположной стороне здания. – За ним гости проходят регистрацию, после чего располагаются в одном из коттеджей. Видите эту железную дверь? Это вход для работников базы. Нам как раз туда.

Сириус подошел к сплошной железной двери, по левую сторону которой светился синий огонек. Я последовал за ним. Только старпом поднес руку к огоньку на двери, как та сразу же открылась.

– Доступ для всех сотрудников первого уровня, – сказал Уайт, пропуская меня вперед.

Я оказался в продолговатом хорошо освещенном помещении. По обе его стороны находилось несколько десятков стальных дверей, которые, как я понял мгновеньем позже, были лифтами. Подойдя к одному из них, мой спутник сделал то же движение рукой, что и прежде, и двери моментально разошлись.

На стене внутри была лишь небольшая голографическая панель. Уайт выбрал на ней нужную отметку, после чего дверь позади бесшумно закрылась, и лифт с невероятной скоростью унес нас вверх.

\*

Пространство вокруг заполнялось миллиардами световых микрочастиц, от которых тускнело в глазах. Хотя мы и находились на улице, это место скорей напоминало сплошной космический военный корабль. Здесь не было никаких растений или даже рекламных щитов – одно лишь железо. Несмотря на масштабность базы, я чувствовал себя загнанным в угол, словно что-то мешало мне свободно вдохнуть.

Уайт обучил меня управляться с местным транспортом – небольшим бронзовым луноходом, слегка напоминающим водный скутер. Но стоило мне лишь сесть за него, и я тут же почувствовал себя лучше. Мой «скутер» несся вперед, с невероятной легкостью рассекая воздух словно волны. Мимо проплывали светящиеся строения небывалых размеров и форм. Где-то вдалеке, по левую сторону от меня, пробивались чарующие огни Луны.

Сбавив скорость, Сириус снизился, и я последовал его примеру. Мы остановились, и он указал на крайнее здание, являющее собой круглый купол из синего стекла.

– Институт Исследований Лунной Поверхности, – говорил старпом. – Внутри разделен на два яруса. В основном, здесь проводятся работы по части зарождения жизни на Луне. Все поля, леса, сады и озера, которые Вам там встретятся – это полностью заслуга наших инженеров. Еще один институт находится на дальней стороне Луны, но обо всем этом лучше говорить с капитаном.

– Ясно. А где находятся те, кто работает с маршрутами и космическими трассами? – спросил я, продолжая оглядывать стеклянный купол.

– В основном, на Земле, ведь маршруты давно проложены, а трассы и вовсе отсутствуют. Конечно, в штабе есть несколько человек, следящих за этим.

Я понимающе кивнул.

– Честно говоря, мы очень надеемся на Вас, Профессор. Лично мне в подобное верится с трудом, но если все пойдет по плану, это значительно облегчит работу, не говоря уже об экономической стороне проблемы.

– Я следил за звездами на протяжении тринадцати лет, и думаю, что у этого проекта действительно есть шанс, так что следующие двенадцать месяцев я намерен продолжить исследования, находясь здесь, – я старался говорить как можно убедительнее. – Конечно, существует еще множество факторов, которые стоит прояснить, но, пожалуй, мне удастся учесть их все за это время.

– Очень хорошо, – ответил Старпом, возвращаясь к своему луноходу. – А теперь пора в путь. Капитан Раст уже, должно быть, ожидает нас.

\*

Благодаря своему размеру, здание штаба м83 заметно выделялось среди других строений, встретившихся мне на базе. Я оглядывал холодные стены корпуса, ожидая пока доложат о нашем прибытии. Как и снаружи, внутри царил идеальный порядок, здесь все было пропитано атмосферой общего дела.

Спустя несколько минут мое наблюдение прервал вошедший в зал солдат. Он был молод, как и многие здесь, а его внешность говорила о том, что на м83 он пробыл от силы пару лет. Каштановые волосы только начинали светлеть, приобретая кремовый оттенок. И хотя его глаза все еще оставались карими, радужка уже выглядела светлей обычного, тогда как кожа юноши не представляла собой ничего сверхъестественного.

– Капитан ждет Вас, – сообщил солдат. – Следуйте за мной.

Он вел меня лабиринтами бесконечно долгих и унылых коридоров, каждый из которых ничем не разнился от предыдущего, пока, наконец, мы не остановились у одного из лифтов.

– Здесь я должен Вас покинуть, Профессор, выше – вход лишь для сотрудников второго доступа. Лифт доставит Вас на последний этаж здания. При выходе сразу же увидите высокие стеклянные двери с гравюрой падающей звезды – кабинет Капитана.

– Благодарю, – сказал я, и, отдав честь, солдат удалился.

Уже поднимаясь, я пожалел, что прежде ничего не разузнал о капитане Раст. Понять людей с м83 представлялось мне нелегкой задачей, и хоть немного информации о моем новом начальстве сейчас совсем бы не помешало, а я ведь даже не знал имени этого человека. В конце концов, я успокоил себя мыслью о том, что с капитаном меня связывает лишь работа, (а свое дело я отлично знаю) – так я думал. И ошибался.

Верхний этаж выглядел более дружелюбно и напоминал офисы it- компаний, в которых мне приходилось бывать прежде. Я сразу же увидел дверь, о которой говорил солдат.

Не встретив никого из сотрудников, я постучал. Ответа не последовало. Тогда я отворил дверь и шагнул в кабинет.

Свет горел лишь у входа. Было непривычно приятно находиться здесь после чересчур освещенных коридоров.

Мгновением позже мне навстречу из полумрака вышла невысокая девушка лет двадцати, облаченная во все черное. Появление этого волшебного существа начисто лишило меня дара речи; еще несколько секунд я не мог отвести восхищенный взгляд от фарфоровой кожи и невероятной длины синих волос. Ее большие глаза цвета океана завораживали, напоминая мне саму Луну, какой я увидел ее впервые на старых снимках.

– С прибытием на м83, профессор Рок, – произнесла девушка; ее голос был низким, а слова, как и у всех здесь, звучали мягко и монотонно. – Меня зовут капитан Отем Раст.

Она протянула мне руку, и я ответил тем же, удивляясь, какими холодными были ее пальцы.

Глядя на нее, я пытался определись настоящий возраст капитана, гадая, сколько времени она провела здесь.

– Все в порядке? – услышал я, и вдруг понял, что за все время не произнес еще ни слова.

– Простите, Капитан, я немного удивлен, ведь Вы так молоды, а я ожидал увидеть седеющего старика, – сказал я, и сразу же пожалел об этом, но девушка, казалось, ничуть не смутилась.

– Время здесь течет иначе, – ответила она.

Я перевел взгляд и принялся осматривать ту часть кабинета, что не была скрыта темнотой. Капитан зажгла небольшой торшер и предложила мне присесть.

– Старший помощник сказал мне, что Вы уже немного осмотрелись у нас…, – начала она.

– Да, он показал мне большую часть базы.

– Не думаю, что увиденное привлекло Вас, но, боюсь, что без Вашей помощи нам не обойтись, так что я хочу показать обратную сторону медали.

– Я с удовольствием увижу ее, Капитан.

– Между прочим…

Отем отворила ящик стола, и протянула мне небольшой бархатный футляр. Открыв его, я обнаружил внутри лишь тонкий ободок из черного метала, идентичный тому, что я видел на руке старпома.

­– Ваш браслет второго доступа. Наденьте на левое запястье и не снимайте до конца своего пребывания на м83.

Надев браслет, я заметил, что на нем зажегся синий огонек, такой же, как на всех дверях здесь.

– Отлично, – кивнула Отем, вставая. – А теперь пойдемте.

Я последовал за ней по просторному кабинету, и, миновав несколько арок, мы вышли на открытую подвесную террасу, которую освещало множество крошечных фонарей, зависших в воздухе. От увиденного у меня перехватило дыхание, и на мгновенье я осознал, насколько прекрасна может быть Вселенная. Прямо под нами раскинулся крохотный городок. Укрытый вечерними огнями, он тянулся через все пространство впереди нас, исчезая где-то в далеком сумраке. По правую сторону возвышались величественные и при этом утонченные мосты, по которым молниеносно проносились бесчисленные огоньки, вероятно, космический транспорт. Вокруг все купалось в лиловых отблесках луча, а окончательное волшебство этой картине предавали синие огни луны, расположенной в невероятной близости от нас.

Здесь все выглядело нереальным и неописуемо прекрасным. Мне вдруг захотелось провести вечность на этой самой террасе, не сводя глаз с открывающегося вида.

– Мы стоим в самой высокой точке м83, – слова доносились словно сквозь сон. – Что скажете, Профессор?

– Это волшебно, – тихо ответил я и, переведя взгляд на Отем, заметил тень улыбки на ее лице. – Признаюсь, еще вчера я не был полностью уверен в правильность своего решения, однако то, что я сейчас вижу, говорит мне обратное.

– Что ж, я верю, что Вы не ошибаетесь, – произнесла Отем.

– Без сомнений, Капитан.

В ее глазах так явственно отражался лунный свет, словно она сама была неотъемлемой частью этого места, и я подумал о том, чего лишены живущие здесь люди, ведь вряд ли со временем они не переставали осознавать, среди какой красоты находятся.

И в этот же миг я понял, что проложу трассы, чего бы мне это не стоило. Каждый должен увидеть этот сказочный мир.

– В таком случае, этим вечером можете спокойно отдыхать, а завтра Вам предстоит нелегкая работа.

– Трудности всегда неизбежны в самом начале, – улыбнулся я. – Я ждал этого.

– Очень хорошо.

Я вновь обвел взглядом открывающийся с террасы вид. Отем спросила, где бы я предпочел разместиться: в штабе, или в одном из секторов. Я ответил, что штаб меня вполне устроит, надеясь, что смогу наблюдать этот чарующий пейзаж со своей комнаты.

– Тогда я дам распоряжение подготовить для вас одну из комнат здесь, наверху, – произнесла она, возвращаясь в кабинет.

– Благодарю.

– Оставайтесь пока на террасе, если хотите, за Вами поднимутся.

– Доброй ночи, Капитан.

– Доброй, Профессор, - и она вновь растворилась во мраке кабинета.