---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Институт Исследований Лунной Поверхности и дальше {#04}

Пробыв здесь около недели, я все так же не мог оторвать восхищенный взгляд от прекрасных видов м83. Отведенная мне комната находилась всего несколькими этажами ниже подвесной террасы и была расположена точно под ней, так что я часами мог стоять у окна, не сводя глаз с коттеджного городка и того, что дальше.

Следующим утром после моего прибытия я проснулся неестественно рано, и обнаружил, что проспал всего три часа. Странно, но желания продолжать сон я совсем не чувствовал, (наверное, так сказывалась смена климата – здесь было гораздо холодней) потому я сразу же поднялся и решил немного прогуляться по м83. До встречи с докторами из ИИЛП оставалось еще более четырех часов.

Позавтракав, я спускался вниз, ощущая небывалый прилив сил, казалось, мне предстояло что-то новое, неведомое прежде, и сейчас я наконец оказался там, где мне действительно следовало быть.

В холле я столкнулся со Старпомом. Он, должно быть, был немного взволнован чем-то, но тогда я не придал этому особого значения ввиду своего расположения духа, да и сложно было правильно понять эмоции этих лунных людей.

– Вы сегодня рано, Профессор, – протянул руку Уайт, и мы обменялись рукопожатиями.

– Решил немного осмотреться, пока еще есть время.

Он резко кивнул, и зашагал дальше. Уже выходя из здания, до меня донеслись обрывки фраз из разговора Старпома с одним из солдат: «Нет нужны тревожить капитана в такую рань…пока мы не найдем…оставим это на время…»

Не без труда мне удалось отыскать нужную стоянку, пришлось практически обойти весь штаб, и только сев за свой новенький луноход, я вспомнил, что мог бы воспользоваться браслетом.

Стараясь подняться как можно выше, я поймал на себе удивленный взгляд смотрителя, и, весело кивнув ему, помчался вперед. Внизу бродили группы военных, некоторые из них встречались мне и около стоянок. Пролетая над зданием штаба, я взглянул на террасу, надеясь увидеть там капитана, но никого не обнаружил.

И вот я вновь остановился около здания института, удивляясь его масштабам и форме. Тогда еще с трудом верилось в то, что мне действительно предстояло здесь работать.

Обогнув ИИЛУ, я немного снизился, и оказался на дороге, по обе стороны которой располагались восемь небоскребов. Это были те самые сектора, в которых проживали мои будущие коллеги. Здесь, казалось, все еще было во сне, и я без особого интереса миновал здания, когда вдруг заметил движение справа от себя. Я повернул голову, и увидел старика в одном из окон. Он приветливо махал мне рукой, улыбаясь словно ребенок. Я помахал в ответ, удивленный таким приятым проявлением эмоций.

Пролетев мимо небоскребов, я заметил небольшое стальное здание внизу, то самое, что вело к лифтам космодрома. Я оставил свой луноход около него и спустился вниз. В глаза тут же ударил искусственный свет коридоров, и я решил оставить попытки найти выход самостоятельно и воспользоваться браслетом.

Вокруг по-прежнему было пусто. Синие стрелки быстро привели меня к лифтам, и вскоре я с облегчением вздохнул, оказавшись посреди космодрома. Я вспомнил слова старпома о том, которые двери ведут к городку, и поспешил к ним. Меня все так же окружали группы туристов. Правда, сегодня их было гораздо меньше, чем прошлым вечером.

Работники космодрома показывали туристам дорогу. На фоне новоприбывших их кожа казалась особенно бледной. Посередине зала высился постамент падающей звезды лилового цвета. Такую же я видел на входе в кабинет капитана и еще нескольких дверях базы.

Я остановился около постамента и понял, что потерял из виду стеклянную дверь.

– Доброе утро, сер, меня зовут Элис. Я могу Вам помочь? – услышал я монотонный голо позади себя, а обернувшись, увидел девушку в синей форме с эмблемой падающей звезды. Должно быть одну из работниц космодрома.

– Да, я немного задумался, и потерял из виду двери, ведущие в коттеджный городок.

– Следуйте за мной. У стойки Вам нужно будет пройти регистрацию, это не займет много времени, после чего сможете выбрать себе коттедж с понравившимся видом…

Я улыбнулся.

– Вы меня не так поняли, я один из сотрудников м83.

Девушка взглянула на меня с недоверием, и я поспешно протянул ей левую руку. Увидев браслет, она сказала, что в нем можно задать любой маршрут, и я виновато улыбнулся.

Элис отвела меня в сторону от шумевшей группы туристов так, чтоб была видна противоположная часть зала. Я тут же заметил стеклянную арку и дверь, о которой говорил Уайт.

– Там находится стойка регистрации, – сказала Элис, – но Вам нужно пройти к другим дверям, – она указала на сплошную стальную дверь в углу, такую же как та, через которую я вошел.

Я поблагодарил девушку за помощь, и она поспешила к группе туристов, растерянно изучающих карту.

Как и снаружи, внутри это место было зеркальным отражением помещения, ведущего к космодрому.

Путь от космодрома представлялся мне более длинным, нежели оказался на самом деле, и какой же восторг я испытал, оказавшись на одной из улочек городка. За пару минут мне удалось добраться до перекрестка, возвышающегося на небольшом холме, с которого открывался вид на многочисленные дома, украшенные лужайками и небольшими садами. Стрелки на шпиле указывали на распределение коттеджей. Вниз от него вели с десяток аллей, исчезающих в сказочных двориках. Вокруг все было пропитано атмосферой осени.

После шумного зала космодрома, здесь было непривычно тихо – должно быть, заселение еще не началось.

Быстрым шагом я спустился с холма. Под ногами шуршали лишь начинающие опадать листья; погода в городке полностью отображала происходящее на улочках нашей страны, и сейчас здесь стояла ранняя осень.

Дорога передо мной казалась бесконечной, но до начала рабочего дня по-прежнему оставалось немало времени, так что я неспешно бродил по городку, переходя из одного переулка в другой. Благодаря покою и тишине, царившим здесь, я ощущал себя персонажем одного из старых фильмов вроде «Эдварда-руки-ножницы». На эти мысли меня натолкнули и аккуратно расположенные цветные домики, украшенные садами в викторианском стиле. Таких уже много лет не встретить на Земле. Мне подумалось, что создать такой уголок из прошлого стоило немалых усилий, и, гуляя здесь, я понимал гениальность этой идеи: после модернизации Земли за последние десятилетия, все вокруг выглядело более земным и настоящим, нежели дома.

Спустя какое-то время я вышел на главную улицу. Она пересекала дорогу, по которой я шел прежде, и тянулась через весь городок. По обе стороны улицы располагались уютные ресторанчики, а в самом центре был небольшой кинотеатр, из тех, что по вечерам крутили фильмы для влюбленных парочек, в обнимку поедающих поп-корн на передних сидениях машин.

Ресторанчики были еще закрыты, но я не удивился бы, обнаружив в одном из них музыкальный автомат.

Возвращаясь к слепящим лучам космодрома, я подумал, что непременно должен вернуться сюда в оживленное время.

Окончив прогулку, я выпил кофе в одном из ресторанчиков космодрома и отправился прямиком в Институт, но до этого успел поинтересоваться у официантки, когда же открывается коттеджный городок.

– Раньше гости посещали м83 каждые выходные, но теперь с каждым разом появляется все большее количество желающих увидеть Луну, так что экскурсии проходят практически каждый день, кроме понедельника, а магазины, кинотеатр и прочие заведения открываются уже после десяти утра, – ответила она.

– А понедельник здесь санитарный день?

– Вроде того.

\*

У входа в Институт меня встретил худощавый юноша, представившийся ассистентом доктора Хартрайта – Джейми ван Дин. Он провел меня в здание и дальше по лестницам – в кабинет доктора.

Внутри ИИЛП представлял собой огромное помещение округлой формы, снабженное сотней лифтов и эскалаторов. Лестницы пересекали пространство повсюду и тянулись в самых невоображаемых направлениях. Мы поднялись по одной из них на третий ярус, затем пересекли его по диагонали. На минуту Джейми заглянул в одну из приемных, дабы взять какие-то файлы для доктора Хартрайта, после чего мы вошли в стеклянный, как и все вокруг, лифт. Поднимаясь в кабинет, я наблюдал за происходящем внизу, удивляясь количеству людей в белых халатах: на каждый этаж приходилось около сотни специалистов, я и подумать не мог, что здесь задействовано столько сотрудников. Я также успел отметить, что вне зависимости от возраста, люди здесь не выглядели столь нереальными, как военные в штабе или работники космодрома. Практически все обладали бледной кожей и светлыми волосами, однако я нигде не заметил синих оттенков.

Как я узнал позже, дело было в том, что, в отличии от остального пространства базы, здание института было наполнено серебряным воздухом – последней разработкой компании, над которой пока продолжали работать. Это вещество никак не влияло на человеческие эмоции, но все еще продолжало видоизменять внешность, тогда как основной задачей этого изобретения было создание искусственного аналога кислорода.

– Вот мы и на месте, – прервал мои мысли Джейми, и мгновение спустя двери лифта отворились. Я мельком взглянул в глаза своему проводнику, они также не были синими, но при дневном свеете зрачки казались невероятно светлыми.

Миновав еще несколько дверей, мы, наконец, вошли кабинет доктора Хартрайта, где все было сделано из синего стекла (включая стены). В центре комнаты располагался сенсорный стол, за которым, что-то оживленно обсуждая, сидели трое мужчин.

– А вот и Профессор Рок, – завидев меня, произнес один из них и поспешил на встречу, – Я доктор Хартрайт, рад знакомству, – мы пожали друг другу руки.

Хартрайт сразу же показался мне вполне добродушным человеком. Доктору можно было дать лет 27, однако фигурная борода немного прибавляла ему в возрасте.

– Признаться, я тоже.

Он указал на место напротив своего.

– Прошу, присаживайтесь.

Я кивнул, и опустился в мягкое белое кресло, а Хартрайт тем временем продолжал:

– Я работаю непосредственно я лунной поверхностью, а также заведую этим местом, – он указал на сидящего справа мужчину с высоким лбом и крепкого телосложения лет сорока на вид, – доктор де ла Круа, главный разработчик последних маршрутов, которые пока еще не вступили в силу, – он указал за мое запястье, – браслет, который Вы носите также его рук дело.

Мы обменялись рукопожатиями.

– А это доктор Штернбренер, специалист по внедрению в космическое пространство, – еще одно рукопожатие.

Штернбренер был высоким мужчиной лет тридцати типичной арийской внешности. Он обладал серыми глазами, молочно-белыми волосами чуть ниже плеч и, кажется, был единственным человеком на м83, носившим очки.

– Вы еще не имели возможности ознакомиться с чертежами наших маршрутов, Профессор? – спросил Хартрайт.

– Лишь частично. Мне высылали кое-что в лабораторию, но предупреждали, что это лишь отрывки…

– Конфиденциальность превыше всего, – протянул Штернбренер, – как всегда.

– Понимаю, – продолжал Хартрайт, – тогда сейчас самое время заняться этим. Артур ознакомит Вас с полным планом чертежей, но для начала мне хотелось бы еще раз услышать Вашу теорию. Я читал многие из Ваших работ, некоторые даже по несколько раз, но все же так и не нашел намеков на то, чем именно Вы планируете тут заниматься.

Я улыбнулся.

– Дело в том, что и мне приходится утаивать основную информацию от общественного доступа. Как Вы могли заметить, большинство моих работ поверхностны и направлены, скорей, на экскурс по астрономии. У меня не было возможности опубликовать свою теорию, сами понимаете, на Земле ею бы тут же воспользовались, так что основную идею я раскрыл лишь на собеседовании с сенатором.

– Вы говорили, что намерены фиксировать перемещение звезд, но ведь с этим невозможно управиться за год…

– Да и с нашей стороны неоднозначно предпринимались попытки, и с каждым разом звезды были все более непостоянными, – печально добавил де ла Круа.

Я вновь улыбнулся: сейчас им предстояло услышать ту самую мелочь, которую уже многие годы подряд упускали из виду все доктора, инженеры и даже астрологи. На самом деле, это был первый раз, когда я собирался изложить своим коллегам все до последней мелочи. Естественно, я испытывал волнение и пытался скрыть его за улыбкой.

– Я расскажу все по порядку.

– Только прошу, не упускайте ни единой детали, – улыбнулся Хартрайт.

Трое докторов заинтересованно смотрели на меня, ожидая рассказа, и, поудобней расположившись в кресле, я начал.

– Впервые я заинтересовался звездами еще в глубоком детстве. Отец подарил мне невероятно старую диск-карту звездного неба. До этого она принадлежала его деду. Отец говорил, что родом она то ли из Сингапура, то ли около него, а возраст карты насчитывал более восьми ста лет. Сделана она была из бамбуковой бумаги и представляла собой череду вращающихся дисков.

– Мне попадались такие карты, – задумчиво произнес Штернбренер, – не оригиналы, конечно.

– Хорошо, – ответил я, – значит, Вы имеете представление об этой вещи.

Доктор кивнул, и я продолжил:

– Карта практически выцвела. Она являла собой, скорей, историческую ценность: с такими уже много лет не работал ни один астролог или астроном. Сложно объяснить почему, но меня эта вещь словно очаровала. С того самого времени я стал интересоваться звездами.

Около двадцати лет я фиксировал перемещение звезд (семь из которых я делал это лишь на любительском уровне), и, как вы все знаете, с каждым годом становилось все трудней проследить какие-то циклы. Занятие это я начал еще будучи подростком. Со временем увлечение астрономией переросло в нечто большее и в итоге, когда, получив степень Профессора, я хотел продолжить работу, оказалось, что по статистике последних лет звезды были размещены столь хаотично, что это не поддавалось ни одной из моих, да и вообще каких-либо, трактовок. Проведя еще несколько месяцев в поисках ответа, я решил оставить эту идею. Так я переключился на свое второе дело – занялся инженерией. Я перебрался в Калифорнию и начал преподавать инженерное дело в Университете имени Юджина Сернана, а позже – и астрологию.

Прошло еще два с половиной года, а я все так же машинально фиксировал перемещение звезд, но уже не строил на этот счет никаких догадок, пока однажды, избавляясь от ненужного хлама, я не наткнулся на ту самую старую карту звездного неба.

– Ну, рад это слышать, – с облегчением вздохнул Хартрайт, – Я-то уж было подумал, что Вы нам так много о ней из сентиментальных побуждений рассказывали.

Я с трудом подавил смех, увидев искреннее удивление на лице де ла Круа, кажется, он не особо дружил с юмором.

– В общем, я отложил диск-карту на стол и продолжил наводить порядок. Вслед на ней я бросил на стол стопку собственных чертежей десятилетней давности, а когда с уборкой было покончено, я решил немного отдохнуть.

Теперь на столе передо мной лежала сингапурская карта с множеством вращающихся дисков, на каждом из которых было схематически изображено звездное небо. А рядом в куче лежали мои школьные чертежи. Сам не зная зачем, я разложил их в правильной последовательности, и, помню как сейчас, чуть не пролил на себя кофе от удивления: полное изображение моих схем абсолютно соответствовало небольшому отрезку старой карты.

Я вернулся обратно в университет уже с диск-картой, и тут же разыскал остальные свои чертежи. Как и предполагалось, все отметки совпали.

Я переводил взгляд на одного из своих собеседников на другого, все трое молчали, обдумывали мои слова.

– Моим глубочайшим заблуждением было предполагать, что с каждым годом звезды меняли свое расположение, ведь оказалось, что они все время движутся по кругу в одну и ту же сторону.

Первым заговорил Штернбренер.

– Все оказалось так просто и вместе с тем столь маловероятно, – тень улыбки промелькнула на его лице. – У Вас есть с собой эта карта? Мне бы хотелось сверить с ней и свои наблюдения.

– Да, я привез с собой оригинал, он был превосходно отреставрирован, но я подумал, что удобней будет ознакомить вас с цифровой версией.

Штернбренер удовлетворенно кивнул, и я принялся рыться в память своего браслета в поисках нужных файлов.

– Но, если звезды действительно движутся по кругу, мне все же не ясно, почему этого не заметили раньше, – сказал де ла Круа.

– Для этого потребовалась бы диск-карта, а если верить ей, звездам нужно ровно две тысячи лет и тринадцать дней дабы завершить свой цикл. А без карты это было бы очень сложно проверить… Боюсь, прежде никто просто не следил за небом та долго.

– Да и кому бы подобное пришло в голову! – добавил Хартрайт.

Загрузка была практически завершена, и мы все устремили свои взгляды на экран стола. Спустя мгновение на нем появилась карта.

– Интересно, – произнес Штернбренер, внимательно осматривая каждый отрезок поверхности. – Я и впрямь склонен поверить Вашей теории, Профессор.

Я не смог скрыть улыбку.

– Рад это слышать. Между прочим, здесь у меня также есть и все мои чертежи за последние двадцать лет, – я поднес руку к экрану и, убедившись, что мои коллеги закончили изучение карты, развернул следующую, – конечно, к самым старым нельзя отнестись с полной серьезностью, но и невооруженным глазом можно увидеть, что даже с ними все совпадает.

– Поразительно! – воскликнул Хартрайт, – Все сходится…

– Доктор Хартрайт, – в дверном проеме возник Джимми, – Вас уже ожидает мистер Корнуэлл. Он в приемной номер три.

– Спасибо, Джимми. Предложи мистеру Корнуэллу кофе, я сейчас подойду.

Ассистент кивнул и исчез в дверном проеме. Хартрайт поднялся.

– Ваша теория настолько увлекла меня, что я совсем забыл о прочих делах, – он широко улыбнулся, и, пожелав нам хорошего дня, поспешно удалился.

Де ла Круа тоже поднялся и повернулся ко мне.

– Я покажу Ваш кабинет. Там Вас уже ожидают последние планы маршрутов.

– Вы не возражаете, если я еще немного посижу над этими файлами, Профессор? – спросил Штернбренер, когда, вслед за де ла Круа, я уже направлялся к двери.

– Это копии. Оставляю их в Вашем полном распоряжении, – ответил я, и вышел из кабинета.

\*

Очередное утро понедельника. Я поднялась немного позже обычного и, опустошив привычную чашку холодного кофе, села на кровати, скрестив под собой ноги. Рядом виднелась стопка оставленных Корнуэллом книг. Я разложила их перед собой и еще несколько минут рассматривала выцветшие политурки. Не зная, с чего начать, я подолгу оглядывала том за томом, вчитываясь в названия, пока, наконец, не остановила свой выбор на сборнике классического готического романа. На обложке книги была изображена крохотная фигура на фоне мрачного особняка, тени которого окутывали все вокруг, делая силуэт еще более темным и неприметным. Тогда в голове впервые проскользнули странные мысли то ли о темной стороне Луны, то ли о самой базе, но я тут же отогнала их и развернула книгу.

«Граф Дракула, вампир» -– гласило название первого романа, и, упав обратно на подушку, я углубилась в чтение.

Потеряв счет времени, я перелистывала страницу за страницей. Мне казалось непривычным, но при этом странно знакомым держать в руках книгу. Листая ее, я словно возвращалась к чему-то старому, о чем я каким-то невероятным образом забыла, а теперь вновь вспоминала. Я читала о дальних странах, темных дорогах и парках, залитых солнцем. Читала, и отчетливо видела лучи солнца, проникающие сквозь стекло в мою комнату, слышала шум ветра, качающего ветви деревьев и голоса морских волн – все те привычные вещи, что описывал Стокер, и которых никогда не было на м83.

Меня прервал сигнал дежурного, я бросила взгляд в уголок книги – «страница 217, ну ничего себе…» Сигнал повторился. Я нажала на синий огонек в центре браслета, и передо мной появилось лицо синеглазого парня в военной форме.

– В чем дело, солдат? – спросила я, прежде чем он успел что-то сказать. Хотелось опустить приветствия и поскорей вернуться к чтению.

– У меня для Вас сообщение от мистера Корнуэлла.

Его ответ меня удивил и как-то непроизвольно я произнесла:

– Правда?

Солдат с мгновенье поколебался, казалось, его тоже удивил мой вопрос.

– Так точно, Капитан.

– И что мистер Корнуэлл просил передать мне?

– Не могу знать, Капитан, – я удивленно вскинула брови, тогда солдат, наконец, добавил: – Это коробка, Капитан. Мне распорядиться, чтоб ее доставили к Вам в комнату?

Поразмыслив над его словами, я сказала, что скоро сама спущусь.

Закончив разговор, я взяла чашку с кофе и подошла к окну, не тому, что полностью повторяло вид на коттеджный городок, открывающийся с террасы, к другому, противоположному ему, из которого на меня смотрели блистательные огни Земли.

Не могу сказать, что огоньки казались мне заманчивыми, хотя с этого места Земля выглядела привлекательней, нежели была в действительности. Но я, все же, чувствовала какое-то слабое, еле уловимое влечение, глядя на эти огни. Возможно, таким образом на мне сказывалось чтение книг, но ведь описанных там вещей уже давно не было и на Земле, разве что в спрятанных уголках планеты… Теперь все мобилизировано, каждый квадратный сантиметр, потому-то люди так и спешат посетить Луну при первой же возможности.

С этими мыслями я спустилась в холл, где меня уже ждала посылка Корнуэлла. Дежурные как раз сменялись, когда я подошла к центральному посту. Один из них направился ко мне, держа в левой руке картонную коробку. Он отдал честь свободной рукой, и протянул мне посылку, но, не рассчитав сил, я чуть было не уронила ее. К счастью, солдат подоспел вовремя.

– Спасибо, – сказала я, на этот раз взяв коробку двумя руками. – Она кажется легче, чем на самом деле.

– Уверены, что не хотите, чтоб я поднял ее наверх, Капитан?

Но я лишь отмахнулась, размышляя о том, чем Корнуэлл решил удивить меня на этот раз. Еще книги? Я повертела коробку в руках – по весу тяжелая, могла бы вместить до тридцати экземпляров. Я еще раз осмотрела ее: ничего, только голубой стикер с моим именем.

«Что ж, посмотрим» – подумала я, выходя из лифта.

Я попыталась отворить дверь, но побоялась вновь выронить посылку, так что пришлось поставить ее на пол. Руки жутко болели, когда я дотащила коробку до средины комнаты, так что я решила открыть ее здесь. Разрезав ленты, я, наконец, заглянула внутрь. Сверху лежал конверт, из под которого виднелись… я не верила своим глазам – это были виниловые пластинки.

Я потянулась за кофе, и, сделав глоток, развернула письмо.

_Дорогая Отем,_

_Мне хочется верить, что однажды снова встретимся в другое время и в другом месте, но я слишком стар, и, скорей всего, это мое последнее письмо. Тяжело оставлять тебя здесь совсем одну, ведь за все эти годы я привык заботиться о тебе как о родной дочери, но обстоятельства не оставляют мне выбора. Утешает лишь одно: когда я увидел тебя, с первой же минуты нашего знакомства, я понял, что когда-нибудь ты станешь капитаном, и сейчас, как и десять лет назад, я так же ясно вижу, что все это не напрасно._

_Я хорошо помню твой первый день на м83, как ты восхищалась коттеджным городком и его окрестностями. В этом ящике все то, что когда-то поспособствовало строительству этого места. Многие годы назад я слушал эти старые пластинки и представлял волшебный космический островок, по-своему идеальный и столь далекий от всего, что происходит вокруг._

_Конечно, здесь лишь малая часть, но ты всегда можешь найти остальное в моей старой квартире._

_Когда ты прочтешь это письмо, я уже, должно быть, буду спускаться по корабельному трапу в одном из земных космодромов. Я никогда особо не умел и не любил прощаться, но сейчас я определенно точно смотрю на Луну, и знаю, что ты так же смотришь на меня._

_Удачи, Капитан,_

_и пускай холод никогда не стоит на твоем пути_