---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Лавандовые Поля и Голубая Луна {#05}

В гостиной моего родительского дома многие годы висела старая фотография в черной витиеватой раме. На ней изображалось лавандовое поле, выходившее далеко за пределы картины. В центре возвышался многолетний дуб, сквозь который пробивались первые лучи заката, а под дубом – скамейка. Выглядела она так, словно еще секунду назад была занята кем-то наслаждавшимся пейзажем, и пускай на всем снимке не было ни души, в нем неумолимо чувствовалось чье-то присутствие.

В детстве мне нравилось смотреть на это фото, представляя, какой Земля была прежде, до внедрения в космическое пространство. С каждым днем мир вокруг менялся до неузнаваемости, но этот небольшой клочек чего-то настоящего всегда был под рукой, висел над отцовским роялем. С такими мыслями я написал свою первую рапсодию, представляя себя сидящим на той самой скамье посреди лилового поля, в полном одиночестве и спокойствии наблюдающего закат.  Сейчас такие поля можно встретить лишь в старых фильмах, но порой, еще ребенком глядя на этот снимок, я чувствовал себя особенным, словно мне было известно что-то, чего другие и не пытались понять.

Искусство уже давно исчезло из списка востребованных вещей, так что я и не думал всерьез зарабатывать этим на жизнь, к тому же меня всегда привлекали звезды. Но и тогда я не мог представить, что однажды действительно окажусь посреди всего этого волшебства.  
Первые проведенные на Луне минуты казались мне приятно бесконечными. Не потому что они были длинней обычного. Просто время здесь словно замерло и, шагая дорогами этого нового мира, ты растворяешься в нем и чувствуешь себя частью вечности…

Эти эмоции и вызвали в моем сознании детские воспоминания, стоило мне лишь сойти со своего лунохода. А позже я увидел их — лавандовые долины, такие же прекрасные и бесконечные, как мне всегда представлялось.

\*

Прошло меньше месяца со дня моего прибытия, и мне уже практически удалось приспособиться к здешнему временному режиму. Минуты на м83 тянулось дольше, потому на сон обычно отводилось около четырех часов, а остальное время делилось на четверти.

Утром того дня я проснулся по сигналу будильника и отправился прямиков в ИИЛП. Моя теория была одобрена тридцатью тремя людьми – контрольной группой астрономов, астрологов, инженеров и докторов, с которыми я встречался и проводил митинги все это время. Параллельно этому я все время проводил за чертежами и планами трасс, пытаясь создать сои собственные, и к концу третей недели мне даже кое-что удалось, теперь оставалось лишь самое главное.

Я прибыл в Институт как раз вовремя, чтобы еще успеть выпить кофе до начала рабочего дня, а после отправился в выделенную мне лабораторию. Здесь было все, что только могло мне понадобиться и даже больше. Теперь мне с трудом верилось, что еще месяц назад я днями сидел над картами в тесной комнатке, больше походившей на подсобку.

– Какой Вы пьете кофе, Профессор? – в дверях лаборатории появился Штернбренер. В руках он держал стеклянную пластину-поднос с двумя дымящимися стаканами.

– Черный. Просто черный.

– Я так и думал, – он протянул мне один из стаканов, – а я вот предпочитаю добавить всего да побольше.

Очистив рабочий стол, я отпил кофе и предложил Штернбренеру сесть.

– Как продвигается работа? – спросил тот.

– Закончил все с час назад.

– Неужели?

Я кивнул.

– Рад слышать. Надо же… всего-то три недели прошло, – он улыбнулся.

– Да, но то, над чем я работал, все еще остается теорией. Вы зашли очень вовремя, Доктор. Мне нужна Ваша помощь, хотел обсудить это после обеда.

Штернбренер снял запотевшие от кофейного пара очки, и принялся протирать стекла.

– Я внимательно слушаю.

Я протянул ему график последних подсчетов.

– Пока все сходится, – осмотрев его, заключил Штернбренер. ­– Это ведь готовые результаты, можете смело направлять их дальше.

– Но прежде чем передать это выше, я бы хотел сам все протестировать.

Доктор удивленно поднял брови.

– Дело ведь серьезное, – добавил я, – хочу наверняка все проверить.

– Да уж тут Вы правы. Можно поднять этот вопрос на следующем митинге, не думаю, что кто-то будет против.

– Спасибо за это, но главное, что мне понадобится – это корабль.

– На м83 десятки тестовых кораблей, можете воспользоваться любым. А если не найдете нужной модели, всегда есть военные.

– Модель не имеет значения. Сейчас меня интересует только одна особенность: корабль должен быть пуст. Я имею ввиду, маршруты компании, путеводители и прочее – в нем не должно быть никаких отметок, а, насколько мне известно, все существующие корабли полны ими.

–…и почистить их никак нельзя, – Штернбренер понял мою мысль и ухмыльнулся. – Меня уже мутит от этой конфиденциальности.

Я решил пропустить его последнюю фразу.

– Придется отыскать «чистое» судно. Я самолично снабжу его последними звездными картами и сделаю круг от Луны до Земли и обратно.

Договорив, я взглянул на Доктора. Он прекратил протирать очки, и молча обдумывая мои слова.

– Нужно свериться с реестром, – наконец сказал Штернбренер. – Не уверен, что здесь вообще может быть подобный корабль, но мы это проверим.

– А если такого нет, Вы сможете спроектировать его для меня?

Его ответ не задержался ни на секунду.

– Смогу. Только я не могу быть уверен, что Совет одобрит подобное пренебрежение Вашей безопасностью. Даже если мы получим разрешение на подобный проект, нужна будет какая-то страховка.

– Я понимаю.

– Хорошо, а теперь расскажите мне подробно все, что потребуется для этой модели.

\*

К концу третей четверти того же дня я закончил все свои дела, связанные с планированием карт звездного неба, и успешно передал их в руки доктора Хартрайта. На данный момент было готово все то, что могло понадобиться для путешествия от базы до Земли и обратно. Поработать с самой Луной у меня пока еще не было возможности, а потому моим следующим шагом должно было стать исследование звезд с точки обзора непосредственно Луны и, конечно же, ее темной стороны.

Выйдя из здания Института, я зашагал прямиком к парковке, что находилась по другую сторону от входа, размышляя о том, как провести оставшееся время, ведь только что я закончил сложный проект и работать сейчас совсем не хотелось.

Уже приближаясь к своему лунному скутеру, краем глаза я заметил силуэт по правую сторону от себя и, обернувшись, увидел Капитана. Она стояла около одного из луноходов, глядя прямо на меня.

– Добрый вечер, Профессор, – произнесла она, направляясь ко мне.

– Рад Вас видеть, Капитан.

– Получила Ваш отчет сорок минут назад. Отличная работа, продолжайте в том же духе, и к концу следующего квартала о вашем труде станет известно всему миру, – она протянула мне руку, – Хотела поздравить Вас лично.

Немного смутившись ее слов, я неуклюже пожал ей руку.

– Благодарю, Капитан.

На мгновенье она замерла, словно обдумывая что-то, после чего кивнула и, поправив воротник своего пальто, сделала еще несколько шагов вперед и села за управление моего лунохода. Я все так же продолжал стоять посреди парковки, не понимая происходящего. Тогда Капитан обернулась.

– Садитесь же, чего вы ждете? – я уловил тень улыбки на ее лице. – Давайте немного прокатимся.

Все еще будучи немного растерянным, я все же опустился на сиденье лунохода позади Капитана.

– Держитесь, Профессор! – крикнула она. Я вовремя успел обхватить ее талию, потому что мы тут же взлетели, и поднялись так высоко над землей, как я не поднимался еще ни разу.

Поток ветра несся навстречу, развивая ее прекрасные синие локоны, а расстояние между нами и базой все увеличивалось. Мы поднялись выше уровня здания штаба, и теперь я мог видеть все пространство вокруг и даже ту часть коттеджного городка, что при взгляде с подвесной террасы казалась мне исчезающей в тумане луча.

Прямо под нами блестел корпус института, отражая синие блики фонарей, позади возвышались темные силуэты зданий для персонала, а впереди светился аэродром, за которым мирно дремал туристический городок. В этот момент я видел Луну так ясно, как никогда прежде, но что более примечательно – мне был виден сам луч, основа, на которой держалось все это чудесное место. Раньше я мог видеть лишь его отблески на зданиях по вечерам, но сейчас мне открывалось нечто большее, и я видел все.

– Это невероятно, – сказал я, стараясь перекричать шум, создаваемый потоком воздуха.

– Подождите еще минуту, – услышал я в ответ, – Сейчас зажгут огни.

Луноход на мгновенье замер над базой, после чего понес нас в сторону космодрома. Не отрывая взгляда от картины внизу, я с трудом успевал дышать, казалось, что весь мир вокруг нас замер ради этого момента. А потом зажглись огни, и, словно по велению чьей-то волшебной палочки, все вокруг осветилось. И это не был режущий глаза белый свет вроде того, что встречался мне в коридорах здания космодрома. Все пространство под нами было заполнено уютными теплыми огоньками, так напомнившими мне земные. И стоило мне лишь подумать об этом, как Отем произнесла:

– Такое чувство, что мы кружим над самой Землей, не правда ли?

– Да, – ответил я, – все именно так.

Мы сделали небольшой круг над коттеджным городком, местами снижаясь над вечерними садами и лужайками, и остановились над главной улочкой. Сейчас я увидел, что это место было заполнено туристами, они радостно сновали по дорогам внизу. Некоторые сидели в барах и ресторанчиках, другие же собрались на главной улице у большого экрана в ожидании какой-то старой киноленты.

Капитан сказала что-то, но погруженный в свои мысли, я не услышал ее слов, и Отем повернулась ко мне.

– Они не видят нас, – повторила она, уловив мой взгляд, – Сейчас слишком темно.

– Все так счастливы, там внизу. Или, по крайней, мере выглядят таковыми.

– Через две четверти многим из них придется возвращаться домой к старым проблемам и бесконечной работе, – ответила Отем, – Что еще им остается, как не быть счастливыми?

Я непроизвольно поднял брови, но ничего не ответил, надеясь, что Отем этого не заметила. И я снова ошибся.

– Вы чем-то удивлены, Профессор?

– Простите меня, Капитан, но для жителя м83 Вы слишком проницательны.

Улыбнувшись, девушка опустила взгляд. Мне показалось, что она смутилась, а потому я постарался поскорей сменить тему.

– Этот городок – невероятное место. Определенно одно из самых прекрасных, что я когда-либо видел.

– Да, я подумала так же, впервые увидев его. Мой старый друг спроектировал это место около шестидесяти лет назад.

– Невероятно, – повторил я. – Возможно, я встречался с Вашим другом?

– Вряд ли. Он вернулся домой буквально сразу после Вашего приезда.

– Что ж, должно быть, это сложно – покидать такой прекрасный мир.

Она медленно кивнула и, казалось, вновь погрузилась в свои мысли.

Мне хотелось спуститься еще ниже и присоединиться к жизни внизу, но я лишь спросил:

– Куда дальше, Капитан?

Мне показалось, что что-то в ее голосе изменилось, и, взглянув на нее, я понял что. Теперь слова Отем звучали иначе, потому что она улыбалась.

– Для начала к мостам, – ответила Отем, возвращаясь к управлению луноходом, – ну а после – к самой Луне, разумеется.

\*

Не снимая правую руку с пульта управления, я откинула с лица непослушную прядь волос и осмотрелась. Луноход приближался к одному из лунных мостов. Сегодня здесь было больше транспорта, чем в прошлый раз: выходные дни на Земле подходили к концу, и туристы спешили провести как можно больше времени, гуляя по местным долинам.

Из-за наплыва транспорта на спуске пришлось увеличить скорость, и Старлайт крепче обнял меня. Мы неслись вперед невероятно быстро, так что невозможно было различить силуэты. По обе стороны от нас виднелись лишь расплывчатые огни.

– Все в порядке? – спросила я, но не смогла разобрать ни слова из его ответа. Кажется, он был положительным.

Оставив позади мост, луноход вместе с нами погрузился в тоннель, который вел прямиком к Луне. С каждым мгновеньем она становилась все ближе, и голубые огни впереди нас принимали уже знакомые мне очертания.

Мы, наконец, оторвались от потока туристов, так что можно было сбросить скорость. Опустив взгляд, я наслаждалась пейзажем, раскинувшимся внизу. Уже который год я пролетала над этим местом, и с каждым разом оно казалось мне все более прекрасным, ведь мы приближались к лавандовым долинам.

Я опустила луноход около одной из тропинок, и, расстегнув ремень безопасности, повернулась к Старлайту. Он смотрел куда-то вдаль от меня, на долины, уходящие далеко вперед и старый дуб, многие годы растущий в этом месте.

– Вот мы и на месте, Профессор.

Он улыбнулся, все еще не отрывая взгляда от картины впереди. Сейчас над долинами стояли первые сумерки, и я видела, как их цветовая палитра отражалась в его карих глазах. Удивительно, как же сильно этот жизнерадостный молодой человек напоминал мне себя прежнюю. Десять лет назад я так же зачарованно смотрела на это место.

– Здесь всегда так красиво? – спросил Старлайт.

– Да, но на закате эти долины особенно очаровывают. Люблю временами погулять здесь, особенно теперь, если под рукой есть хорошая книга.

– Книга? – удивился он, и, переведя взгляд на меня, тут же улыбнулся – Вы имели в виду текст?

– Нет, книги, но я понимаю Ваше удивление.

– Чего я точно никак не ожидал встретить на м83, так это книги. Их-то и на Земле сейчас толком не найдешь.

– Да, это длинная история.

– Не расскажите?

– Один мой друг, любитель былых времен, оставил их мне перед возвращением домой.

– Тот самый друг, что создал коттеджный городок? – догадался Старлайт, и я кивнула. – Вы, должно быть, скучаете по нему.

– Не знаю, – честно ответила я, – временами да, но я уже давно привыкла быть одна, к тому же у него просто не было другого выбора, кроме как вернуться на Землю, тогда как мое место здесь.

– Это все звучит так печально.

– Вовсе нет, Профессор. Иногда ты просто должен делать то, что должен, и однажды светлое будущее окажется твоим настоящим.

После этих слов Старлайт посмотрел на меня как-то иначе, и мне вновь подумалось, что за всю свою жизнь я ни разу не встречала человека, собственное сходство с которым так сильно бросалось бы мне в глаза.

Он снова окинул взглядом долину.

– Нам пора идти, Профессор, если Вы, конечно, хотите успеть насладиться этим местом до наступления темноты, – поторопила его я, и наклонилась к нему, дабы расстегнуть ремни безопасности.

Внезапно Старлайт посмотрел прямо в мои глаза, и это заставило меня на мгновенье затаить дыхание. За многие годы, проведенные на базе, мне не часто приходилось видеть на себе чей-то теплый взгляд, хотя, возможно, я просто не замечала этого раньше.

Он провел рукой по моей щеке, и прежде, чем я успела хоть как-то выразить удивление, коснулся моих губ своими. Это было так невероятно, словно поцелуй героев одного из тех черно-белых фильмов, что я когда-то любила пересматривать.

– Я мечтал об этом с самой нашей встречи.

Он улыбнулся, и я ответила тем же, все еще пытаясь собраться с мыслями.

Старлайт поднялся, протянул мне руку, и мы молча зашагали вдоль лавандовой долины.

\*

– Даже не верится, что оно не настоящее, – произнес Старлайт, глядя на золотые лучи солнца.

Мы сидели на плетеной скамейке, расположенной в самом центре долины. Солнце опускалось все ниже, приближаясь к линии горизонта и заливая теплом все вокруг.

– Все дело в отражателях… – начала я.

– Нет, не говори мне ни слова об этом, прошу тебя. Не хочу знать, чем картина перед нами является на самом деле. Здесь все в действительности выглядит гораздо естественней, нежели теперь на Земле, и мне не хотелось бы думать, что это всего лишь очередной технологический прорыв, – его ладонь накрыла мою, и про себя я отметила, какими горячими в этот момент мне показались его пальцы.

– Хорошо, Старлайт, – я улыбнулась.

– Твои руки такие холодные, – словно прочитав мои мысли, сказал он.

– Температура моего тела 81, 14 градус по Фаренгейту, – ответила я, и, встретив его удивленный взгляд, добавила: – Со временем к этому привыкаешь.

– К чему?

– Подобным метаморфозам. Поначалу их не замечаешь, а потом быстро втягиваешься. – я опустила глаза, – Влияние Луны меняет тебя до неузнаваемости, я ведь не всегда была такой.

Все так же не отводя свой теплый взгляд, Старлайт взял меня за руки и, поднеся их к лицу, поцеловал.

– Ты прекрасна, Отем, – сказал он.

\*

Открытые для посещений туристами семнадцать процентов лунной поверхности схематически делятся на восемь секторов, в каждом из которых находится несколько таких чудесных мест, и все они отвечают за определенное время суток, которое, в свою очередь, смещается каждую четверть.

Когда цветы лаванды опустились, а солнце исчезло за горизонтом, мы направились в сторону золотого парка, раскинувшегося через сектор от долин. Здесь всегда стояла осень. Солнце озаряло своим ласковым светом широкие кроны деревьев вокруг, придавая им еще больше красок.

Отставив верхнюю одежду около лунохода, мы опустились на пожелтевшие листья травы. Старлайт рассказывал мне о проделанной работе, своем восхищении звездами и о том, что ему непременно еще предстоит совершить. Конечно, мне уже было известно об этом все, но я не хотела прерывать его рассказа: этот голос меня успокаивал. Переполненные эмоциями, его слова звучали так по земному, и с каждой новой фразой я слышала в них все большее желание жить и следовать своей цели. В этот самый момент я поняла, что жизнь больше не выглядит застывшей на месте. Мне показалось, что даже голос моих собственных мыслей звучит теперь иначе, более выразительно и оживленно.

Вдалеке, расположившись на уютных скамейках, в тени среди сосен оживленно болтало несколько туристов, а еще дальше невысокая девушка в соломенной шляпке фотографировала улыбающегося мужчину с ребенком на плечах.

– В начале следующей недели состоится собрание, на котором решится вопрос о моем участии в тестировании, – говорил Старлайт. – Штернбренер считает, что у меня неплохие шансы на этот счет.

Он вздохнул.

– Заручиться поддержкой главы строительного отдела – не так уж и плохо, к тому же, думаю, Доктор Хартрайт также поспособствует продвижению твоей идеи. Ты ведь говорил, он вполне добродушный.

– Да, он хороший человек, а вот на счет де ла Круа я не могу быть уверен, очень уж он хмурый тип.

– Вот как.

– Никогда не поймешь, что у него на уме. Мой отец называл таких пасмурными людьми.

Я улыбнулась.

– Здесь ведь все такие, Профессор.

– Да, не без этого, – Старлайт улыбнулся в ответ, – но только не в институте, там дела обстоят совсем иначе.

– Правда? – я удивленно подняла брови, и Старлайт кивнул.

– Ты разве прежде не замечала?

– Честно говоря, никогда не обращала на это внимания.

Он приобнял меня за талию, и, облокотившись на его плечо, я обратила взгляд к небу. Облака еще никогда не казались мне такими прекрасными; верхушки елей тянулись к ним, сплетаясь над нашими головами в золотой венок.

– Словно здесь есть абсолютно все, – произнесла я, не отрывая взгляда от картины, что была над нами.

– Абсолютно все, – согласился Старлайт, – такой идеальный маленький мир, ведь именно таким задумывал его твой друг. Хотел бы я с ним познакомиться.

– Думаю, у тебя еще будет возможность разыскать его с возвращением на Землю.

Старлайт ничего не ответил, а лишь крепче обнял меня, и я почувствовала касание его теплых губ около виска.

– За все эти годы я не единожды облетела Луну, и будь у меня возможность, я бы добавила только одну вещь – поля, полные алых роз.

– Неужели их здесь все еще нет? – улыбнувшись, спросил Старлайт.

Я покачала головой.

– Корнуэлл мечтал построить в седьмом секторе каменную башню, с которой бы открывался вид на поле из алых роз, говорил, что читал о подобном в одной из своих книг. Работал над полем многие годы, и все это время периодически видел эту картину в своих снах. Но розы так и не прижились на Луне, их не обманешь искусственным солнцем.

Старлайт, казалось, задумался о чем-то, после чего сказал:

– Тебе, должно быть, присуще хорошее воображение, раз, не смотря на влияние этого места, ты все так думаешь об этом поле.

– Дело не в поле, а в самом этом цветке, – ответила я. – Он очаровывал меня еще с детства, и, глядя на вазоны на соседском балконе, я думала о том, как однажды поселюсь в тихом далеком месте, где перед моими окнами каждое лето будут расцветать кусты роз. Удивительно, я ведь уже давно забыла об этом, и вспомнила только сейчас.

– Давно ты здесь? – спросил Старлайт.

– Немного более десяти лет.

На его лице проявилось удивление.

– И ты ни разу не задумывалась о том, чтобы вернуться? Хоть ненадолго.

– Никогда, – ответила я. – Я совсем не из тех, кто тоскует по дому.

Должно быть, тогда впервые за все это время я действительно задумалась о том, как бы сложилась моя жизнь, вернись я сейчас на Землю. Но я так и не нашла ответа на этот вопрос.

– Кажется, я совершенно не принадлежу к той жизни, – после небольшой паузы добавила я. – Ну, не чувствую я в себе ничего земного.

– Верю, – ответил Старлайт. – Когда я впервые тебя увидел, ты напомнила мне Луну, словно какое-то волшебное отражение этого места, а сейчас я понимаю, что без тебя Луна и вовсе не была бы Луной.

Что-то внутри меня словно на миг замерло после его слов, а затем затрепетало быстрее прежнего, и мне вспомнилось стихотворение о синей птице, которое я прочла в одной из книг Корнуэлла.

Я провела рукой по темным волосам Старлайта, и поцеловала его, вновь ощутив себя в одном из тех старых фильмов.

\*

Когда я вернулся в свою комнату, последняя четверть подходила к концу, и я сразу же плюхнулся на просторную кровать. Это был первый раз, когда перед сном я не бросил взгляд на открывающийся за окнами вид, ведь все, о чем сейчас хотелось бы думать, было прямо в моей голове.

Спустя пару минут я уже погрузился в сон. Той ночью мне снилось полное роз поле, я брел по нему в поисках чего-то очень важного, а впереди меня ждал бесконечный алый закат. И проснувшись утром следующего дня, первой моей мыслью было: «А я ведь знаю эту книгу».