---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# По другую сторону Луны {#06}

Первая четверть приближалась к концу, и, покончив с работой, я направлялся в лагерь. Думал подождать Джека. За последние сутки у меня возникло к нему несколько вопросов, но сегодня тот, должно быть, решил припозднится. Дела можно будет обсудить и позже, а вот чувство голода за время ожидания только усилилось.

Я переоделся, и, аккуратно расправив форму, повесил ее в дальний угол своего шкафчика. Не знаю, к чему была вся эта щепетильность: кроме сменщика мне здесь мало кто встречался, так что, я делал это, скорей, автоматически.

«Хорошо, что они все же построили эту дорогу», - думал я, шагая по стеклянному тоннелю, ведущему к лагерю от самого тринадцатого поста. Коридор впереди меня был тускло освещен, что спасало глаза от возможности резкого света: фактически, эта часть Луны все еще была темной и, соприкоснувшись с чрезмерно ярким светом после полного рабочего дня, ты рисковал временно потерять зрение.

Когда-то, до постройки надземного тоннеля, нам приходилось носить массивные скафандры с кислородными рюкзаками и перемещаться по поверхности на луноходах. Не том подобии скоростных мотоциклов, которые на м83 называют луноходами, а настоящих стальных шестиколесных монстрах, которые весят добрых пять тонн. И, в отличие от тех луноходов, наши по-прежнему не могли подниматься над поверхностью. На этой стороне Луны такое еще попросту не нужно.

Лагерь находился в получасе ходьбы от тринадцатого. Это был последний и самый дальний пост, и, шагая по тоннелю, я то и дело бросал взгляд на остальные посты, расположенные на ледяной поверхности за стеклом. Иногда по пути назад мне встречались другие бурильщики, но не сегодня. В этот раз, ожидая сменщика, я пробыл на рабочем месте немного больше обычного, так что они, скорей всего, уже были далеко в конце коридора.

Царившая здесь тишина порой сводила с ума, а иногда наоборот приходилась весьма кстати, как, например, сегодня. Сейчас даже самый крохотный шум показался бы мне разрушительным, столь выжатым я себя чувствовал.

Добравшись до лагеря, я решил, что поем уже после пробуждения. Голод отступил, уступая место усталости, и я сразу же завалился в постель.

«Странно, он ведь никогда не опаздывал», – услышал я собственные мысли, и тут же забылся сном.

\*

– Какого черта? – прохрипел я, и, оторвав лицо от подушки, протянул руку за сигаретной пачкой.

Надо мной стоял Райан Харди из двенадцатого. Вид у него был глуповато растерянный.

– Джек пропал.

Я прекратил рыться в ящике, и удивленно уставился на своего коллегу.

– Что значит пропал?

– Пропустил свою смену. И в лагере его нет. Они сейчас все кругом обыскивают. Военные. Что ты ищешь?

– Сигареты.

– Ты бросил курить семь лет назад, – ухмыльнулся Райан.

– Зря.

Я вздохнул. Старые привычки никуда не исчезают.

– Поднимайся, Джо, работа стоит. Нужно чтоб ты наверстал там все.

– Ладно, но только сегодня. Не могу же я один следить за тринадцатым, – я устало потянулся и с неохотой направился в душ.

– Придется перебиваться так до конца недели, может из наших кто подсобит. Они пришлют нового человека к понедельнику, – бросил мне вслед Райан.

\*

Вернувшись в тринадцатый, я приглушил освещение и проверил мониторы: никаких изменений после моего ухода. Пытаясь выяснить, что же произошло с моим напарником, я решил просмотреть предыдущий отчет Джека. В другие дни мы делали это раз в неделю, прежде чем направлять бумаги капитану. Обычно они отправлялись по внутренней связи, а раз в квартал к нам наведывались ребята старпома, бледная молчаливая армия, для полной проверки.

Мой взгляд скользил по, казалось, застывшим страницам отчета, не находя, ровным счетом, ничего нового: бурение участка С проходило без изменений. Еще несколько часов я следил за датчиками, составляя новый доклад, и периодически поднимал глаза на звезды.

Своим видом тринадцатый напоминал стальной подземный бункер с единственным небольшим окном в потолке, из которого был виден крохотный отрывок звездного неба. И вот я вновь смотрел на него, размышляя о том, куда же мог подеваться мой первый сменщик. Вряд ли бы он стал исчезать по собственной воле, еще и за год до пенсии. Нет, здесь определенно было что-то еще.

Когда очередная четверть подошла к концу, и я закончил свой доклад, какая-то еле уловимая мысль проскользнула в моей голове. Я вновь схватился за отчет Джека. Здесь было все верно, только вот последние данные вносились за час до окончания его смены, а старина Джек был не из тех, кто любил работать, задрав ноги на стол. Тогда я зафиксировал текущие показатели датчиков, и принялся отматывать их до последнего часа, указанного в отчете Джека. Действительно, все гладко, но вот к концу четверти был найден явный сбой. Что это, подземные толчки? Перепады давления? И почему Джек не внес их в отчет?

Если верить датчикам, эти толчки продолжались на протяжении двадцати минут. Показатели на аппарате измерения подземного давления росли, и к концу указанного времени стрелка стремилась далеко за пределы максимальной нормы. Я переписал координаты и сверил их с базой данных. Результат загрузился мгновенно, и я увидел, что указанный участок находился всего в десяти минутах езды от тринадцатого.

Кое-как мне удалось досидеть это смену, после чего я буквально понесся на нижний ярус нашего пункта, где провел еще какое-то время, пытаясь втиснуться в скафандр. Прошло больше пяти лет с того момента, когда мне в последний раз приходилось надевать его. Когда мне, наконец, удалось это сделать, я интуитивно заглянул в шкафчик Джека: его лунного костюма не было на месте. Затем я проверил кислород, надел шлем, и, выйдя из бункера, направился в сторону луноходов.

Шагая по лунной поверхности, я едва ли мог устоять на ногах. К счастью, стоянка находилась всего в нескольких шагах от тринадцатого пункта, и вскоре я с облегчением вздохнул, усевшись на один из луноходов.

Машина уносила меня все дальше от тринадцатого. Казалось, что с каждой минутой вокруг становилось только темней. Возможно, картина в моих глазах просто тускнела от внезапно нахлынувшего холода и постоянных скачков лунохода (земля подо мной была сплошь и рядом укрыта неровностями, а под колесами то и дело попадались замерзшие камни). Зубы начинали скрипеть от режущего тело холода, но я старался не отводить взгляда от карты с маршрутом. Сейчас нужно было сворачивать налево. Я присмотрелся, но ничего не заметил в темноте, когда луноход вдруг стремительно полетел вниз. Вскрикнув, я почувствовал во рту привкус крови. Кажется, я прикусил язык.

Луноход стоял прямо в центре одного из многочисленных кратеров, а я сидел на нем, по-прежнему не решаясь сойти. Температура здесь была в разы ниже по сравнению с поверхностью. Голова начинала кружиться, а вокруг была одна лишь тьма.

Я медленно поднял голову и сквозь замерзшее стекло скафандра увидел небо, покрытое тысячами звезд. В последний раз я видел их такими яркими, стоя около входа в Гайд-Парк в ожидании Лии, белокурой подруги моей молодости. Как давно это было? Лет десять назад… нет, двенадцать. Интересно, что сейчас с ней стало?

Словно стараясь привести мысли в порядок, я тряхнул головой и зажег лучи ближнего света. Находясь в этом месте, я чувствовал себя в неком подобии вакуума, который забыли закрыть, и теперь дышать становилось сложней. Тогда я принялся осматриваться вокруг. Как и везде, поверхность здесь была замерзшей и немного рыхлой после бурения. Никаких следов чьего-либо присутствия. Затем прошелся лучом по каждому сантиметру стен кратера – и здесь без изменений.

Теперь мне ничего не оставалось, как вернуть луноход обратно в тринадцатый, а после хорошенько выспаться. Но все мои мысли занимали внезапные нарушения давления под землей и, конечно, Джек. На все это должна была быть какая-то причина, или, хотя бы, объяснение. Не мог ведь он просто исчезнуть.