---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Тоннель {#07}

– Выглядишь устало, – заметил Сириус. Он сидел за столом моего кабинета, не сводя глаз с недавно полученных отчетов. – Ты сколько сегодня спала?

– Это не важно, отдохну на выходных, – отмахнулась я, и, закрыв окно, пересекла комнату, дабы вместе со старпомом склониться над бумагами.

Еще какое-то время мы молча просматривали страницу за страницей, после чего Сириус откинулся назад и устало протер глаза.

– Ничего я в этом не смыслю, – признался он.

«Помощь Корнуэлла была бы сейчас как нельзя кстати» - подумала я, и лишь пожала плечами. Мне и самой была чужда подобная работа, так что я с трудом могла разобрать указанные в отчете данные и сложить их в общую картину.

– Тот парень, – начала я, и опустила взгляд на бумаги в поисках имени, – Джоуэлл Блек…

– Бурильщик?

– Да, нужно поговорить с ним. Думаю, он сможет с легкостью объяснить все эти показатели и данные.

– Хорошо, – кивнул старпом, – сегодня же дам распоряжение.

– Нет нужды. Я сама могу переговорить с ним, у меня как раз есть дело на темной стороне, которое еще предстоит завершить, – и, поднявшись со своего кресла, я направилась в сторону выхода.

– Отем, – позвал меня Сириус. Я обернулась. – Надеюсь, сенатор Куинн в курсе твоих дел?

– Разумеется, – ответила я, и вышла из кабинета.

Исчезновение сотрудника тринадцатого пункта подняло на м83 немалую шумиху. Эта новость настигла меня воскресным утром, и вот уже вторые сутки я проводила без сна в попытках прояснить события того дня, когда Джек Метьюз пропал без вести. Сириус, конечно, неплохо мне в этом помогал. Его парни ни на минуту не прекращали поиски, но Совет состоится уже завтра, и если расследование не принесет результата, мне самолично придется объясняться с сенатором.

Спустившись на этаж ниже, я позвонила в дверь расположившейся под моим кабинетом комнаты. За стеной раздались шаги, и вскоре на пороге появился Старлайт. Одетый в потертые джинсы и наспех накинутую рубашку, он, должно быть, только вернулся из ИИЛП.

– Отем, – на его лице засияла очаровательная улыбка, – а я уже начал думать, что ты меня избегаешь.

– На м83 намечаются проблемы, я могу войти?

– Конечно.

Старлайт отступил в сторону, и когда дверь за моей спиной опустилась, я продолжила.

– Один сотрудник пропал на прошлой неделе, и мы все еще не можем найти его, – я села в стоявшее у входа кресло, и Старлайт опустился рядом со мной. Он прижал меня к себе, и, увидев мою усталую улыбку, спросил:

– Хочешь чего-нибудь выпить?

– Виски. Но мой рабочий день еще не окончен, так что кофе тоже сойдет.

Поцеловав меня, Старлайт зашагал в сторону кухни, и пока он возился с кофе, я рассказывала о том, почему вскоре собираюсь отправиться на темную сторону Луны.

– Ты говорил, что хотел бы поработать и с той частью звездного неба, – продолжала я, – Можешь пойти со мной, если силы еще есть.

– Да, я совсем не против, – ответил Старлайт, протягивая мне чашку горячего кофе.

– Тебе нужно взять что-нибудь в институте?

– Нет, все здесь, – он улыбнулся и поднес указательный палец к голове.

– Хорошо, тогда можешь начинать собираться. И советую тебе одеться потеплей. Там стоит жуткий холод, не смотря на туннель.

\*

Мы брели по стеклянному туннелю уже около двадцати минут. Погруженная в свои мысли, Отем шагала рядом. Ее бледные запястья скрывались в черном пальто, а шею укутывал вязаный шарф. Здесь было так тихо, что я с легкостью мог услышать ее на удивление ровное дыхание.

Окружающий меня холод напоминал о времени, проведенном в старом фамильном гнездышке, тех его днях, когда первые хлопья декабрьского снега мягко ложились на замерзшие ладони, и все вокруг, казалось, было укрыто этим белым сном. Но тогда под снегом скрывались и звезды, а сейчас мне стоило лишь поднять взгляд к небу, дабы увидеть всю их безмолвную красоту.

Не преодолев и половину пути, я пожалел, что не взял с собой кофе, ведь пространство вокруг только и дышало холодом.

– Все-таки замерз, – произнесла Отем, и взяла меня под руку.

– Не представляю, как в этом месте можно работать.

– Там, куда мы направляемся, немного теплей, – улыбнулась она, – только вот жутко мрачно.

Наконец, среди царившей вокруг нас темноты, я начал различать силуэты зданий, сжавшихся у стен тоннеля.

– Это и есть второй институт? – спросил я, глядя на угрюмое стальное сооружение. В нем было не более двадцати этажей.

– Да, а за ним – тринадцать пунктов бурения. Пропавший Джек Метьюз работал на последнем из них.

Немного помедлив, я все же решился спросить:

– У тебя есть какие-то мысли на этот счет?

– Никаких, – призналась Отем.

– А что насчет пиратов? – спросил я, и, увидев на лице Отем улыбку, поспешно добавил: – Когда-то они не сходили с первой полосы новостей.

– Никаких новых объектов зафиксировано не было, да и внезаконники уже несколько лет не давали о себе знать. Все утихло после истории с «Алым Орионом», я тогда еще не была капитаном.

Я хорошо помнила это время. Около трех лет назад, когда лунный туризм только-только достиг пика своей популярности, вооруженная группа людей, прибывших на звездолете под названием «Орион» пыталась захватить коттеджный городок. Численность жертв превысила сотню, после чего пиратский корабль упоминался лишь как алый. В свете событий того дня смертная казнь вновь была узаконена, и участникам захвата была введена инъекция смертельной дозы барбитуратов.

– Вот мы и на месте, – сказала Отем, и я осмотрелся.

Мы стояли около стальной двери, ведущей к зданию института, а стеклянный коридор перед нами все так же тянулся на многие мили вперед.

Отем поднесла свой браслет к двери, и, пройдя авторизацию, мы вошли. Внутри практически не было света, но я тут же почувствовал в воздухе смену температуры, и вскоре с облегчением расстегнул пальто.

В тускло освещенном пространстве перед нами виднелась парочка лифтов и очередной коридор, уходящий вглубь здания.

– Снова лифты, – протянул я.

– Здесь везде сплошные лифты и коридоры, – улыбнулась Отем, – но все это с лихвой компенсируется природой по ту сторону Луны. Ты привыкнешь.

Я не мог с ней не согласиться.

Она вызвала лифт, и, приподнявшись на носочках, коснулась губами моей щеки.

– Поднимайся на последний этаж, там расположена обсерватория. Я поговорю со сменщиком Метьюза, и буду ждать тебя внизу, когда закончишь.

– До встречи.

Войдя в лифт, и хотел пожелать Отем удачи, но она уже исчезла за его закрывающейся дверцей.

Наверху не было ни души, и я с трудом мог различить очертания предметов вокруг. Темнота вызывала у меня ассоциации с открытым космосом, и это ощущение лишь усилилось, когда мне, наконец, удалось увидеть звезды.

Войдя в обсерваторию, и оказавшись под сияющим покрывалом звезд, я отметил про себя, что снаружи это место казалось мне намного меньше. В итоге мне все равно пришлось включить свет, дабы найти для себя рабочее место.

В самом центре зала был расположен немыслимых размеров сенсорный стол, а рядом – несколько кресел, не особо удобных на вид. Я подошел к столу, и, скопировав данные со своего браслета, вывел на экран последние карты звездного неба, сделанные мной. В той части, что отвечала за видимый с темной стороны Луны участок, все еще красовался немалый пробел.

– За дело, – произнес я, и погасил свет.

\*

– Но почему Вы не упомянули об этом во время предыдущей беседы с нашими людьми? – удивленно спросила я, когда Блек закончил свой рассказ.

Он развел руками.

– Мне так и не довелось лично пообщаться с военными, – ответил Джоуэлл.

– Но в отчете также нет ни слова…

– Да, я составил его еще до того как мне пришло в голову отмотать счетчики.

– И Вы не потрудились тут же сообщить об этом?

Должно быть, я произнесла эти слова слишком строго, и, замешкавшись на мгновенье, Блек принялся оправдываться.

– Закончив все дела, я тут же отправился спать. Пожалуй, это было неосмотрительно с моей стороны, но ведь я так и не нашел ничего объясняющего события той четверти. Простите, Капитан, я очень устал, – и, положив руки на стол, он опустил в них голову.

– Мы все здесь очень устали, – ответила я, и, попытавшись придать своему голосу более доброжелательный тон, добавила: – И мы также очень волнуемся.

– Но, боюсь, мне правда больше нечего добавить, – его голос звучал слишком измученно, и я решила, что пора завершить наш разговор.

– Я вижу. Но Вы ведь непременно сделаете это, если будет такая возможность, не так ли?

Блек медленно кивнул.

– Не сомневайтесь.

– Хорошо, тогда не вижу смысла Вас больше задерживать, – я протянула ему руку, и Джоуэлл пожал ее – В любом случае, благодарю за сотрудничество.

– Нет проблем.

– Кстати, как дела с новым работником?

– Все в порядке, Капитан. Парень не промах, согласился поработать сегодня за меня, а то я уже просто с ног валюсь.

– Очень хорошо. Тогда можете отдыхать.

– Спасибо, Капитан.

И он удалился.

Еще несколько минут я просидела за столом восьмой аудитории, сопоставляя в голове полученные факты и пытаясь привести мысли в порядок, после чего вслед за Джоуэллом направилась в сторону лифтов.

В мыслях возникали запомнившиеся строки из «Дракулы», которую я прочла еще совсем недавно, но со всей этой шумихой, поднятой вокруг исчезновения Метьюза, мне казалось, что это было тысячи лет назад. Подобно Джонатану Харкеру я брела темными коридорами, обдумывая предстоящий разговор с сенатором. На самом деле это был мой первый промах на должности капитана, и я совершенно не знала, что буду говорить.

В который раз я пожалела о том, что Корнуэлла нет рядом. На фоне этих мыслей к душе подкралась давно забытая дрожь. «Должно быть, это и есть волнение», – подумалось мне. Земные чувства, нахлынувшие на меня с новыми силами, в последнее время становились все более заметными. Возможно, дело было в Старлайте: его присутствие вызывало немало эмоций, словно, возвращая меня к жизни. А, возможно, Корнуэлл был прав, и я действительно отличалась от других обитателей м83. Так или иначе, но я больше не могла это игнорировать.

Не сбавляя ход, я связалась с Сириусом.

– Ты быстро, Капитан, – произнес он, – Есть указания?

– Нужно чтоб ты послал нескольких человек для детального обыска кратерной зоны около тринадцатого пункта. И пускай с вами отправляется кто-то из ИИЛП, знающий толк в бурении. Дай мне знать когда закончите.

– Хорошо, а координаты?

– Вышлю через минуту, – ответила я, и отключилась.

Сириус мне всегда нравился. Он был типичным представителем местного населения. Старательно служащий своей стране, он превосходно владел военными навыками, приобретенными в Космической Академии, а главное – не задавал лишних вопросов, если дело принимало серьезный оборот.

Дойдя до лифтовой площадки, я переслала Сириусу полученные у Блека координаты кратера и, прислонившись к стене, ждала Старлайта.

От усталости закрывались глаза, а мысли путались, я чувствовала как проваливаюсь в сон, но уже ничего не могла с этим поделать. К реальности меня вернул звук открывающегося лифта, и я поняла, что сижу на полу.

– Черт, Отем, ты в порядке?!

На лице Старлайта проступило беспокойство, он помог мне подняться.

– Все хорошо, я просто устала, – я обняла его, – пойдем.

– Уверена что ты в порядке?

– Однажды мне пришлось не спать более восьми суток, так что да, Стар, я в абсолютном полном порядке.

Он лишь вздохнул, и мы медленно зашагали обратно к базе.

– Есть новости? – спросил Старлайт, когда мы вошли в тоннель.

Я кивнула.

– Ситуация хоть немного прояснилась? Потому что ты не выглядишь воодушевленной.

– Дело приняло странный оборот, но от этого все стало лишь более запутанным, и, если честно я надеялась, что разговор с Блеком будет более продуктивным.

– И что теперь?

– Дождусь новостей от старпома, а после снова примусь за отчеты Метьюза, его личное дело… любые документы, какие только смогу отыскать, – я вздохнула. – Должно же здесь что-то быть.

Старлайт остановился и посмотрел мне в глаза.

– Ты отличный капитан, Отем, и я знаю, ты не опустишь руки, – говорил он, – но теперь для тебя самое время отдохнуть. Ты выглядишь очень вымотанной и вряд ли сейчас можешь что-либо сделать.

Старлайт был прав, отсутствие отдыха и вновь обретенное волнение как никогда давали о себе знать. К тому же у меня было непреодолимое предчувствие касательно зоны около тринадцатого: я знала, что они ничего там не найдут. К тому же, завтра мне, так или иначе, предстоял серьезный разговор с сенатором, и, за неимением других вариантов, оставалось только выспаться перед этим.

– Должно быть, ты прав. Сейчас я ни на что не гожусь.

Я вдруг вспомнила, что так и не спросила у Старлайта о его работе в обсерватории, и тут же поспешила сделать это.

– Постепенно заполняю пробелы, – ответил он. – Понадобится провести там еще несколько четвертей, и общий план будет в твоих руках.

– Что ж, учитывая обстоятельства, тебе еще не раз представится возможность посетить эту сторону Луны. Можно повысить приоритет твоего пропуска, если хочешь быстрей с этим покончить.

Старлайт улыбнулся и прижал меня к себе.

– Ну уж нет, – ответил он, – у меня совершенно нет желания в одиночку бродить по этим мрачным коридорам.