---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Вечная Роза {#08}

Казалось бы, этим вечером я была вымотана как никогда, но вот уже на протяжении второго часа не могла сомкнуть глаз. Мысли о пропавшем сотруднике не желали исчезать из моей головы, все никак не позволяя мне забыться сном. Тогда я решила дать себе еще полчаса, и, поставив одну из пластинок Корнуэлла, завалилась обратно в постель.

Доносившиеся с проигрывателя звуки музыки успокаивали. Вслушиваясь как можно лучше, дабы освободить голову от тревожных мыслей, я старалась припомнить хорошие моменты из своей жизни. Как оказалось, их было не особо-то и много: кое-что из детства, последний день в академии, начало работы на м83, но, так или иначе, все сводилось к Старлайту.

В день нашей первой встречи, лишь взглянув в эти полные энтузиазма глаза, я вспомнила себя прежнюю и ощутила чувство некогда утраченной близости. Так, словно мы уже были знакомы в другом, более радужном периоде наших жизней. Странное было чувство, но меня это не пугало.

Полчаса были на исходе, когда я услышала, как заиграла давно забытая мелодия Бостона, говорившая о «Более чем чувстве», и внезапно мои мысли прояснились. Почувствовав новый прилив сил, я мгновенно сложила проигрыватель и пластинки обратно в коробку, и, не замечая ее тяжести, спустилась на этаж ниже.

В коридорах штаба не было слышно ни звука, я знала, что единственным, кто мог мне встретиться по пути, был дежурный, находящийся в самом низу здания.

Я позвонила, и дверь почти сразу же отворилась.

– Не могу уснуть, – объяснила я. – Не против, если я побуду с тобой?

Старлайт улыбнулся и прижал меня к себе. На нем были только джинсы, и я почувствовала неловкость за то, что, возможно, вытащила его из постели.

– Я рад что ты здесь, милая. И прости, что я в таком виде, на этот раз тебе удалось застать меня врасплох, – говорил он, все еще не выпуская меня из своих теплых объятий.

– Ничего, Старлайт, мне это даже нравится, – рассмеявшись, ответила я.

Он улыбнулся, и заглянул мне прямо в глаза. В этот момент мне подумалось, что никогда прежде ни один мужчина не смотрел на меня так, как сейчас он.

– Что в коробке? – спросил Старлайт.

Я улыбнулась.

– Сейчас увидишь. Мой старый друг кое-что оставил для меня, прежде чем вернуться на Землю, – говорила я, распаковывая коробку. – Мне кажется, теперь я стала более чувствительна ко всему, что происходит вокруг.

Стар заинтересованно смотрел на меня.

– На протяжении последнего месяца музыка помогает мне справляться со всяческими переживаниями, – объяснила я.

После этих слов я увидела сияющие огоньки в глазах Старлайта.

– Ничего себе, – произнес он, разглядывая стопку пластинок, – Я могу взглянуть?

– Конечно, – улыбнулась я. – Помоги мне выбрать, что поставить.

Невероятно чудесно и приятно было наблюдать с какой искренней, чуть ли не детской радостью Старлайт держал пластинки в своих руках.

– Эту, – определившись с выбором, сказал он, и протянул мне «Шоссе Красных Роз» Маккартни и группы «Крылья».

– Хорошо.

Я поставила пластинку.

Старлайт принес немного виски, и мы расположились на уютном диване в центре комнаты.

– Винил совсем иначе передает музыку, ты заметил? – сделав глоток виски, спросила я.

– Да, я понял это еще в самом детстве.

– Удивительно замечать такие вещи только сейчас.

– Знаешь, почему я выбрал именно это пластинку?

Я покачала головой, не сводя со Старлайта глаз.

– Меня подтолкнул к этому твой рассказ о розовом поле, – он улыбнулся и, словно смутившись, продолжил: – На самом деле меня сразу же очаровала эта идея, и она не отпускает меня до сих пор. У меня даже был сон, в котором я неустанно прогуливался по полю, заполненному алыми розами. И эта книга…

– Темная Башня, – подсказала я.

– Да, я вспомнил, что читал ее многие годы назад.

– Я обнаружила ее в стопке оставленных мне книг. На самом деле я только начала читать ее. До этого хотела взяться за Коллинза, но, увидев обложку и это поле на ней, просто не смогла устоять.

– После этого сна, – говорил Старлайт, – я кое-что вспомнил. В этой книге описывался образ розы, растущей в мире хаоса, и при одном лишь взгляде на этот цветок сердце трепетало как никогда, а слезы наворачивались на глаза – настолько она была прекрасна…,– он отставил стаканы с виски, и провел рукой по моей щеке и волосам, – И тогда я подумал о тебе, Отем.

Все еще не в силах произнести ни слова, я обхватила его шею и поцеловала губы, горячие как и его сердце.

\*

Следующим утром я открыла глаза за полчетверти до начала совета. Еще никогда прежде я не чувствовала себя столь спокойно; все вчерашние проблемы отошли на второй план и даже теперь, когда мне совсем скоро предстояло объясняться с сенатором Куинном, это больше не тревожило меня, ведь я сделала все, что смогла.

Пластинка с розовым шоссе все еще наполняла комнату сладким шумом, но теперь ее звучание было намного тише. Какое-то время я просто лежала на груди Старлайта, наблюдая как окутанное сном, его тело вздымалось с каждым новым вдохом. На его лице, аккурат над левым уголком губ и кое-где под бородой, виднелись небольшие родинки, и я мысленно удивилась тому, что не замечала этого прежде.

Решив выпить кофе, прежде чем отправляться на утреннее построение, я попыталась осторожно подняться с постели, дабы не разбудить Стара, но стоило мне только сделать это, как он глубоко вздохнул и, простонав что-то, открыл глаза.

– Привет, сладкая, – все еще сонным голосом произнес он.

– Доброе утро, – улыбнулась я. – Я как раз собиралась сварить кофе.

– Погоди, давай полежим еще немного, – попросил Старлайт.

Не будучи в силах отказать, я вернулась в его теплые объятья.

– Знаешь, – говорил Старлайт, медленно проводя рукой по моей спине, – тебе определенно не идет это имя.

Я удивленно подняла брови, спросив: «Почему же? Оно мне всегда нравилось.», но тут же улыбнулась, ведь и так знала ответ.

– Да, согласен, имя красивое. Но, как по мне, ты больше похожа на раннюю зиму, или рождественское утро.

Почувствовав, что краснею, я постаралась скрыть это, и тут же ответила:

– Не забывай, что я не всегда была такой как сейчас. Когда-то это имя действительно было мне к лицу, милый.

– Правда? – заинтересовался Старлайт, и, приподнявшись на локтях, внимательно посмотрел на меня. – А какой ты была?

Я пожала плечами.

– Совсем другой. В чем-то очень похожей на тебя.

– С карими глазами? – догадался Старлайт.

– Да, и к тому же у меня были каштановые волосы с золотым отливом. Так что я очень даже напоминала золотую осень, – я улыбнулась, и добавила: – Ну, и как ты можешь догадаться, я никогда не была настолько бледной.

– Надо же, – протянул Старлайт, – Мне и впрямь сложно представить тебя такой.

Я опустила глаза.

– Но уверен, – продолжил он, – если я когда-нибудь увижу тебя прежней, то непременно влюблюсь еще раз. Бесконечное количество раз.

Все еще краснея, я крепко поцеловала его, и Старлайт ответил тем же.

– Так как насчет кофе? – предложила я.

\*

Старлайт отправился в ИИЛП, а я, заскочив к себе, наспех накинула форму, и как раз вовремя подоспела к построению.

Шеренга солдат выстроилась в огромном холле правого крыла здания штаба. Я неспешно шагала вдоль нее. Честно говоря, мне уже немного наскучило заниматься этим каждое утро. Сириус отлично справлялся с построением в мои выходные, и я уже давно подумывала поручить ему еще парочку дней в конце недели. Конечно, не столь важных как сегодняшний.

Зная Сириуса, я с уверенностью могла сказать, что он вряд ли стал бы отказываться. К тому же, желание дополнительно работать с его стороны в будущем самым что ни на есть положительным образом повлияет на выдвижение его кандидатуры на мой нынешний пост. Обычно старпомы не становились капитанами, а сменялись вместе или через несколько лет после ухода последних, но я всегда считала Сириуса Уайта идеальным приемником. За все годы, проведенные здесь, а также в Космической Академии я все еще не встретила более подходящего для этой должности человека, обладающего теми лидерскими задатками, которые имелись у Сириуса. При всем этом, они никогда не мешали его работе на должности ниже моей, и это являлось еще одним неоспоримым достоинством старпома.

По обыкновению, до мозга костей залегшем в моем сознании, я опросила десант об обстановке. Как и всегда, все мои предыдущие приказы оказались безукоризненно выполненными.

– Теперь о наболевшем. Что с кратерной зоной у тринадцатого? – спросила я, сейчас этот вопрос волновал меня сильней всего. – Кто отвечает за обыск территории?

Светловолосый солдат с невозможно ясными серыми глазами сделал шаг вперед из первого ряда.

– Сержант Фостерс, Капитан.

– Докладывайте, Сержант.

– В прошедшие сутки на протяжении одной четверти указанная зона была подвержена обыску. Задействованы были четверо солдат, включая меня. Следуя Вашим указаниям, мы также прибегли к помощи двух специалистов по бурению лунной поверхности: докторов &lt;хуйзнает&gt; и &lt;нухуйегознает&gt;. В результате исследования, зафиксированные ранее датчиками толчки были подтверждены. Они взяли начало при семидесяти шести метрах под уровнем поверхности, и на протяжении небольшого отрезка времени достигли самой высшей и, казалось бы, невозможной точки – восемнадцати метров _над_ уровнем поверхности. Об этом также свидетельствуют повреждения, оставленные на самой поверхности, которые Джоуэлл Блек, вероятно, и счел за следы бурения. В ходе поисков ни исчезнувший луноход, числящийся под номером одиннадцать, ни сам Джек Метьюз, или какие-либо следы пребывания в указанном участке последнего, не были обнаружены.

Затаив дыхание, я ошарашено смотрела вперед себя, не будучи в состоянии вымолвить и слово.

– Я также передал Вам письменный отчет о вчерашних действиях, – добавил Фостерс. – Он уже на Вашем столе, Капитан.

– Большое спасибо за помощь, Сержант, – наконец ответила я, и, увидев ошарашенный взгляд солдата, тут же скомандовала: – Вольно.

На пути к выходу мне встретился Сириус. Он предложил позавтракать, но в этот раз я отказалась: мне всегда лучше думалось на голодный желудок, а сейчас как никогда важно было трезво мыслить. Тогда старпом в одиночку отправился в столовую, а я вышла на улицу.

Все еще шокированная последними новостями, я шагала в сторону стоянок. Вокруг все было прежним, но мне оно виделось в еще более серых тонах, чем можно бы было представить. В голове мелькнула мысль о том, что если бы здесь мог пойти дождь, он бы сейчас непременно пустился. Нет, не дождь – ливень.

Хоть мне казалось, что корабль двигался невыносимо медленно, на ЭСКМО я прибыла гораздо раньше обычного, и все оставшееся до совета время просто болталась на стоянке, не замечая здешнего холода.

Наконец, я услышала звук приближающихся кораблей, и напряженно вздохнула: пора подниматься в Зал Совета. Не желая сейчас болтать с кем-либо из капитанов, я ускорила шаг и вскоре первой появилась перед сенатором.

Мы обменялись рукопожатиями, и я решила, что правильней будет с глазу на глаз доложить ему об обстановке. Выкладывая все как есть, я старалась смотреть в глаза сенатору, но мой взгляд, то и дело, скользил в сторону собственных ботинок.

Закончив рассказ, я кое-как нашла в себе силы, и взглянула в глаза сенатору Куинну. К моему удивлению, его лицо оставалось все таким же беспристрастным.

– Дезертир, – наконец, заключил он.

Я постаралась как можно лучше скрыть свое удивление.

– Но у Джека Метьюза прекрасная репутация. И это при том, что ему оставался всего год до пенсии, – напомнила я.

– Дезертир, – не сводя с меня глаз, повторил сенатор.

– Но, сер, – не унималась я, – это противоречит фактам. И, к тому же, всем существующим законам физики. Как, по-вашему, ему удалось бежать? На луноходе?

– Послушайте, капитан Раст, я в этом деле намного дольше Вашего, и способен с полуслова раскусить дезертира. Знаю я таких парней. Сначала они показывают себя как истинно прилежных работников, а после бегут при первой же возможности. По окончании совета я сообщу о нем на Землю, и как только Метьюз объявится, а будьте уверены, он объявится, наши люди тут же его перехватят.

– А как же толчки?

– Всего лишь попытка запутать нас и не более. Вы ведь сами сказали, что они, якобы, достигли невозможной высоты. Тут-то Метьюз и прокололся. Уверен, при более детальном расследовании таких несостыковок окажется гораздо больше, чем Вы думали. Проверьте, все ли корабли на месте.

– Уже. Все они на базе, сенатор.

– Что ж, – протянул он, – тогда это могло быть и незарегистрированное судно. Узнайте, не велось ли в последнее время строительство новых кораблей.

– Только одного, сер.

– Подробней?

– Это тестовый корабль для Профессора Рока. Проект возглавляет доктор Штернбренер. Судно будет готово к концу следующей недели.

– Уверенны, что корабль не был готов ранее?

– Да, сенатор, – ответила я, – я проверила его наличие в Институте Исследований Лунной Поверхности.

– Хорошо. Считайте, что Вы передали это дело мне. Теперь можете забыть о нем и вернуться к своим привычным обязанностям, – он ухмыльнулся.

От этой улыбки мне стало как-то не по себе.

– Может, все-таки присядете, капитан Раст?

Я кивнула и молча опустилась в свое кресло. Через минуту дверь отворилась, и зал наполнился приветствующими друг друга капитанами.

Совет начался.

\*

По окончанию всей этой суеты, я была рада вернуться в свою комнату и провести вечер за чтением «Темной Башни». Доносившая из проигрывателя музыка ненавязчиво нарушала привычную тишину этих стен.

К средине вечера в дверь позвонили. Это вряд ли мог быть кто-то из солдат, обычно, они связывались со мной дистанционно. Должно быть, это Старлайт, решила я и, отложив книгу, направилась к двери.

Я не ошиблась, на пороге, спрятав одну руку за спину, стоял Стар.

– Ну, как ты? – спросил он, увидев мой расстроенный вид. – Сенатор плохо воспринял эту новость?

– Вовсе нет, – ответила я.

Старлайт удивленно вскинул брови.

– Но ты подавлена, – произнес он.

– Да, так и есть…

– Прежде, чем ты что-либо скажешь, я хочу подарить тебе это, – он улыбнулся и протянул мне прекрасную алую розу, помещенную под стеклянный колпак.

Этот его жест тронул меня до глубины души, и я все еще не могла поверить своим глазам.

– С ума сойти, Старлайт, – говорила я, не в силах отвести взгляд от красоты цветка. – Я очарована.

Он улыбнулся еще шире.

– Ведь я не видела роз уже больше…

– Десяти лет, знаю, – он взял мою руку и трепетно поцеловал ее.

Поставив цветок на столик рядом с книгами, я отвела Старлайта на кухню, и приготовив кофе, потянулась за бутылкой коньяка.

– Но как тебе удалось ее достать? – спросила я. – Это ведь вечная роза.

– Она со мной с самого детства, – говорил Старлайт, не выпуская моей руки из своей. – Стояла на старом дедовском рояле многие годы, и не раз придавала мне вдохновения. Теперь она твоя.

– Ты играл? – удивилась я.

– Да, в наше время это мало кого интересует, но меня всегда захватывала музыка. Как же мне этого здесь не хватает, – мечтательно произнес он.

– Но почему ты прекратил?

– Я никогда не прекращал, – улыбнулся Старлайт, взяв из моих рук чашку с кофе.

\*

Ближе к ночи я рассказала Старлайту о разговоре с сенатором Куинном. Внимательно меня выслушав, он, к счастью, не испытывал всеобщего спокойствия.

– Тебе ведь тоже кажется это странным, не так ли? – спросила я.

– Абсолютно, – согласился Старлайт.

– Меня это очень беспокоит, и вызывает так много вопросов. Здесь явно то-то происходит. Вот только я никак не могу понять, что, а все вокруг словно не хотят открывать глаза.

– Послушай, милая, я полностью разделяю твое беспокойство, но, боюсь, мы оба здесь бессильны, так что нам не остается ничего, кроме как продолжить свою работу. Просто не забывай об этом.

Его слова успокоили меня, но только на время.