---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Земля {#09}

Уже который вечер подряд я усаживался в садовое плетеное кресло на заднем дворе своего дома в Кентуки, и с наслаждением наблюдал, как над городом сгущались первые сумерки. Радиоприемник, стоящий на веранде еще с самых незапамятных времен, передавал «Где-то за радугой» Томаса Ньюмана. Подобные радиопередачи сейчас были редкостью. Их слушал лишь небольшой процент земного населения, и, большей частью, это были такие же старики как я, всю жизнь скучающие по былым временам.

В моей руке покоился стакан бренди. Кубики льда в нем медленно покачивались в такт музыке.

Как же чертовски хорошо было, наконец, вернуться домой спустя все эти годы. Столь многое я потерял, находясь вдали отсюда, но сейчас для размышлений были вещи и поважней моего спокойствия…

И все же, насколько приятным было для меня находиться в этом загородном уединении. Стоило мне лишь сойти с трапа космического корабля, и я тут же почувствовал себя прибывшим на чью-то чужую планету. Вокруг все было столь мобилизированно… Для каждого ребенка в порядке вещей было иметь хотя бы одну галаграфическую модель солнечной системы, а от владелицы космической лавки напротив своего дома я узнал, что воздушные галактики в последнее время стали просто нарасхват.

Поразительно было наблюдать, как люди тянутся ко всему космическому, забывая при этом об истинно земных вещах. Откровенно говоря, я и сам когда-то стремился стать таким. На то были свои причины, но я все же никогда не прекращал ценить красОты простых вещей. А тогда, шагая по улицам, насквозь пропитанным искусственностью, я думал лишь о том, что наличие хотя бы одного деревца на целый квартал для этого мира – уже неплохо.

Человечество вымирало. Оно стремительно катилось к гибели, не замечая этого и с радостью падая в темную пропасть. Нет, численность населения оставалась прежней. Исчезали их души.

Каждое здание, что встречалось на моем пути, каждый диалог – все это отдавало невыносимой сухостью, но, войдя в свой сад через старую, скрипящую (точно как и раньше) калитку, я почувствовал облегчение – вот теперь я был дома.

У меня все еще оставалось одно незавершенное дело на Земле. Все те долгие годы вблизи Луны я ни на минуту не забывал об этом, но вот я здесь, и прошло уже более двух месяцев, а я все никак не мог найти в себе сил, дабы завершить начатое.

Конечно, я осознавал, что времени у меня оставалось не так уж и много. Было бы безумием это отрицать. Но пока я здесь и пока я жив, для меня существовали всего лишь две задачи, которые нужно было решить.

Опустошив стакан, я еще разок обвел взглядом улицу: на ней стало заметно темней, а кое-где уже загорались первые фонари.

Поднявшись, я направился к дому.

Сухие поленья тихо потрескивали в камине при соприкосновении с пламенем. Перекусив несколькими сырными тостами, я принес из дальней комнаты стопку фотоальбомов и, умостившись у огня, принялся рассматривать снимки. Сменяясь один за другим, они напоминали мне о годах, прожитых на Земле – самом счастливом времени в моей жизни. Вот я держу на руках Роуз, а Лили радостно размахивает бенгальскими огнями. А здесь уже Роуз постарше и вместе с сестрой помогает маме срезать головки одуванчиков для моего фирменного вина.

– Моя дорогая Амелия, – произнес я, осторожно проводя рукой по снимку жены, – как же сильно мне тебя не хватает.

Я взглянул на следующий снимок, и невольно улыбнулся. На нем семилетняя Роуз пыталась взять на руки Хенка, нашего пса. Мне отлично помнилось то утро. Мы с женой получили долгожданный отпуск и в первый же его день всей семьей отправились к морю. Путь был не близким, ведь уже тогда нетронутую корпорациями природу найти было крайне сложно, но оно того стоило, ведь уже спустя три дня мои девочки радостно плескались в пене серебристых волн.

Вместе с этими воспоминаниями пришли и другие. Те, что на протяжении многих десятилетий я старался запереть в самом дальнем уголке своего сознания, и вот теперь они вырвались наружу, заставляя мое сердце биться в тысячи раз быстрее. В голове мгновенно всплыли картины, навеки оставленные в моей памяти тем утром. Я видел обломки своего бьюика, разлетевшиеся по трассе. Рядом лежали тела моих девочек, в которых еще секунду назад теплилась жизнь. Столкновение отбросило их на несколько метров от машины, но это уже не имело значения.

Тошнотворный ком подступил к горлу, стало сложно дышать, и на мгновенье мне показалось, что все закончится в эту самую минуту. Но я прокашлялся и, поднявшись на ноги, потянулся за шляпой и пальто.

Нужно было действовать, и прямо сейчас.

\*

Бредя по унылому холлу Госпиталя Падших Ангелов, я подловил себя на том, что с каждой секундой все заметней замедляю шаг. Это место всегда вызывало в моей душе невыносимую дрожь и на протяжении многих лет являлось мне в кошмарах.

Мы все от чего-то бежим. Все время на м83 я скрывался от собственной боли. Теперь же наступило самое время взглянуть страхам в лицо.

Я подошел к стойке регистрации, за которой сидела девушка с бейджем, на котором виднелось ее имя: «Джинни».

– Могу я видеть пациентку из 113-й палаты? – как можно уверенней произнес я.

– Ваше имя? – спросила девушка, по-прежнему не отрываясь от компьютера.

– Джуд Корнуэлл.

Услышав мое имя, Джинни машинально поправила очки и ошарашено уставилась на меня своими зелеными глазами. Другой бы счел этот жест неприемлемым, даже оскорбительным, но я ее за это не винил.

– Присядьте, мистер Корнуэлл, – сказала она, взяв себя в руки. – Я пошлю за доктором Бёртоном.

– Стивеном Бертоном? – уточнил я.

Девушка посмотрела на меня с еще большим удивлением.

– Доктор Стивен Бертон отошел на покой двадцать лет назад, сер. Теперь Вашим делом занимается его сын, Орландо.

– Благодарю, – ответил я, и присел на белоснежный диван, стоящий около восточной стены.

Несмотря на позднее время, доктор появился гораздо быстрее, чем я предполагал. Он был высок, подтянут и выглядел лет на сорок, хотя в его каштановых кудрях уже виднелись первые проблески седины.

– Доброй ночи, мистер Корнуэлл, – он протянул мне руку.

Я облегченно вздохнул, заметив, что доктора вовсе не ошеломило мое появление. Он вел себя так естественно, словно я наведывался в госпиталь каждые выходные.

– Отец говорил мне о Вашем деле. Давайте пройдем в мой кабинет.

– Хорошо, – ответил я, – Но для начала можно мне к ней?

– Конечно. Вас провести?

Я горько улыбнулся.

– Не стоит, доктор, я все еще помню дорогу.

И поднявшись, я на ватных ногах зашагал навстречу самому жуткому из своих кошмаров.

\*

Глубоко вздохнув, я вошел в палату.

Роуз неподвижно лежала на белоснежных простынях около прикрытого окна. Она выглядела такой же спокойной и красивой, какой я оставил ее здесь семь десятилетий назад.

Стараясь подавить слезы, я сжал ее хрупкую руку в своей ладони.

«Мы все от чего-то бежим», – неустанно повторял голос в голове, и словно стараясь перекричать его, я произнес сквозь слезы:

– Я вернулся, дорогая.

… и не узнал звук собственного голоса.

Столь многое мне хотелось сказать ей, но я больше не смог вымолвить и слова, так что я устало опустился в одно из кресел и, не выпуская руки Роуз, в тишине слушал ее еле уловимое дыхание.

Несмотря на свой преклонный возраст, я еще никогда в жизни не чувствовал себя настолько старым и беспомощным как в этот самый момент. Прежние деньки остались далеко позади, где-то за радугой и ясным небом. Пора было взглянуть реальности в лицо.

Напоследок поцеловав дремлющую Роуз, я провел рукой по ее седым волосам.

– Я найду тебя где-то за радугой, дорогая. В стране с ясного неба и сбывшихся надежд.

\*

– Вы уверенны в своем решении? – спросил доктор Бёртон.

Я кивнул.

– Что ж, если хотите знать мое мнение, Вы не ошибаетесь. Деньг, что Вы высылали на протяжении последних лет, хватило бы на строительство еще одного госпиталя, – продолжал он, – но, к сожалению, в случае Вашей дочери мы бессильны.

– И я готов отдать все до последнего, если бы это только могло помочь ей проснуться, – сказал я, стараясь не поднимать покрасневшие от слез глаза.

Доктор Бертон ничего мне не ответил. Он лишь поднялся со своего кресла и, подойдя ко мне, понимающе положил руку на мое плечо.

– Тогда пройдемте в палату, – наконец произнес он.

Я вновь кивнул и мы зашагали по ярко освещенному коридору.