---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Сон {#10}

Я по-прежнему стояла около круглого окна своей комнаты, круглосуточно передающего заманчивые земные огни. Не помню, как долго я пробыла здесь, возможно, всего час, или целые сутки... Я уже давно потеряла счет времени. Картина перед моими глазами была столь чарующе прекрасна, что я готова была не сводить с нее глаз веками.

Откуда-то издалека непрестанно доносилась безмолвная космическая музыка. Она касалась моей души, словно ледяная капля в жаркую летнюю ночь, наполненная приятным током, и пронизывала каждый сантиметр пространства вокруг. Казалось, музыка была внутри меня самой. Было странно и не совсем понятно, как такое могло происходить, но мне не было никакого дела до этих пустых вопросов. Единственным моим желанием сейчас было находиться на этом самом месте, вглядываясь в бесконечную темноту звезд, среди которой невидимо вращалась моя родная планета. И каждый раз это зрелище заставляло сердце на миг замирать, а после – стучать пуще прежнего.

В голове пронеслась еле различимая мысль о Розе Роланда. Это определенно могла быть она, ведь время способно преобразить все до неузнаваемости, так почему бы и нет?

Внезапно я заметила новые огоньки, появившиеся на самой поверхности Земли. Несоразмеримые с предыдущими, невероятных размеров вспышки света продолжали мелькать и разрастаться сплошь и рядом. Но мне совсем не нравился этот свет: он был чужим, холодным, и вызывал необъяснимое отчаянье в моей душе. И, все же, что я могла поделать, будучи здесь, за тысячи километров от Земли?

А вспышки тем временем продолжались. Они затмевали все вокруг себя с такой скоростью, что теперь неохваченные ими участки преdращались в редкие пятна, безвозвратно исчезающие с каждой секундой. И тогда я поняла, что это были взрывы, поглощающие все на своем пути.

От собственной беспомощности становилось сложно дышать, а сердце раз за разом разбивалось на части, но, словно парализованная я, затаив дыхание, продолжала стоять у окна с широко раскрытыми глазами.

Мелодия космоса также утратила свою красоту, она беспощадно гудела, пронзая своими ядовитыми иглами даже воздух, в то время как с полотна Земли пропало последнее нетронутое вспышками пятно. Вскоре и сама Земля обратилась сплошным огненным шаром, на миг зависла в воздухе, а после осветила своим пламенем все вокруг, и навсегда исчезла в темноте ночи.

Внезапно я услышала чей-то пронзительный, преисполненный болью крик. Он звучал совсем близко, но, оглянувшись по сторонам, я с удивлением отметила, что рядом никого нет. Крик продолжал звучать. Сквозь него я услышала встревоженный голос Старлайта. Он непрестанно повторял мое имя. Мгновеньем спустя я почувствовала, как кто-то коснулся моего плеча, открыла глаза, и поняла, что это кричу я сама.

– Отем, дорогая, очнись, – говорил Старлайт, и, увидев, что я проснулась, прижал меня к себе.

Немного отдышавшись, я обняла его в ответ, и вскоре почувствовала, что теплые руки Стара гладят мои волосы.

– Ты в порядке? – тихо спросил он.

Я изо всех сил постаралась улыбнуться.

– Да, в полном, как и всегда. Всего лишь дурной сон.

\*

– Проходи, – улыбаясь, произнес Штернбренер, и исчез в дверном проеме.

Последовав за ним, я оказался в просторном купольном зале верхнего яруса института. Несмотря на его внушительные масштабы, здесь было практически пусто. Лишь в самом центре меня ждал новенький блестящий звездолет. Он был небольшой, по сравнению с теми, что я видел прежде.

– А вот и он, – ликующе произнес Штернбренер, и перекатывая догоравшую сигарету из одного уголка рта в другой. – Моя последняя модель. В своей компактности он не уступает автомобилю класса J, хотя начинка та же, что и в военных кораблях.

– Потрясающая работа! – воскликнул я, осматривая блестящий корпус судна.

Штернбренер шутливо поклонился.

– Постой, с советом точно не возникло проблем?

– Можешь даже не беспокоиться на этот счет, – отмахнулся он. – Они всего-то настояли на стандартных мерах безопасности, как я и думал.

– Каких же?

– Вместе с твоими картами я снабдил систему контактами всех сотрудников базы и проверил, работает ли связь.

Я согласно кивнул.

– А теперь взгляни-ка на это, – Штернбренер указал мне на надпись, выгравированную на передней панели корабля.

– РокCтар, – прочитал я, и широко улыбнулся. – Ну, ничего себе, не знаю, что и сказать. Спасибо, Август, – я горячо пожал ему руку.

Штернбренер облокотился на корпус корабля и закурил очередную сигарету.

– Не можешь дождаться полета? – подмигнул он.

\*

Прислонившись к окну, Отем заворожено смотрела на сияющую вдали Землю.

– Уже совсем скоро ты будешь там, – тихо произнесла она и улыбнулась.

Подойдя ближе, я увидел в стекле отражение ее прекрасных глаз. Но, все же, я не мог не заметить скрывающейся за всем этим печали. Со мной Отем действительно стала более чувствительной, а значит, прятать эмоции для нее теперь также было трудней. Хотя тень печали в ее глазах была так заметна, я подумал, что, должно быть, девушка еще сама не догадывается, насколько это очевидно.

Все так же, не оборачиваясь, Отем впитывала взглядом земные огни, когда я обнял ее за талию и коснулся губами фарфорового плеча. Тогда она вновь улыбнулась и, обняв меня за шею, нежно поцеловала.

– Ты тоскуешь по дому? – спросил я.

Она вздохнула и немного повременила с ответом.

– Скорей всего, я должна ответить «да». Но правда в том, что на самом деле у меня просто нет на Земле ничего, по чему я могла бы тосковать, Старлайт.

Я не знал, что и сказать.

– Знаешь, – продолжала Отем, – когда я только прибыла на м83 и впервые встретилась с Корнуэллом, главным инженером этого места, он спросил, от чего я бежала. Ведь, по его мнению, все, кто решает провести здесь хотя бы десятилетие, напросто скрываются от чего-либо. А я ответила, что это не так, и солгала, – она печально улыбнулась, – тогда мне еще под силу было сделать это.

– Значит, тебе что-то мешает вернуться?

Отем задумчиво кивнула.

– Долгое время мне было сложно осознать это. Ты первый кому я призналась.

– Но прошло так много времени, – произнес я, – Разве это не должно было хоть что-то изменить?

– Не знаю. Года прошли на Земле, а здесь время для меня словно замерло, и я понятия не имею, что ждет меня за пределами базы. Но, скорей всего, мне просто не к чему возвращаться.

К сожалению, для меня время не стояло на месте, и я знал, что скоро должен буду покинуть ее, пускай и ненадолго. Но сейчас мне было невероятно сложно выпустить любимую из своих объятий, так же, как и поверить в то, что такой волшебный человек как Отем действительно может быть столь одинок.

Все же, я всем сердцем чувствовал это.

– Уже назначен день для полета? – словно прочитав мои мысли, спросила она.

– Двадцать девятое января.

– Так у тебя есть еще несколько недель, – улыбнулась Отем. – Волнуешься?

– Несомненно. Чертовски волнуюсь, если честно. Я ведь никогда прежде самостоятельно не летал. Но я также очень жду этого момента, так что все это время проведу в тренировках.