---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Листья Травы {#11}

Страницы «Листьев Травы» приятно шуршали под моими руками, когда я переворачивала их одну за одной. Темно зеленый томик был прочитан ровно наполовину. Теперь, что бы не случилось, я всегда возвращалась к чтению. Меня это успокаивало, унося мысли далеко-далеко, тем самым приводя содержимое головы в порядок.

Мне нравилось то, о чем писал Уитмен, хотя многие из этих строк были мне не совсем понятны. Казалось, без предыстории здесь не обойтись. Постепенно, тщательно вчитываясь в каждое слово, я приблизилась к поеме с кричащим названием: «О, капитан мой, капитан», но прежде чем я успела прочесть ее, кое-что привлекло мое внимание. Нет, это было даже не само название. Внизу на полях, сразу под текстом, я увидела несколько строк написанных мелким слегка закругленным почерком, в котором тут же узнала руку Корнуэлла.

_О, Капитан мой, Капитан,_

_Столь многое мне хочется сказать тебе, но это рискует поставить под угрозу не только твою карьеру, но и жизнь, а посему я готов попридержать коней, но лишь на время._

_Вспомнив об этом стихотворении перед тем, как отдать тебе книги, я не смог удержаться. На этой странице ты найдешь номер, соответствующей ячейке камеры хранения, что находится в туристическом космодроме. Там тебя ждет еще одно и, на этот раз, действительно последнее письмо. Пароль для доступа к нему также спрятан на этой странице. Для того, чтоб узнать его, тебе достаточно лишь вспомнить тайну золотого жука. Но я настоятельно прошу тебя не делать этого вплоть до последнего момента, потому что только так ты сможешь уберечь себя. Поверь мне, дорогая, когда настанет время, ты поймешь меня так же хорошо, как понимала и множество раз до этого._

На этом запись обрывалась. Я прочла ее дважды, дабы убедиться, что ничего не упустила, а после в замешательстве села на кровати. Еще недавнее желание на протяжении всего вечера наслаждаться поэзией как рукой сняло. Хотелось бросить все и поскорей отправиться на космодром. Но я твердо решила прислушаться к Корнуэллу и в этот раз: прежде он никогда не подводил меня.

Так я и просидела весь остаток вечера, размышляя над запиской и думая, стоит ли мне выходить из комнаты, пока, в конце концов, не уснула, забыв погасить свет.