---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Полет {#12}

Всю прошлую ночь я долгое время не мог уснуть из-за возбуждения, нахлынувшего на меня в канун предстоящего полета. Отем мирно спала рядом, положив руку на моей груди, тогда как я просто наслаждался ее присутствием и предвкушал наступающий день.

Несколько лишенных сна часов казалось мне до невозможности затянувшейся вечностью и проведя таким образом еще какое-то время, я вынужден был признаться самому себе в том, что уже вряд ли смогу уснуть этой ночью: слишком уж я переволновался. Теперь нужно было успокоить нервы и постараться отвлечься.

Лучше всего меня удавалось отвлечь Отем, но так как она уже давно спала, я обратил свое внимание к другим вещам, не раз спасавшим меня в подобных ситуациях. Обычно, это была работа над звездными картами, и, конечно, музыка.

Стараясь не потревожить Отем, я бережно убрал ее руку, и окончательно встал с постели.

За окном стояла умиротворяющая картина, и, глядя на россыпи звезд, я думал о том, что уже спустя несколько часов окажусь среди них.

Усевшись как можно дальше от кровати, я запустил свой браслет. После нескольких секунд загрузки в пространстве передо мной возник невидимый экран, на котором с невероятной правдоподобностью отображался мой проект: сияющие трассы, тянущиеся от Земли к Луне и обратно, зависли среди тысячи звезд. Предполагалось, что их ширина достигнет около 80-ти метров, но ввиду того, что (благодаря моим картам) путь к Луне, прежде длившийся 83 минуты, теперь должен был стать заметно короче, что уже никак не вязалось с названием компании, я решил добавить к ранее запланированной ширине дороги еще несколько метров. Таким образом 83 минуты превратились в 83 метра.

Края моих дорог в космическом пространстве определялись бесконечным количеством голубых огней размером с телефонную будку, установленных через каждые 5 метров. Увидев их однажды на моем макете, Отем сказала, что они напомнили ей сверчков из какого-то старого мультфильма. С той поры дорожные огоньки стали зваться сверчками.

Я разглядывал план дорог и с замершим сердцем осознавал, что теперь это нечто большее, чем просто мечта. Если сегодня все пройдет гладко, уже с началом третей четверти начнется строительство.

Эти мысли немного успокаивали, и вскоре я перешел ко второй части своего проекта. Той, которую еще предстояло доработать – отрезок маршрута и частичка звездного неба, берущие место непосредственно за той частью Луны, которую было принято называть светлой.

Вот передо мной предстала совсем иная, веющая холодом картина темной половины. В этот момент я подумал о несчастном Метьюзе, с которым никогда прежде-то и не был знаком, и искренне пожелал тому (вопреки здравому смыслу) оказаться дезертиром. Ведь иначе…сложно было представить его дальнейшую участь.

Свет от голографической проекции моего браслета падал на постель, и я заметил что Отем пошевелилась. Тогда я уменьшил изображение до минимально приемлемого для работы с ним, но это не особо помогло, а потому мне пришлось на время свернуть работу. Немного подумав, я решил переместиться в комнату отдыха, а после, возможно, немного пройтись.

Одевшись, я взял пальто и направился к выходу, но на половине пути остановился и взглянул на сладко дремлющую Отем. Мне вдруг захотелось оставить ей записку. Удивительно… В смысле, ну кто теперь занимается подобными вещами, когда различные устройства моментальной связи всегда при тебе? Но я лишь отмахнулся от этих так себе аргументов.

Ручка для &lt;сенсорного?&gt; стола у меня была. Она отлично подходила и для бумаги. Единственной сложностью оказалось найти хоть какой-нибудь лист. Этой ночью мы остались в моей комнате, и я вообще не был уверен, что где-то здесь может быть что-то подходящее. Пришлось перерыть все свои вещи, но в итоге я кое-что нашел. Передо мной лежали два снимка. Один из них – мое первое фото луны – был со мной с тринадцати лет; я сделал его, будучи совсем ребенком, так что изображение было немного нечетким. Другой, прибывший вместе со мной из Страны Садов – той части Парижа, что по-прежнему сохраняла свой цветущий вид. Мне довелось побывать там чуть менее года назад – деловая поездка, темы которой я уже совсем не помнил, зато восхищение от увиденных в тот день красот надолго поселилось в моей памяти.

Поколебавшись немного и сравнив обе фотографии, я, все же, выбрал вторую, и, перевернув ее, написал на обратной стороне:

_Всю ночь не мог уснуть из-за предстоящего полета,_

_решил немного поработать._

_Буду в комнате для отдыха,_

_а позже, возможно, прогуляюсь в городок._

_Я уже давно поглядываю на тот кинотеатр._

_Стар_

Я отложил ручку и перечитал записку. Уже собирался опустить фото на одну из подушек около головы Отем, но тут же взял ручку обратно, и чуть выше своего имени дописал: «Люблю тебя».

Затем я положил карточку куда и собирался, и вышел из комнаты.

\*

Новый день встретил меня запиской Старлайта. До полета оставалась всего четверть, но, несмотря на повисшее в воздухе волнение, я чувствовала себя абсолютно спокойно. Должно быть, таким образом на мне сказывался длительный и здоровый сон.

Выйдя из душа, я отложила завтрак и распитие кофе на террасе (ставшие уже традиционными в выходные дни), и отправилась на поиски Старлайта. Его записка навеяла на меня некое чувство ностальгии. И хотя я никогда не жила во времена, лишенные технологического обилия, мне вдруг показалась совершенно неправильной мысль просто позвонить Стару. Хотелось прогуляться по солнечным аллеям городка, и, немного замерзнув, найти его сидящим в небольшом кинозале.

Но я застала его спящим в зале отдыха. Вокруг не было ни души. Только полуметровая проекция Луны вращалась под потолком в самом центре помещения. Старлайт же дремал за столом, уронив голову на руки.

Я осторожно коснулась его плеча, и Старлайт тут же преподнял голову.

– Который час? – с затуманенным взглядом спросил он. – Я все пропустил?

Я не могла не улыбнуться.

– Еще практически четверть до полета.

Старлайт пробурчал что-то невнятное. Мне показалось, что сейчас он снова отключится, но нет, за этим последовала попытка встать на ноги.

– Тебе нужно привести себя в порядок, милый, – произнесла я. – Скоро здесь появятся остальные.

Под остальными я подразумевала своих ребят, возвращавшихся с очередных утренних поисков. Сейчас Сириус не позволял им расслабиться даже в выходные дни, а я не была против. Несмотря на свою точку зрения в вопросе о пропаже Метьюза, сенатор Куинн, все же, не велел закрыть это дело прямым текстом. Так что поиски по-прежнему велись. Они продвинулись далеко за пределы тринадцатого пункта, и теперь, насколько мне было известно, было прочесано около 10 % поверхности темной половины.

Старлайт, казалось, понял мои слова. Кивнув, он медленно побрел в сторону своей комнаты. Вращающаяся проекция Луны поплыла вслед за ним, и, заметив эту картину, я рассмеялась. Может быть, хоть приняв душ Стар заметит ее присутствие.

\*  
Когда после завтрака я вернулась в комнату, Старлайт уже вышел из душа и выглядел более бодрым, чем прежде. Казалось, былое воодушевление перед работой вновь вернулось к нему. Стоя перед зеркальной стеной и что-то весело напевая (мне показалось, это была «Потому что мы можем»), Старлайт застегивал пуговицы на своей клетчатой рубашке.

– С добрым утром, - на его лице засияла очаровательная улыбка. – Я ведь так толком и не поговорил с тобой.

Я улыбнулась, и опустилась в уже успевшее полюбиться мне кресло, стоящее у входа в его комнату.

– Приятно вновь видеть тебя в хорошем расположении духа, – начала я, – но сейчас мне нужно поговорить с тобой как твоему капитану, а не возлюбленной.

Он взглянул на меня слегка удивленно, но тут же улыбнулся.

– Иногда я совсем забываю о том, что ты к тому же еще и мой капитан, – произнес он, усевшись рядом со мной. – Хорошо, я внимательно тебя слушаю.

– Что ж, тебе лучше меня известно, что сегодняшний полет должен стать лишь проверочным, а значит никакого афиширования не предвидится. Ты ведь знаешь все эту секьюрность.

– Конечно, – кивнул Старлайт. – Я это понимаю. Да и сама работа готова лишь на 2/3.

– Именно. Потому не мне хочется чересчур забегать наперед, но, если все и впрямь пройдет удачно, (а я не сомневаюсь, что так и будет) мы вынуждены будем открыто объявить о последних исследованиях. Скорей всего, во время следующего полного полета ты уже станешь всемирно известной личностью. Бесконечные интервью, вопросы и копание в твоей личной жизни — вот что последует далее. Отталкивающая сторона славы. И ты должен быть готов ко всему этому.

Он взял мою руку и поднес ее к своим губам.

– Ничто из этого не способно навредить мне пока мы вместе, – произнес Старлайт.

– Замечательно, – ответила я и застегнула последнюю пуговицу на его рубашке. - Тогда пойдем. Самое время становиться известным.

\*  

Должно быть, это и есть одно из тех прекраснейших мгновений жизни, когда понимаешь, что твоя давняя мечта наконец стала реальностью. Но вместо наступления ожидаемого опустошения чувствуешь, как твое сознание заполняется лишь новыми целями и стремлениями, число которых сводится к вечности.

&nbsp;В абсолютном одиночестве я мчался сквозь космическое пространство, со всех сторон облаченное в звезды, и чувствовал себя как никогда замечательно, а вместе с тем и волнительно. Эмоции, нахлынувшие на меня в этот самый момент, были сравнимы с первым поцелуем Отем, когда просто смотришь на человека, и чувствуешь, что — это твоя судьба. Это мгновенье напомнило мне и о том дне, в который я впервые услышал запись со своей первой рапсодией. Волшебно.

Как и тогда, сейчас я знал, что мне все удастся, но все равно немного пережевал ввиду важности задуманного.

Несмотря на намерения компании скрыть этот полет, (вплоть до того момента, когда он покажет положительные результаты) весь ИИЛП сошелся пожелать мне удачи. Несколько сотен человек собрались на двухкилометровом космодроме. Он был гораздо меньше туристического, поэтому пришедшим приходилось буквально тесниться. Затаив дыхание, они стояли среди стальной пустоши.

Большинство военных также накрыла волна всеобщего интереса. Обступив окна своих комнат, они удивленно глазели в мою сторону, пытаясь разобраться в происходящем. Вместе со старпомом Отем наблюдала за взлетом, выйдя на террасу своего кабинета. Взглянув на Отем, я подумал о том, что никогда прежде не видел ее столь серьезной. В тот момент, когда «РокСтар» вспарил над землей, я смотрел на свою любимую, но видел лишь руководителя этого места. Вместе с этой сосредоточенностью Отем выглядела гораздо старше своих лет. Нет, не так: внешне она сейчас практически соответствовала своему настоящему возрасту.

Я вздохнул и закрыл глаза лишь на мгновенье, а после — корабль взлетел, незаметно набирая скорость. Пронесясь над зданием штаба, он плавно преодолел расстояние между космодромом и тем местом, где заканчивалась база. Секунду спустя судно вышело в открытый космос и достнгнув скорости света помчался прямиком по курсу. М83 скрылась за моей спиной, но я отлично знал, как ее отыскать.

— Задать новый маршрут? — предложил лишенный эмоций голос корабля, который так походил на голоса людей, подолгу дышащих синим кислородом.

Я согласился.

Контрольная панель «РокСтара» представляла собой тонкую сенсорную поверхность и внешне напоминала так популярные на базе столы, по модели которых она, собственно, и была выполнена. Удивившись собственному спокойствию, я потянулся к музыке. Штернбренер все предусмотрел. Я запустил «Натупление эры» и, выставив максимальную громкость, вернулся взглядом к картам. Сейчас они занимали практически половину панели, разместившись в самом ее центре. Как и задумывалось, они были единственным, с помощью чего я выстраивал свой маршрут на Землю. Заблаговременно развернув и увеличив нужный отрезок пути, теперь я просто внимательно наблюдал за ловцом звезд, периодически сравнивая его данные с показателями на карте.

Перед глазами все еще стоял образ Отем. Не той, какой я видел ее перед взлетом, другой – взволнованной и влюбленной, какой она провожала меня в путь. Эта картина оставалась со мной на протяжении всего полета, отвлекая от переживаний, и лишь позже, увидев ее снова, я смог действительно осознать то, что мне, наконец, удалось сделать. Теперь происходящее со мной было вполне реально.

Пока все складывалось удачней некуда. Сквозь космическое пространство я летел в направлении Земли, слушая любимые мелодии. Вскоре заиграла «Простая Песня» группы the Shins и на ум непроизвольно пришли мысли об обветшалой усадьбе, расположенной в долине снежных холмов – семейное гнездышко, где проходили мои самые счастливые годы на Земле. Жаль, отца теперь нет рядом, он был бы рад увидев то, чем я сейчас занимаюсь, ведь, не смотря ни на что, отец всегда верил в меня и, как мог, поддерживал это порой фанатичное увлечение звездами.

Я вздохнул. Не хотелось отталкивать от себя подобные воспоминания, но нужно было обратить все мысли к работе и сосредоточиться на том, дабы звездный поисковик отображал верные ориентиры. К счастью, так и было: точки, обозначающие звезды, расположенные в радиусе ста тысяч километров, по мере движения РокСтара продолжали проступать в окошке, находящемся в верхнем левом углу экрана и в точности соответствовали изображению на карте.

И все же я не мог не думать о, казалось, посторонних вещах. Со мной подобное случалось всю жизнь, на самом деле. Стоило мне остаться наедине с самим собой, и поток разнообразных мыслей тут же уносил меня. Они сменялись одна за другой, что частенько мешало уснуть.

Я перевел взгляд на свою левую руку. Хоть я и покинул базу, браслет по-прежнему был на ней. Я догадывался, почему Отем решила отступить от издавна действующих на м83 правил и ни слова не промолвила о браслете, когда, перед самым полетом, я выходил из ее кабинета.

– Удачи, дорогой мой, – сказала она, и взглянула на мою руку, а, убедившись, что браслет все еще там, добавила: – И, пожалуйста, будь осторожен.

После чего Отем обняла меня и крепко поцеловала. Только выходя из здания штаба навстречу пришедшим поддержать меня коллегам, я понял, что браслет до сих пор сомкнут вокруг моего запястья.

Помимо множества других разнообразных функций, такие гаджеты имели еще одну особенность – они непрерывно измеряли пульс и работали лишь будучи надетыми на запястья своих владельцев. В случае смерти человека, носившего его, браслет сразу же отключался. Так было и при его снятии. Сделано это было ввиду соблюдения мер безопасности, ведь этот браслет изготовлялся индивидуально, так что после отключения никто другой не мог запустить его, кроме как сам владелец. Теперь Отем не смогла бы проследить за моим передвижением, так как я находился далеко вне м83, но, пока браслет был на моей руке, она хотя бы знала, что я в порядке.

Честно говоря, осознание этого меня неплохо успокаивало, и даже придавало сил. Казалось, все дорогу – эти неполные триста восемьдесят пять с половиной тысяч километров – Отем была рядом со мной. Стоило лишь обратить мысли к ее образу, и любые тревоги уносились прочь из моего сердца. Что бы там ни было, все страхи вмиг исчезли, когда я в очередной раз взглянул в окно иллюминатора, и осознал, насколько близка в эту минуту ко мне была Земля. Черт возьми, мне и впрямь удалось сделать это!

\*

Стоя посреди своего кабинета, я не сводила глаз с центральной стены-монитора. На ней отображались сигналы, передаваемые браслетами всех нынешних сотрудников м83. Сейчас меня интересовал только один из них.

– Все в порядке? – позади меня произнес Сириус.

– Да, я вижу его.

– Может, хотя бы присядешь ненадолго? – спросил он. – Я принес ужин, ты же снова пропустила его.

Я обернулся.

– Правда? А я и не заметила, что ты выходил, – вновь повернувшись к монитору, сказала я.

– Меня не было больше часа, Отем.

Я не ответила. Сириуса не было здесь больше часа, а до этого мы примерно столько же обсуждали результаты утреннего построения, которое сегодня проводил старпом. Точнее, говорил все время он, а я только изредка и односкладно отвечала. Но это было неважно.

Больше часа…значит, Старлайт уже облетел Землю и вот-вот должен был вернуться.

Стоило мне подумать об этом, и вскоре раздался протяжный сигнал со стороны монитора. Сириус, кажется, даже подпрыгнул от неожиданности.

– Что это? – спросил он.

Сейчас старпом выглядел как-то забавно и даже по-детски обиженным.

Я улыбнулась.

– Он вернулся.