---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Циановый Лес {#13}

Удивительный это оттенок – такая тонкая грань между синевой и зеленью, практически неощутимая. Его мало где можно встретить. Раньше я видел циан лишь на побережье Черного моря, когда теплые лучи вечернего солнца озаряли голубые волны, предавая им легкий зеленый окрас. Теперь же мне несказанно посчастливилось побывать в лесу, название которого говорило само за себя.

Это было волшебное место, как и все в этом лунном мире. Тонкие стволы елей тянулись высоко к небу и словно сближались у самого его начала, сухие ветви шуршали под нашими ногами, а вокруг царила чарующая атмосфера предзакатного покоя. На самом деле, здесь были далеко не одни лишь ели, но названия других деревьев я попросту не знал, и, признаться, сомневался, что подобные виды в принципе существуют на Земле. Нас окружало множество диковинных растений вычурного вида. Стоит ли говорить, что все они переливались всевозможными оттенками синего и зеленого цветов.

Я с интересом разглядывал странного вида куст, очень напомнивший мне очертания силуэта бабочки.

– Это – крыло мотылька, – произнесла Отем, проследив за моим взглядом.

– Красиво.

– Ну, тут уже как сказать, – тихо ответила она.

Я удивился такому ответу, и спросил, знает ли она, как называется то голое ветвистое дерево позади нас, напоминающее человеческий позвоночник.

Отем пожала плечами.

– Мне известно название только одного растения, – ответила она, – вернее сказать, запомнила я лишь его.

– Потому что оно походит на мотылька?

Она кивнула.

– Гигантского холодного мотылька. Поразительное сходство. Каждый раз охватывает дрожь при виде этого дурацкого куста, – она обхватила себя руками. – Я до жути боюсь бабочек.

Мне пришлось приложить немало усилий, чтоб не рассмеяться, услышав это.

– Что, серьезно?

– Да.

– Ну, надо же…,а я и не знал: великий капитан м83 страшится бабочек. В такое практически невозможно поверить, – улыбнулся я.

– Они правда пугают меня, – едва ли не жалобно произнесла Отем. – Пойдем уже дальше, милый.

Я обнял ее, и мы зашагали по пологому склону.

– Значит, бабочки, – сказал я, все еще улыбаясь этой мысли. – Какие еще жуткие вещи внушают тебе страх?

– Клоуны, – с невероятной серьезностью ответила Отем, – но, к счастью, на Луне их нет.

– Не считая сенатора Куинна, – добавил я, и мы рассмеялись.

\*

Отем отвела меня на тихую прохладную полянку, откуда с легкостью можно было увидеть, как за склоном неспешно садится солнце.

– Умиротворяет, не так ли? – спросила она.

Я согласился.

– Знаешь, сейчас мне и впрямь начинает казаться, что я заметно погорячилась на счет событий на темной стороне, – начала Отем. – Времени прошло уже прилично, а вокруг по-прежнему тихо. Я начинаю сомневаться в правильности своих мыслей.

– Ты ведь ни на минуту не прекращаешь думать об этом, правда?

– Нет, не прекращаю. Я все еще ищу зацепки и постоянно нахожусь в ожидании того момента, когда ситуация прояснится. Мне казалось, это правильно.

– А теперь? – спросил я.

– Думаю, теперь для меня самое время прекратить нагнетать обстановку, – она взяла меня за руку. – Среди такой красоты нет места смерти.

– Должно быть, ты права, потому что я чувствую себя так же. Хочешь поговорить о чем-нибудь другом? – предложил я.

– Да, расскажи мне о своих планах на Земле. Чем ты будешь заниматься там целый месяц?

– У меня есть усадьба в долине Снежных Холмов, – произнес я, и тут же почувствовал внутри себя приятное тепло, вызванное воспоминаниями о доме. – Теперь там совсем пусто, не считая нескольких брошенных домов, хотя когда-то в этом месте просто кипела жизнь. Я даже застал это время. В юношеские годы мне уже приходилось проходить несколько километров до конечной остановки поезда, дабы вовремя добраться до университета. А закончив его, я устроился на работу и в следующем же месяце снял себе квартиру в спальном районе города. Но мне все еще дорога та усадьба, столько воспоминаний связанных с домом… Да и местность там несказанно красива. В общем, прежде чем вернуться на м83, мне хочется провести в долине еще какое-то время. Жаль, перед этим еще придется решить вопрос с университетом, – я вздохнул. – Как бы мне хотелось показать тебе долину Снежных Холмов, Отем.

Она улыбнулась мне своей очаровательной загадочной улыбкой, и тогда я понял, что уже успел всем сердцем полюбить ее.

– Скорей всего, у тебя еще будет такая возможность.

– Я все никак не решался спросить, – наконец, произнес я, и Отем внимательно посмотрела на меня, – какие у тебя самой планы на будущее? Конечно, здесь чудесно: и звезды, и эти уголки природы, разбросанные по всей Луне, не могут не очаровывать, но ты никогда не думала о том, чтоб окончательно вернуться на Землю?

Отем вздохнула и слегка улыбнулась.

– Это ведь не совсем то, что ты хотел спросить, верно? Ты хочешь знать, есть ли в моем будущем ты, Старлайт.

Я улыбнулся и прижал ее к себе.

– Твоя проницательность порой сводит меня с ума.

Отем улыбнулась в ответ.

– Мне хотелось бы вернуться на Землю, – говорила она. – Не прямо сейчас, а лет семь спустя. И, конечно, мне бы хотелось, чтоб в этот момент ты был рядом со мной.

Отем произнесла эти слова с привычным для нее спокойствием, ну а я почувствовал сильнейший прилив чувств, вызванный этой фразой. Казалось, мне вновь семнадцать. Я был счастлив как мальчишка.

– И где бы ты предпочла жить? – спросил я.

– В Исландии, конечно, – все так же спокойно ответила Отем.

– Ничего себе, я и подумать не мог, что тебя заинтересует это место.

– Почему? – удивилась она. – Там ведь ужасно красиво. Никакой суеты.

– Не знаю. Мне казалось, тебе захочется обустроиться в Штатах.

– Ну уж нет, – ухмыльнулась Отем. – Я ни за что не вернусь в Штаты.

Я уловил в ее словах некую горечь, возможно, связанную с домом, но не стал вдаваться в расспросы. Совсем не хотелось портить этот чудеснейший из вечеров.

Не успел я что-либо ответить, как из браслета Отем раздался сигнал. Она освободилась от моих объятий, вывела перед собой голографическую панель, и внимательно посмотрела на экран.

Мне совсем не нравилось выражение ее лица. В еще мгновенье назад светящихся умиротворением глазах сквозило некое беспокойство.

– В чем дело, Отем?

– Это сообщение, – тихо ответила она.

– Что в нем?

– Пока не знаю.

Я хотел спросить, отчего же она не прочтет сообщение, но Отем тут же ответила на мой вопрос.

– Не нравится мне это. В выходной день меня не стали бы тревожить из-за пустяков.

– Брось, – я постарался улыбнуться, хотя и сам теперь чувствовал небольшую тревогу. – Должно быть, кому-то просто нужна твоя помощь.

Отем кивнула, и, проведя по воздуху пальцами, вывела на экран новое сообщение. Сидя напротив, я не мог увидеть его текст, но сразу же заметил, как по мере чтения расширялись зрачки девушки. В тот момент я мог бы поклясться, что ее и без того фарфоровая кожа стала еще бледней.

– Все в порядке, дорогая?

Отем подняла глаза. Мне был знаком этот взгляд. Я уже видел его прежде, когда Отем полностью погружалась в собственные мысли. И каждый раз это предвещало тревожные последствия.

– Отем? – позвал я.

Она вмиг сделалась гораздо серьезней, а от взгляда затуманенных глаз не осталось и следа. Моя любимая на время исчезла. Сейчас передо мной была только Отем Раст – капитан м83.

– Нам нужно идти, Старлайт, – поднимаясь, произнесла она. – Еще один сотрудник пострадал на темной стороне Луны.

\*

Я так устал быть в одиночестве, изо дня в день проходить один и тот же путь и видеть лишь холодные мрачные стены вокруг себя – такие жалкие мысли кружились в моей голове, когда, возвращаясь в свою комнату прямиком из тринадцатого, я нашел Кита Терренса. Вернее сказать, сперва я его услышал. Пронзительный крик старика разносился по всему коридору. Крик, полный безумия, поспешив навстречу которому, я вскоре увидел и самого Кита. Он лежал на земле, обхватив себя руками, и истошно выкрикивал повторяющуюся фразу, которую просто невозможно было разобрать.

Не успел я опомниться, а к нам уже подоспели другие бурильщики, растревоженные этим внезапным нарушением привычной тишины. И вот, спустя треть четверти, я вновь оказался в одном из тускло освещенных кабинетов ИБЛП.

Мне определенно не нравилось это место. В тесном замкнутом пространстве, лишенном даже таких простых признаков комфорта как окна, я чувствовал себя изолированным от внешнего мира, загнанным в угол. Но, что еще хуже, мне совершенно не нравились окружающие меня люди – военные. Всем своим видом они внушали в меня страх.

Как только Кит был доставлен в госпиталь, я сразу же поспешил в свой отсек, как всегда мечтая о теплой постели и нескольких часах отдыха. Разумеется, там меня уже ожидал один из военных.

– Мистер Блек, – произнес он, равномерно выговаривая каждый слог, – пройдемте мо мной.

Я не стал возражать и безмолвно последовал за ним.

Солдат отвел меня в институт, а затем по его темным коридорам вглубь здания. Мы пришли прямиком в ту комнату, где со мной уже однажды общалась капитан, ну, или в схожую с ней, теперь я уже не помнил наверняка, да и это было совсем не важно.

Высокий светлый мужчина с явными афроамериканскими чертами лица представился старшим помощником капитана и попросил меня какое-то время побыть в аудитории. И снова я не стал возражать. Тогда он вышел, а я остался сидеть за столом. Мне не сказали, чего именно стоит ожидать, но я догадывался, что вскоре вновь увижу капитана.

Спустя двадцать минут, или около того, я услышал за дверью приближающиеся шаги и приглушенный женский голос, которому вскоре ответил мужской. Слов было не разобрать. Дверь тут же отворилась, и в кабинет вошла капитан. Она бросила в мою сторону пристальный взгляд, остановилась, и сложив руки на груди, облокотилась о стену около входа.

Прежде чем она заговорила, я успел заметить, что в этот раз Отем Раст выглядела куда более встревоженной, возможно, даже рассеянной. Мне этого было не понять, ведь со стариком Терренсом и так уже давно все было ясно как день.

Что касается капитана, стоило ей войти, как у меня сложилось впечатление, что вынужденная встреча со мной оторвала ее от каких-то важных и более приятных дел.

«А ты не похожа на других военных, – подумал я. – Интересно…»

– Что интересно? – спросила капитан, и тогда я понял, что сказал вслух последнее слово.

– Ничего. Просто задумался, – соврал я.

Обмена приветствиями не последовало, и капитан сразу же перешла к делу.

– Мне очень неприятна эта ситуация, мистер Блек, – начала она. – Надеюсь, Вы осознаете, чем она чревата для Вас?

Я непонимающе поднял брови.

– В каком смысле?

– За последние пару месяцев здесь произошло уже два необъяснимых случая, и в обоих Вы выступаете как главный свидетель. Это дело рискует обернуться для Вас плохим.

После этих слов я глубоко вздохнул, и откинулся на неудобную спинку стула. Хотелось скрестить руки на груди, но я знал, что на подобных встречах таких жестов со стороны допрашиваемых, мягко говоря, не терпят.

– Мне и самому это приходило в голову, Капитан, – ответил я, стараясь выглядеть спокойным.

– Хорошо, – сказала она. – Тогда расскажите мне все, что знаете.

\*

Начну с того, что старик Терренс всегда считался в наших кругах человеком не от мира сего. Он довольно поздно попал на м83, перевелся с одной из других баз, как я понял, и за тринадцать лет работы Терренса в третьем бурильном пункте очень немногие могли похвастаться тем, что слыхали от него хотя бы пару словечек. Но, в большинстве своем, странности его проявлялись далеко не в этом. В голове старика уже долгие годы присутствовала некая фобия, навязчивая идея, если угодно. Сколько я его помню, Кит всегда был убежден в том, что за ним постоянно следят. Он как-то неуверенно и с опаской бродил по коридорам, чаще всего молча. А иногда, все-таки, решался заговорить. Речь эта ограничивалась только банальными фразами, связанными с работой. Ничего больше.

Как я уже сказал, о странностях Терренса здесь знали все, но никто уже давно не предавал этому особого значения, хотя однажды он здорово напугал своим паническим приступом одну пожилую туристку.

На самом деле, мне не совсем понятно, почему после всего этого Терренс все еще здесь, но мое дело бурить, а не задавать вопросы. К тому же, наша работа грязная, однотипная и далеко не перспективная. Кто сейчас на такую пойдет, если есть множество куда более привлекательных вариантов? Я и сам прогадал с профессией: ни передохнуть толком, ни на Луну посмотреть, но что уж теперь сожалеть-то…

– Мистер Блек, – прервала меня капитан, – прошу Вас, давайте не будем отклоняться от основной темы.

Я удивленно взглянул на нее и тут же улыбнулся. Сам я уж никак не ожидал, что вдруг окажусь таким болтливым. Видимо, человек может сказать гораздо больше, когда его есть кому слушать.

– Конечно, Капитан, простите. Наверное, я просто слишком долго был один, – ответил я.

Отем Раст опустила глаза, и я подумал, что, должно быть, чувствует она себя сейчас неловко. Еще несколько секунд я подождал ответа, он его так и не последовало, а потому я продолжил.

– Когда, идя по тоннелю, я услышал крики, то сразу же понял, что это был Терренс. Дело даже в не голосе. Просто кто еще здесь будет так орать? В общем, я прибавил шагу. Шум лишь нарастал по мере моего приближения к его источнику. Вскоре я увидел старика, валяющегося на земле. Было это у дверного отсека, ведущего к третьему пункту. Тогда я понял, что не ошибся.

– Значит, у мистера Терренса уже случались подобные истерики до этого дня? – спросила капитан.

– На моей памяти только один, не считая сегодняшнего.

Капитан подошла к столу и опустилась напротив меня.

– Расскажите мне про тот случай, – она сложила руки перед собой и наклонилась ко мне. – Как думаете, почему подобное могло произойти с ним?

Свет падал лишь на центральную часть комнаты, и только сейчас я заметил, что капитан выглядит гораздо моложе, нежели мне представлялось ранее. Я также не мог не обратить внимания на ее ясные синие глаза. Казалось, весь недостающий свет кабинета собрался в этих глазах, и сейчас они сияли ярче Луны.

– Это было около пяти лет назад, – наконец, ответил я. – Тогда я уже перевелся в только открывшийся тринадцатый пункт. Для полноценной работы в нем мне нужен был напарник. Новичка никто брать не хотел, ведь по сравнению с остальными, я и сам еще был дебютантом, а потому ко мне решили распределить кого-то из более опытных сотрудников. Как чаще всего и бывает, первым переводят того, кто плохо прижился в коллективе, а в случае с Терренсом, он не прижился вовсе.

Вместе мы проработали всего ничего: пару недель или вроде того. Потом четверть подошла к концу. На носу была проверка, и нам нужно было выбраться на поверхность, дабы обойти оборудование и лично убедиться в том, что работа выполняется надлежащим образом. Я хорошо помню тот день еще и потому, что это был последний раз, когда я надевал лунный костюм, не считая недавних событий.

Мы облачились в скафандры и, усевшись на луноходы, прошлись по всему сектору. Когда пришло время возвращаться в тринадцатый, и я уже мчался обратно, (я старался поскорей покончить со всеми делами на поверхность, ведь там ужасно холодно, и даже костюм не спасает) но заметил, что Терренс отстает. Я видел свет, исходящий от фонаря его лунохода, но сам старик упорно не отвечал мне, сколько я не звал его по имени. Пришлось разворачиваться.

Нужное расстояние я преодолел в два счета, но старика уже не было на месте. Оглядевшись по сторонам, я услышал приглушенный крик, доносящийся до моих ушей словно из-под земли. Тогда я направил свой фонарь в то место, из которого, как мне казалось, доносился крик, и минутой позже обнаружил самого старика. Он лежал прямиком на холодной поверхности и без конца выкрикивал что-то нечленораздельное. В ту минуту я был настолько сильно повергнут в шок, что не сразу заметил, что Терренс пытается стянуть с себя шлем. К счастью для старика, тот не поддавался его трясущимся рукам. Так быстро как мог, я подобрался к Киту и, закинув все еще вопящего старика на луноход, помчался в сторону здания. Вскоре Терренса доставили в госпиталь, а на его место был направлен Метьюз.

Я закончил рассказ и посмотрел на капитана.

– Можете описать, где конкретно Вы нашли орущего Терренса? – попросила она. – В тот, первый раз, я имею ввиду.

Она ждала ответа, но мне было практически нечего сказать. Я снова вздохнул.

– Бедняга валялся на земле, когда фонарь моего лунохода осветил его. Прямо посреди темноты лежал.

– Никаких примечательных знаков? – не унималась капитан. – Может быть, в тот день произошло еще что-то, что Вы запомнили? Какая-нибудь незначительная деталь?

Я покачал головой.

– Что ж, спасибо и на этом, мистер Блек.

– Я бы хотел рассказать больше, но это действительно все, что я сейчас могу вспомнить.

Я удивился собственным словам. Несмотря на свою настойчивость, капитан определенно располагала к себе людей.

Она понимающе кивнула и поднялась из-за стола.

– Последний вопрос, мистер Блек, – произнесла Капитан, направляясь к выходу.

– Я слушаю.

– Как Вы думаете, почему после первого случая Терренс по-прежнему работает здесь, на темной стороне Луны?

Этот вопрос застал меня врасплох. До этого мне казалось, что капитану были интересны только сухие факты, а никак не мое мнение касательно их.

– Не имею и малейшего понятия, – честно сказал я, и, поразмыслив, решился добавить еще кое-что: – Джек Метьюз говорил, что для них так удобней: держать сумасшедшего под рукой.

– Для кого для них? – ошарашено спросила капитан.

– Не знаю, но, боюсь, он имел ввиду вас, – тихо ответил я, бросив взгляд на дверь.

– Военных?

– Да, в том числе…

Капитан отстранилась от двери и вновь подошла ко мне.

– Я не понимаю, – говорила она, – в каком смысле?

– Это были его слова, Капитан, не мои. Думаю, Джек намекал на то, что вы не хотите разглашения подобной информации. А Вы ведь не хотите, я прав?

– Да, – согласилась капитан. – Это было бы неприятно. Но, все же, думаю, что мистеру Терренсу придется вернуться домой сразу же по окончании лечения.

– На Землю? – теперь пришла моя очередь удивиться.

– Да, именно так, – капитан протянула мне руку, и я пожал ее. – До встречи, мистер Блек.

– До встречи, – ответил я, и она скрылась за дверью.

Возвращаясь в свою комнату, я в последний раз видел Отем Раст. Со спрятанными в карманы пальто руками, она стояла, вглядываясь в темноту за стеклом. Заметив меня, капитан кивнула и вернулась обратно к своим мыслям.

Я кивнул ей в ответ, хотя знал, что она этого не увидит.