---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---


# Атлантида {#14}

Военный госпиталь, в который мне обычно приходилось обращаться, находился в правом левом здания штаба и занимал весь шестнадцатый этаж, но сейчас я направлялась в другое место – небольшую больничку, расположенную сразу перед спальными отсеками для работников темной стороны Луны.

К счастью, больница была построена практически у самого входа на темную сторону, так что на этот раз мне почти не пришлось ступать по коридорам длинного тускло освещенного тоннеля, ведущего к пунктам бурения.

Пройдя по тоннелю всего пару шагов, я остановилась у первой встретившейся мне двери. На ней не было никаких знаков или надписей, но я хорошо помнила план здешней местности, а значит, это была именно та дверь. Я поспешила отворить ее: не хотелось надолго оставаться одной в этом угнетающем месте.

Выполненные в серо-синих тонах, все строения, возведенные в этой части Луны, были однотипными. Они беспрестанно напоминали друг друга и вполне могли бы сойти за осколки одного и того же здания, разбросанные по всей темной стороне.

По сути, сам госпиталь представлял собой девять этажей мрачного угловатого здания продолговатой и слегка приплюснутой формы. Со стороны это местечко выглядело крайне безвкусно и неуютно. Стоящее среди ледяной темноты, оно напоминало мне отрывок давно опустевшего и затонувшего подводного городка. Такая космическая Атлантида.

Сделав еще несколько шагов вперед по смежному коридору, я отворила следующую дверь и оказалась в небольшой серой комнатке, служившей этому месту холлом. За столом, что стоял под правой стеной, было пусто. Пришлось воспользоваться браслетом.

Если верить плану, на первом этаже были размещены только холл и столовая. Палаты же находились на всех последующих этажах, начиная со второго. К ним вела лестница, расположенная в конце комнаты.

Я сняла пальто, и, оставив его в подобии приемной, направилась к ступеням. В отчете Сириуса говорилось, что Кит Терренс находится на последнем этаже, и, когда я поднялась туда, то поняла, почему.

Терренс не замолкал ни на минуту. Он вопил и извивался на кровати, превратив аккуратно уложенную постель в кучу тряпок, сбившихся у изголовья его койки. Я услышала этот крик сразу же, стоило мне лишь ступить на лестничную клетку.

Как мне было известно из упомянутого выше отчета, медсестры периодически вводили бедняге дозу успокоительного, но и это не могло заставить Терренса замолчать. Время от времени, его голос срывался, изнемогая от бесконечных криков, но и тогда старик продолжал трястись и бормотать понятные лишь ему одному фразы.

Окромя Терренса, на девятом этаже не было других пациентов, как и на предыдущем, и том, что был до него. Всех больных перевели как можно ниже, пытаясь изолировать от них старика: лежавшим здесь требовался покой.

Не успела я подняться на девятый этаж, а мне навстречу уже шла одна из медсестер, поочередно дежуривших у кровати Терренса.

– Капитан Раст, – произнесла она, – мне говорили, что Вы придете.

–Добрый день, сестра. Как сегодня себя чувствует мистер Терренс?

Уже задав этот вопрос, я поняла, насколько глупым он был, ведь я отлично слышала мистера Терренса прямо сейчас и то, что доносилось до моих ушей, едва ли говорило о его выздоровлении.

– Ох, – только и протянула в ответ медсестра.

На вид ей было лет пятьдесят с лишним. «В вопросах возраста не бывает лишнего», – любил говорить Корнуэлл.

Мне тут же захотелось извиниться за свою глупость, но вместо этого я задала следующий вопрос.

– Вы можете сказать, что с ним?

– У больного шок, – с усталостью на лице ответила сестра, – вызывающий яркие панические атаки.

– Да, я вижу.

– Пока это все, что я могу сказать Вам.

– Благодарю. Могу я его увидеть?

Я в ожидании взглянула на свою собеседницу. Она пожала плечами.

– Можете попробовать. С ним невозможно говорить.

Я кивнула и направилась в палату.

«Палата номер шесть» – гласила надпись над входом.

– Постойте, – окликнула меня сестра. – Возьмите это с собой.

Я обернулась. Она протягивала мне что-то. Присмотревшись, я поняла, что этим чем-то были беруши.

– Благодарю, но мне это не нужно, – отмахнулась я.

Уже спустя минуту я пожалела о своем решении.

– Ну, как знаете, – сказала женщина, и направилась в сторону лестницы. – Позовите меня, когда закончите. Там на стене у кровати есть кнопка вызова.

– Хорошо.

Открыв ведущую в палату дверь, я сразу же почувствовала сильнейшее желание прикрыть уши руками, хотя это вряд ли смогло бы помочь мне. Так или иначе, находиться здесь было определенно невозможно.

Переборов резкую головную боль, вызванную внезапным шумом, я просидела в палате номер шесть около часа. Как и предупреждала медсестра, старик так и не ответил ни на один из заданных мною вопросов. Да что там говорить, он полностью игнорировал их и, скорей всего, даже не подозревал о моем присутствии. Все это время Терренс продолжал извиваться в постели под аккомпанемент собственных криков.

Я все пыталась понять, что же могло сотворить с человеком такое. В этом организованном и таком правильном лунном мире просто не могло быть ничего, что послужило бы катализатором подобного поведения.

Прошло еще минут пятнадцать, и я окончательно сдалась.

– Мне нужно идти, мистер Терренс, – сказала я, поднимаясь с соседней от его кровати. – Надеюсь, вскоре Вы придете в себя, и тогда я распоряжусь о Вашем возвращении на Землю.

Я протянула руку и нажала на кнопку вызова медсестры, когда заметила, что что-то изменилось. И каково же было мое удивление, когда я поняла, что старик вдруг замолчал. Он медленно повернул голову и заглянул мне прямо в глаза. Я даже отшатнулась от удивления.

– Вам ясны мои слова, мистер Терренс? – с надеждой спросила я.

Он не отвечал.

–Думаю, Вы меня поняли. А теперь будьте душкой и расскажите мне о том, что произошло с Вами в тоннеле тем вечером?

Но старик продолжал молчать.

Я глубоко вздохнула, пытаясь соблюдать спокойствие.

– Мистер Терренс, прошу Вас.

Безрезультатно.

– Святые небеса! Ушам своим не верю, – услышала я удивленный голос за своей спиной.

На пороге появилась медсестра. Она стояла у входа в палату, переводя взгляд то на меня, то на старика.

– Как Вам это удалось? – обратилась ко мне женщина.

– Мы просто поговорили, – уклоняясь от ответа, произнесла я. – До свидания, мистер Терренс.

Я вышла из палаты старика прежде, чем сестра успела задать мне еще какие-нибудь вопросы. Вопросы, ответов на которые я не знала. Теперь у меня было много вещей, над которыми стоило подумать. Хорошо хоть Терренс прекратил истерики – одной проблемой меньше.