---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---


# Жаль, что тебя здесь нет {#15}

– Давай прогуляемся по Луне еще разок перед моим отъездом? – предложил Старлайт.

Мы встретились по окончании тяжелой рабочей недели, и вот уже час как болтали лежа в его постели.

– Ну же, - подбодрил меня Старлайт, – не будь так печальна. Я постараюсь решить все свои земные дела как можно скорей и тут же вернусь к тебе уже с новым проектом. Месяц пролетит практически незаметно, обещаю.

Я подняла голову, и взглянула в его прекрасные карие глаза.

– Я ждала тебя десять лет, милый, – я улыбнулась, - смогу подождать еще месяц.

Старлайт расплылся в улыбке и поцеловал меня.

– Тогда пройдемся завтра утром? – спросил он.

– Конечно, - ответила я. – Но прежде чем ты решишь уснуть, я бы хотела кое-что показать тебе.

Он с интересом взглянул на меня.

– Что же?

– Увидишь, – я со смехом стянула с него одеяло. – А теперь поднимайся, если хочешь успеть выйти со штаба до того как на дежурство заступит Саймон и начнет донимать меня своими бесконечными расспросами.

– Надеюсь, оно того стоит, - шутливо протянул Старлайт, и, подняв лицо с подушки, лениво потянулся.

– Можешь не сомневаться, – весело ответила я, и протянула ему джинсы.

\*

Одевшись, мы вышли из здания штаба навстречу привычной темноте базы. Вечернее построение, проведенное Сириусом, окончилось с четверть часа назад, и я видела как в окнах первых пяти этажей здания то тут то там поочередно выключался свет — это солдаты готовились к долгожданному сну.

&nbsp; Над нами пронесся одинокий луноход, окутав холодным потоком воздуха. Держа Старлайта под руку, я вздрогнула и мысленно порадовалась тому, что на м83 не бывает ветра.

– Может, тоже возьмем луноход? - спросил Старлайт.

Я остановилась.

– Мне хотелось прогуляться, а ты слишком поздно опомнился, – сказала я, улыбнувшись. – Мы уже пришли.

– Правда? – удивился Стар. - А я-то боялся, что ты ведешь меня обратно в институт, – он рассмеялся.

Мы стояли около одного из небоскребов. Вернее пятого по счету с правой стороны от трассы. Лишь в редких окнах все еще горел свет, и мы вошли внутрь, воспользовавшись моим браслетом.

– Удобная штука, – с улыбкой сказал Старлайт, – многим бы на Земле пригодилась, а то я уже устал терять свою ключ-карту после каждых выходных.

– Не могу не согласиться. Хотя в последний раз я была дома так давно, что уже практически не помню, каково это – терять ключи.

– О, это мерзко, – ответил он и мы рассмеялись.

– А теперь следуй за мной, – позвала я, направляясь к закрытым лифтам, – и давай постараемся никого не разбудить.

– Мне знакомо это здание. Это ведь сектора для сотрудников. Август Штернбренер живет в соседнем. Но куда мы идем?

Я подумала, что теперь самое время рассказать о своей небольшой задумке.

– Помнишь, в конце осени я показывала тебе посылку от своего давнего друга, Корнуэлла? – начала я.

– Создателя коттеджного городка.

– Да, в ней также было письмо. Корнуэлл просил меня присмотреть за всем этим. Он был любителем антиквариата, что, собственно и не удивительно...

– Я догадался об этом по его работе, – улыбнулся Старлайт.

Мы вышли из лифта и последовали к крайней двери двенадцатого этажа. На ней все еще виднелась табличка с именем Корнуэлла.

– Во-первых, я уже прочла все книги, что были в моей комнате, и, честно говоря, мне этого жутко мало.

Я отворила дверь, и мы оказались в небольшой уютной квартирке, где все было пропитано духом старины. Войдя внутрь, мы попали в особенный мир — мир Джуда Корнуэлла.

Старлайт с восхищением рассматривал диковинную мебель, которой была набита прихожая.

– А во-вторых? - наконец спросил он.

– А во-вторых, - я взяла его руку и отвела Старлайта во вторую гостиную, – я хотела показать тебе это.

В самом углу комнаты уже многие годы стоял старый рояль. Несмотря на то, что эта вещь была далеко не из нашего времени, ее присутствие здесь казалось мне привычным и практически необходимым. Инструмента не касались уже несколько месяцев, и красную дубовую поверхность покрывал небольшой слой пыли. Старлайт выпустил мою руку и сделал несколько шагов в сторону рояля.

– Как ему это удалось? – восторженно спросил он, не сводя с рояля глаз. – Это ведь классическая модель 19... года. Должно быть, стоит сейчас целое состояние, не говоря уже о том, что во всем мире таких осталось не больше сотни.

– И три из них находятся у Корнуэлла, - не без улыбки сказала я. - Он провел не одно десятилетие, и, насколько мне известно, практически не прибегал к снятию вырученных средств. Можно сказать, Джуд в действительности сколотил состояние.  
Старлайт удивленно поднял брови.

– А остальные два, где они?

– Такой же стоит в доме Корнуэлла в Кентуки, а еще один он оставил в «Серебренном Роге», любимом пабе коттеджного городка. Он уезжал в спешке, – сказала я и добавила, указав на рояль: - Надо бы и этот пристроить в месте получше темной квартирки.

Все еще очарованный роялем, Старлайт, казалось, совсем не слышал моих слов, но минутой спустя спросил:

– Есть идеи?

– Да. Я подумываю о вишневых садах. Корнуэлл всегда восхищался ими так, словно видел впервые. А кроме того, именно там мы с ним познакомились.

Старлайт скинул пальто, и, аккуратно положив его на плетеное кресло-качалку, (будто боясь, что последнее вот-вот развалится) провел рукой по клавишам. Мне казалось, что те заскрипят, но, несмотря на свой возраст, инструмент издал восхитительное пение, и довольный этим, Стар тут же уселся за рояль.

Я опустилась рядом и с наслаждением наблюдала, как его пальцы ловко скользили по клавишам. Старлайт только разыгрывался, но я уже видела счастливые огоньки в его глазах. Склонившись над роялем, он выглядел так, словно с каждой сыгранной нотой обретал новое дыхание.

Находясь здесь, слушая чудесные мелодии ночи, я непроизвольно вспоминала первую встречу с Корнуэллом в вишневом саде. Странным и на самом деле невероятно удачным оказалось это знакомство, ведь обычно инженеры не ведут общение с рядовыми военными, они даже не пересекаются на протяжении многих лет, вплоть до того момента, пока кто-нибудь не дослужиться до одного из высших на м83 званий. Я же не знала и прежде никогда не задавалась вопросом, почему именно Корнуэлл встретился на моем пути тем сентябрьским утором, но это действительно было как минимум удачным стечением обстоятельств. Не случись этого, сейчас все могла бы быть совершенно иначе. Да, вишневые сады определенно сыграли в моей жизни важную роль.

Вслед за этими мыслями пришли другие — воспоминания об академии и, в частности, последнем дне, проведенном в ней. Я отлично помню каменные аллеи дворика, ведущие от самого акведука, по обе стороны которых с наступлением весны расцветали вишневые деревья, что по земным меркам было одним из первых признаков роскоши и серьезности заведения. Наверное, это и есть одно из тех мест, которые совершенно невозможно забыть. Даже по прошествии стольких лет достаточно было лишь закрыть глаза, и воспоминания становились настолько яркими, что на мгновенье можно было ощутить в воздухе вишневый запах.

Голос Старлайта вырвал меня из воспоминаний, и я заметила, что музыка стихла.

– Хочу сыграть тебе кое-что, - произнес Старлайт.

Я заинтересованно посмотрела на него.

– Я не нашел этой песни ни на одной из твоих пластинок, - говорил он, - но она поистине чудесна. Называется «Жаль, что тебя здесь нет», старая мелодия Пинк-Флойд из одноименного альбома.

Я улыбнулась.

– Интересно...

Старлайт согласно кивнул и взялся за вступление. Его музыка и само это место навеяли на меня удивительную бурю эмоций, и, наблюдая его серьезный вид и сосредоточенность на игре, я чувствовала как влюбляюсь в него. Снова и снова.

– Звучит волшебно, – произнесла я. – И как только у тебя это выходит...

– На Земле я любил исполнять ее по субботним вечерам в одном небольшом пабе, что недалеко от центра моего района. А в последний раз я делал это в Стране Садов, кажется. Честно говоря, я уже столько раз играл ее, что пальцы сами ложатся на нужные клавиши, и мне даже не нужно задумываться о том, что я делаю. Хотя, поверь мне, на самом деле это совсем не сложно. Если хочешь, я мог бы научить тебя.

Я положила голову на его плечо.

– Конечно.

– Но самое прекрасное в этой песне — текст, простой и в то же время такой глубокий, – продолжал Старлайт, и прежде, чем я успела ответить, не отводя взгляд, начал петь.  
Его слова звучали успокаивающе приятно, и в этот самый момент мне подумалось, что с этим голосом не способен сравниться ни один другой.

_Действительно ли ты думаешь, что способен
увидеть разницу между Раем и Адом,  
ясным небом и болью?_

_Можешь ли ты отличить зеленое поле  
от стальной рельсы? Улыбку от вуали?  
Думаешь, ты правда знаешь разницу?_

_Неужели они и впрямь убедили тебя променять  
своих героев на призраков?  
Жаркий пепел на деревья?_

_Теплый воздух на бриз?_

_Холодный комфорт на цепи?  
Действительно ли ты предпочел
проходную роль на войне основной в клетке?_

_Как же мне жаль, что тебя здесь нет,  
Ведь мы словно две заблудшие души,
год за годом плавающие в тесном аквариуме,  
вновь и вновь повторяем былые ошибки.  
Но что мы при этом обретаем?  
Все те же старые страхи.  
И, все же, как жаль, что ты не рядом._

Закончив композицию, Старлайт улыбнулся мне самым великолепным образом.

– Очаровательно, - сказала я. - Никогда не слышала ничего более волшебного.

Немного смущенный моими словами, он взял мои ладонь в свою, и произнес фразу, которую в будущем я не раз буду вспоминать.

– Я не знаю, что ждет нас дальше, и, по правде говоря, просто не могу этого знать, но если жизнь решит разлучить нас на время, прошу тебя, просто приходи сюда, когда будешь тосковать по мне, - он улыбнулся, - или в вишневый сад, если все же решишь поставить рояль там. Достаточно будет только напеть эту мелодию, и ты сразу же вспомнишь этот самый момент, то, как я смотрю на тебя прямо сейчас, и поймешь, что больше не одна во вселенной. Ты всегда в моем сердце.

– Ох, Старлайт, – я обняла его, - только теперь я осознаю, как сильно мне не хватало тебя все это время.

– Я люблю тебя, Отем, – произнес он и, увидев мой смущенно-ошеломленный вид, широко улыбнулся.

Старлайт положил мои руки на невесомые клавиши рояля.

– А теперь давай я научу тебя этой мелодии, - сказал он.