---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Опасения {#16}

Первая четверть лишь начиналась. Отем и я сидели за столом в одной из комнат отдыха. Меня с самого начала удивило то, что девушка предпочла занять места, находившиеся далеко от окон, но когда на протяжении получаса она так и не притронулась к завтраку, я не мог более оставаться равнодушным, и спросил в чем дело.

Ее холодные пальцы нервно сжимали полную кофе чашку, когда Отем рассказывала мне о своих снах. Я смотрел в ее ясные как океан глаза, и буквально видел, как в них отражалась описываемая гибель Земли. Так, словно я и сам был частью ее сна.

– Я переживала это снова и снова, – говорила Отем. – В конечном счете, я знала, что нахожусь всего лишь во сне, но беспокойство и ужас, охватившие меня, были столь явственны и реалистичны... После всего этого в моей душе затаилось мерзкое тревожное чувство, и вот уже который день я никак не могу избавиться от него.

Я отставил кофейную чашку и, наклонившись к Отем, сжал ее дрожащие руки в своих ладонях, в очередной раз удивившись про себя тому, какими же холодными были ее пальцы.

– Послушай дорогая, – говорил я. – Я всегда полагал, что сны, особенно такие яркие как этот, являются лишь отражением нашего подсознания. Мыслей, которые на протяжении долгого времени таились в самых глубинах разума. А в определенный момент, такой как этот, они просто вырываются наружу.

Слушая меня, она высвободила одну руку из моих ладоней, и принялась машинально стучать пальцами по поверхности стола.

– Ох, Стар, никогда не думала, что однажды скажу это, но я больше не чувствую себя в безопасности, будучи на м83.

Она вздохнула.

– Понимаю, – ответил я, – Эти толчки всех сбили с толку. Странно, что процентный рейтинг туристических посещений до сих пор не упал.

Отем вдруг перестала стучать по столу пальцами и внимательно посмотрела на меня.

– Что ты сказал?

– Туристы, – повторил я. – Странно, что они ежедневно все так же продолжают прибывать сюда.

– Вовсе нет, – просияла Отем.

Удивленный таким ответом, я хотел спросить, о чем это она, но Отем тут же поднялась из-за стола.  
<br/>– Мне нужно бежать. Прости, Старлайт, и спасибо тебе.

– За что? – будучи еще более удивленным, произнес я, но Отем уже исчезла за пределами комнаты.

\*

Быстрым шагом я вошла в небольшой тусклый кабинет, расположенный в самом конце цокольного этажа здания штаба.

Уткнувшись в какие-то бумаги, Гастингс уже сидел за своим столом. Заметив мое появление, он мгновенно поднялся и, приветственно протянув руку, предложил присесть.

Питер Гастингс был тридцатишестилетним сотрудником местного справочного бюро, в чьи обязанности также входила работа по связи с внешним миром. Именно он вел переговоры с Калифорнийским Космическим Университетом, а позже и с самим Старлайтом, с целью привлечения последнего к сотрудничеству с м83. Несмотря на свою, казалось бы, довольно-таки коммуникабельную должность, Гастингс никогда не сходил в число особо общительных работников базы. Все свое время он предпочитал проводить в тесном кабинете цокольного этажа, занимаясь текучкой.

Внешне Гастингс был весьма привлекателен, а вот смекалки порой ему явно не доставало, хотя все это меркло и бледнело на фоне его необычной (для места и времени) манеры поведения. Мужчина этот бывал необычайно галантен, что в совокупности с его немалым ростом и правильными чертами лица напоминало героя какого-нибудь классического детективного романа. В этот раз при взгляде на него в моей памяти всплыл неведомо откуда взявшийся образ капитана полиции, рука об руку я гениальным детективом расследовавшего запутанное дельце.

– Мне нужны сводки земных новостей за.., – я ненадолго задумалась, – ... последний месяц.

– Сию минуту преступлю к делу, Капитан.

Гастингс молниеносно черкнул что-то в своей записной книге и вновь перевел свой взгляд в мою сторону.

– С какого именно региона Земли? – спросил он.

– Со всей Земли.

После этих слов Гастингс взглянул на меня с явным недоверием, (парень пробыл на м83 лишь пару лет, так что проявление эмоций пока еще не стало для него чуждым) которое тут же сменилось удивлением, когда он, наконец, понял серьезность моих слов.

– Но, Капитан, это ведь немыслимое количество информации...

– В таком случае, начните прямо сейчас, Гастингс. Отсейте все сведенья, не касающиеся м83 и нашей компании в целом, и снабдите меня лишь теми, что относятся непосредственно к ЭСКМО. Я понимаю, что это займет какое-то время, так что не стану давить со сроками, – произнесла я, и Гастингс вздохнул с облегчением, – но буду очень признательна, если Вы поспешите.

– Сделаю все, что в моих силах, Капитан.

Я кивнула, такой ответ меня вполне устраивал.

– Но учите, – добавила я, поднимаясь с потрепанного кресла, – меня интересуют не только сухие факты. Желтая пресса, любые сплетни, предположения и неподтвержденные заявления – все это также стоит внимания. Скорей всего, даже в первую очередь

Выходя, я краем глаза заметила, как Гастингс принялся искать для меня материалы, и с грустью подумала о том, что хорошо бы мне не умереть от бессонницы прежде чем он их найдет.

По хорошему счету, стоило бы сразу же намекнуть Гастингсу на то, что следует обратить внимание на наиболее тревожные сообщения, связанные с перепадами подземного давления, например, но интуиция подсказывала мне, что этого попросту не стоит делать. На счет самого Гастингса я не переживала: он был славный и ответственный парень, но не особо смышленый в свои тридцать с хвостиком, тогда как (если мои опасения и впрямь были верны) подобный запрос данных мог моментально привлечь ненужное внимание. Для меня же гораздо проще было объяснить желание просмотреть все новостные сводки.

С этими мыслями я, должно быть, впервые в жизни опоздала на очередное утреннее построение.

Подумать только, еще несколько месяцев назад в моей голове не могло быть и мысли о том, чтобы позволить себе придти куда-либо с опозданием, а сейчас меня это и вовсе не тревожило. В конце концов, я была капитаном.

Я улыбнулась: кажется, я и впрямь становлюсь больше похожей на человека и меньше на машину.

Войдя в холл, я увидела Сириуса. С непроницаемым, как и всегда, лицом, старпом направлялся прямиком ко мне. Возможно, он и был немного встревожен моим опозданием. Сложно было сказать.

Мне вспомнились старые дни в академии и то, каким вечно-смеющимся тогда я видела Сириуса. Несмотря на хорошие результаты в учебе, в повседневной жизни он бывал просто несносен с этой своей несерьезностью. И вот, спустя десять лет, я смотрела на все того же повзрослевшего Сириуса, стараясь понять, что у него на уме.

Прежде, чем старпом успел пересечь и половину холла, я повернулась лицом в шеренге солдат.

– Простите мое временное отсутствие, имелись неотложные дела, – произнесла я. – Насколько я помню, на эту неделю у нас с вами были запланированы ежеквартальные учения. Так давайте же преступим.

\*

Проведя стандартный опрос, я стояла на террасе собственного кабинета, наблюдая вышагивающими внизу солдатами.

Учения для военных прежде имели место быть каждый месяц, но несколько лет назад, после того, как смертная казнь была вновь узаконена и случаи нападения космических пиратов свелись к, казалось бы, невозможному минимуму, подобные учения стали проводиться лишь раз в квартал.

Зная все наши новые стратегии, (хотя бы потому, что я была основным разработчиком многих из них) я с уверенностью могла сказать, что мои ребята были отлично подготовлены и проинформированы. Теперь никому не под силу было проникнуть вооруженным на базу без нашего на то ведома, не говоря уже о попытке захвата какой-либо из ее частей. На протяжении последних лет эта задача оставалась для внезаконников невыполнимой, и мысль об этом не могла не вызывать у меня чувства удовлетворения.

И, все же, я по-прежнему не унималась. После исчезновения Метьюза и инцидента с Терренсом в моей душе застыло беспокойство.

– Нет, – произнесла я, стараясь привести мысли и нервы в порядок. – Невозможно проникнуть на базу незамеченным, не зная о том, как все здесь устроено и не имея понятия о наших стратегиях.

– Совершенно верно, – услышала я знакомый монотонный голос позади себя.

– Сириус, – не оборачиваясь сказала я, – Я совсем не слышала как ты вошел.

– Я постучал несколько раз, но ответа не последовало, так что я позволил себе войти. Я видел снизу, что ты здесь.

Старпом поравнялся со мной, и, облокотившись о поручни, тоже устремил свой взгляд вниз.

– Почему ты решила начать учения сегодня? – спросил он. – До конца этого квартала еще больше месяца.

Честно говоря, я ожидала этого вопроса еще с конца прошлой недели, когда внесла военные учения в общий план. И, все же, я немного замешкалась прежде чем ответить.

– Интуиция, – призналась я. – Мне совсем неспокойно в свете последних событий.

– Да, в последнее время ты сама не своя, – согласился Сириус. – Но что ты имеешь ввиду, говоря об интуиции?

Я удивленно подняла брови.

– Не думал, что она у тебя есть, – объяснил старпом, после чего его лицо приняло довольно-таки странное выражение, и мне еще понадобилось какое-то время, дабы понять, что он шутит.

– Меня жутко беспокоит все это, – продолжила я.

Сириус кивнул. К счастью, ему можно было довериться.

– Тогда могу я узнать, что ты сам об этом думаешь?

Он прекратил наблюдать за строем военных, и повернулся ко мне. На его лице читалось такое удивительное спокойствие, что я даже позавидовала.

– Касательно того мрачного парня, Терренса, он всегда был не в своем уме, так что давай признаем это. К тому же, старику уже немало лет, – говорил Сириус, – а вот в историю с Метьюзом мне верится очень слабо.

– Ему оставался лишь год до пенсии, – добавила я, – да и куда он мог деться с Луны? Это же нелепо.

– Дело даже не в этом. Я был хорошо знаком с Джеком. Дезертир? Он славный малый, совершенно не такой человек, каким его пытаются теперь выставить, и любой способен подтвердить мои слова. Или, правильней будет сказать, был не таким.

Уже знакомая дрожь подкралась к моему сердце после его последней фразы.

– Так ты полагаешь, Метьюз погиб? – дрожащим голосом произнесла я.

– Да. Я практически уверен в этом. Иначе мне пришлось бы усомниться в его чести, а к этому я сейчас явно не готов.

Мне показалось, что я, наконец, услышала голосе Сириуса нотки глубоко скрытой скорби. Словно заметив это, он поспешно вернулся к предыдущей теме.

– Так что с построениями? – спросил он. – Планируешь проводить их до конца недели?

– Нет, – уверенно ответила я, – до конца месяца. Затем последует небольшой перерыв, и начнем все заново.

Сириус не стал возражать.