---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Темнота {#17}

Я взглянул в окно пассажирского корабля с мелодичным названием «Лунная Волна», и увидел Отем. Она стояла под прозрачным навесом, отделявшим взлетную полосу от космодрома.

Неделя подходила к концу. Все туристы покинули городок, и, разместившись в просторном салоне, уже мирно посапывали, забывшись безмятежным сном. Новый заезд на Луну должен был быть лишь спустя два дня, так что на всем космодроме не было ни души, что, казалось, увеличивало его и без того значительную масштабность.

Я смотрел на Отем, одиноко наблюдающую за судном, и думал, какой же все-таки маленькой она казалась мне на фоне этих громадных мрачных зданий. Одета как всегда в черное и укутанная в широкий вязаный шарф, сейчас она меньше всего напоминала капитана м83.

Корабль бесшумно стартовал, и мне пришлось усесться вполоборота, дабы все еще иметь возможность видеть Отем. Она слегка улыбнулась и махнула мне рукой.

«А ты и впрямь похожа на осень,» - подумал я и помахал в ответ.

Наверное, именно в этот момент я впервые увидел ее настоящую, без какой либо тени преображений, вызванных луной и ее синим воздухом.

Судно поднималось все выше и выше над м83, унося меня все дальше от Отем. Вскоре и она, и городок, и сама база исчезли, растворившись в темноте и оставив за собой только звезды. Это произошло настолько быстро, что события последних шести месяцев показались мне волшебным сном.

– Отражатели, - вздохнул я и, последовав примеру других пассажиров, постарался уснуть.

\*
Земля встретила меня будучи все такой же как и прежде. К счастью для самого себя, я пробыл недостаточно много времени вне этого мира технологий, чтобы успеть в нем разочароваться. Однако, стоило мне только сойти с корабля, и я тут же почувствовал как замершее прежде время молниеносно пустилось вспять, словно желая скорей наверстать опушенные часы.

Мимо меня сплошь и рядом проносилось безмерное количество транспорта, а столь популярные в этом веке ай-роады и вовсе заполняли улицы. Мой поношенный Порше ждал меня на долгосрочной парковке около дома, поэтому добираться до него мне пришлось как и в университетские годы — скоростным надземным поездом, стоя в проходе которого я на протяжении всего пути наблюдал столь хорошо знакомую панораму города.

Несмотря на наличие собственного автомобиля, этот вид транспорта всегда приходился мне по душе. Линии путей проходили на высоте трехсот пятидесяти метров над уровнем трассы, что позволяло избегать привычного в наши дни столпотворения транспорта. К тому же, как и космическое судно, поезд двигался без лишнего шума, вне зависимости от набираемой скорости, оттого в другие дни я спокойно мог отдохнуть в нем, расположившись подальше от выхода. Но только не сегодня. Сейчас я был как никогда преисполнен энергии и решимости взяться за накопившиеся за полгода дела и побыстрей покончить с ними, дабы как можно скорей вернуться к своей любимой.

Первым делом с решил отправиться в университету. Нужно было окончательно решить вопрос с моим увольнением, потому что, уезжая в прошлый раз, я лишь оформил перевод на м83 сроком на год, а после мне предстояло вновь вернуться к преподаванию, чего теперь мне хотелось меньше всего. Нет, я всегда любил свою работу в университете, но по истечению времени все это казалось мне таким приземленным.

Если честно, раньше я и сам до конца не верил в то, что мне удастся осуществить задуманное, ведь в какой-то степени этот проект был для меня не более чем красивой мечтой, но вид каттеджного городка в мой первый вечер на м83 и, конечно, появление Отем изменили многое в моей жизни. В итоге же события последних месяцев оказались для меня гораздо важней чего бы то ни было.

Поглощенный вихрем собственных мыслей, я чуть было не пропустил нужную остановку, но вовремя увидев в окне поезда хорошо знакомую крышу своего дома, в последний момент успел проскочить в закрывающуюся дверь.

Двадцати пяти этажный дом, в котором я снимал квартиру, был маловат для центра города, но довольно заметным для спального района, где он и находился. В основном, здесь преобладали каскадные пятиэтажки, а кое-где и вовсе можно было встретить двухъярусные домики. Спустившись вниз по эскалатору, я вышел из здания &lt;метро&gt;, и, быстрым шагом перейдя улицу, оказался около своего дома.

Я поднял голову, стараясь разглядеть свои окна, но зимнее солнце этим утром ослепляло, не позволяя мне что-либо увидеть. Протяжно вздохнув, я вошел в здание. На пути мне встретились соседские ребятишки, с радостными криками пересекающие холл. И вот вскоре я стоял на пороге своего дома.

Скинув пальто, я осмотрелся по сторонам. Квартира, которую я арендовал, находилась на последнем этаже и больше походила на просторную студию. Обычно, в таких не задерживались надолго, а скорей перебивались некоторое время в ожидании возможности обзавестись собственным семьей и домом. Но меня это место вполне устраивало. За пятнадцать лет, прожитых здесь, я так и не успел полностью обставить квартиру. Свободного места в ней было хоть отбавляй. Окна не такие большие как хотелось бы, но проникающего из них света было достаточно, дабы каждое утро стряхивать с моей скромной обители мрачность ночи.

Под одним из окон стояло сенсорное фортепиано. Я приобрел его со своего первого учительского оклада, и отдавал долг больше года, хотя этот инструмент так и не смог сравниться с дедовским роялем, чье звучание я помнил еще с малых лет. Всю стену напротив фортепиано занимал огромный снимок  звездного неба, изображающий мои разработки последних двадцати лет, а под ним находилась невысокая двуспальная кровать. Импровизированной кухней мне служили небольшая микроволновая печь и электрический чайник, стоящие на выдвижном столике в другом углу комнаты. Чаще всего я обедал вне дома, так что остальные предметы бытовой техники мне попросту не были нужны.

Около постели стояло мое любимое удобнейшее кресло из красной кожи, что было приставлено к рабочему столу средних размеров. Умостившись в кресле, и перекинув ноги через подлокотник, я нажал единственную кнопку на столе, и тот моментально осветился. Спустя каких-то двадцать минут царивший здесь прежде порядок превратился в совершенный хаос.

Осознав это, я улыбнулся: беспорядок беспорядком, главное он не мешал мне работать.

Поначалу гора скопившихся бумаг казалась мне бесконечной, но к обеду мне, все же, удалось разобрать большую их часть. В любом случае, мне предстояло отчитать еще семь лекций, а заодно подыскать себе постоянную замену, на что этого месяца вполне должно было хватить.

Копаясь в учебных планах, я неожиданно для самого себя понял, что возвращение на время к старой работе оказалось для меня приятным занятием. Единственным минусом было отсутствие каких-либо возможностей общения с Отем. Как и на всех дочерних компаниях ЭСКМО, на м83 настрого запрещалась любая связь с внешним миром. Не считая, конечно, всяческих переговоров, относящихся к рабочим моментам. И как не пытался я сосредоточиться на составлении учебного плана, в итоге мои мысли все равно возвращались к Отем, и я чувствовал, как непреодолимо сильно тоскую по ней.

Наконец, к вечеру того же дня короткий курс лекций был подготовлен, и, решив, что пора перекусить, я вышел из квартиры.

\*

Следующим моим шагом было хорошенько выспаться перед наступающим насыщенным днем. Мне предстояло оббежать чуть ли не половину города, но потому как по возвращении домой я только и делал, что отсиживался за столом, я был вовсе не против такой небольшой прогулки.

По поводу небольшой я, конечно, погорячился, потому что уже через четыре часа после пробуждения чувствовал себя так, словно прошел за это время какой-то усиленный курс военной подготовки, предназначенный для службы на м83.

Наконец, я добрался и до Университета. Оставив машину на преподавательской парковке, я поднимался по ступеням залитого солнцем крыльца здания. Но не успел я пройти и пару шагов в сторону центрального входа, как меня тут же окликнули по имени.

– Профессор Рок?

Я обернулся. Навстречу мне спешил Курт Саймонс, второкурсник. Я хорошо помнил этого парнишку, и на то было как минимум две причины.

Во-первых, он однозначно был самым заинтересованным в астрономии студентом на всем курсе, если не сказать факультете. Курт, как губка, впитывал каждое слово, сказанное мной во время лекций, (будь это давняя теория, или незначительный факт) но при этом никогда не терял интереса к новым знаниям. Именно благодаря таким ребятам как Курт мне всегда нравилось преподавать: видеть этот неподдельный интерес в глазах подростка, делиться собственными знаниями и соображениями на ту или иную тему.

Во-вторых, Курт уже второй год занимался собственным научным проектом, и в даный момент тот был полностью сконцентрирован на Луне. Хотя на первый взгляд тема его работы могла показаться шуточной, парень был настроен весьма серьезно. Еще до моего отъезда, он еженедельно брал консультации у нескольких преподавателей, включая меня. И пускай я, как и подавляющее большинство его окружения, не был сторонником этой лишь начинавшей вырисовываться идеи, не могу сказать, что меня она не интересовала. Ведь наше внимание всегда получают в первую очередь те, кто решается пойти против течения.

К тому же, я никогда не отметал что-то лишь потому, что другим оно могло показаться глупым, и, в каком-то смысле, допускал абсолютно во все.

Тема работ Курта была широко известна благодаря средствам массовой информации, но уже давно никак не соприкасалась с наукой — «Внеземные расы. Их жизнь в и вне нашей солнечной системы.» Невероятно глупая и устаревшая затея — так думали многие, но уверенность Курта в собственных домыслах мне нравилась. Это вызывало уважение.

Дело было в том, что в наши дни вездесущих технологических исследований уже давным-давно никто всерьез не допускал самих даже мыслей и существовании подобных вещей. Они были, скорей, занимательной сказкой, но не более.

Курт же так не считал. Нет, он не был из числа помешанных, но день за днем проводил в исследовании всевозможной информации и поисках нужных ему фактов.

– Профессор Рок? – поднявшись, Курт отдышался и широко улыбнулся. – Вы вернулись.

– Здравствуй, Курт. Совсем ненадолго.

– Серьезно?

Я кивнул. Касалось, он был немного расстроен.

– Очень жаль слышать это. Профессор Рок, я ждал Вас с самого утра. Миссис Пиллсберри сказала, что Вы сегодня возвращаетесь.

– На самом деле, преподавать я начну только со среды, – вставил я, – а сейчас просто зашел уладить некоторые организационные вопросы.

– Так вот я хотел спросить, раз уж Вы здесь, – продолжал он, – нельзя ли мне еще немного посоветоваться с Вами?

Я вздохнул: на сегодня дел и без того было хоть отбавляй, да и утренней бодрости во мне уже заметно поубавилось.

– Прости, Курт, но мне еще очень многое предстоит сделать, боюсь, что у меня просто нет времени.

Он тут же поник, а я просто не мог позволить себе разочаровать ребенка, следовавшего за своей мечтой. В каком-то смысле, он напоминал мне самого себя в его возрасте.

– Послушай, а почему бы тебе просто не прислать свои вопросы на мой рабочий имэйл? – предложил я. – Я прочту их ближе к ночи, так что утром уже получишь ответ.

Курт слегка улыбнулся.

– Хорошо бы, профессор Рок, но я стараюсь избегать подобного вида общения.

Видимо, мне так и не удалось скрыть своего удивления, потому что, завидев мое выражение лица, он тут же расхохотался и поспешил добавить:

– Дело в том, что мне немного некомфортно вести любые переписки. Я не чувствую собеседника, не могу воспринимать его всерьез таким образом. Не знаю, как это объяснить, ведь я даже в социальных сетях не зарегистрирован. В общем, мне гораздо легче дается живое общение, поэтому, если Вы не против, я лучше уж подожду, пока Вы освободитесь, и подойду... в следующий понедельник, например.

Ошеломленный его тирадой, я не мог не улыбнуться, и немного пораскинув мозгами, решил все таки сдаться.

– Ладно, &lt; &gt;, жду тебя через десять минут в своем кабинете, – произнес я. – И захвати кофе, день обещает быть долгим.

\*

Без сомнений, объем новостных сводок, которые я запросила неделей ранее, должен был оказаться немалым, но я, все же, с ужасом наблюдала за тем, как их стопка беспрестанно увеличивалась на моем рабочем столе. Гастингс направил файлы сразу после обеда и мне больше часа пришлось ждать окончания разархивации. В конце концов, бумажек накопилось столько, что распредели я их поровну между всеми своими подчиненными, все равно нам не хватило бы и года, дабы их прочесть.

К счастью, это вовсе не было обязательным. Достаточно было просто воспользоваться поиском, правильно подобрав ключевые слова. Что ж, я использовала все возможные варианты, и так и не нашла ни одной разоблачающей статьи или хотя бы заметки, связанных с изменениями подземного давления, толчками, исчезновением Метьюза и прочим. Даже обиходное слова «опасность» не привело меня к особым результатам.

Покончив со всем этим, я включила успевшую мне так полюбиться «Maybe I Missed The Point», и, прикрыв глаза, вытянулась в своей постели. Все оказалось именно так, как я и предполагала: никто на Земле и понятия не имел о происходящем.

\*  
– Сириус? – позвала я, войдя в соседний от моего кабинет.

За дверью стояла кромешная темнота, но я знала, что старпом был внутри.

– Я здесь, – раздался ответ. – Проходи, только не включай свет.

Голос доносился с конца кабинета, и, закрыв за собой дверь, я на ощупь двинулась в его сторону. Глаза, привыкшие видеть в полумраке, быстро освоились в темноте, и вскоре я увидела силуэт Сириуса. Облокотившись о стол, он стоял со сложенными на груди руками.

– Что ты делаешь?

Я опустилась на диван, приставленный к стене напротив.

– Размышляю, – ответил Сириус, и я невольно улыбнулась.

Мне вспомнилась его юношеская привычка бегло говорить, да так, что не всегда можно было разобрать и половину сказанного. Теперь же его слова звучали столь однообразно и монотонно, словно старпом намеренно старался протянуть каждое из них. Так сравнительно немного времени прошло с той поры, а передо мной уже был совершенно другой человек.

Иногда я все же видела Сириуса прежним. В такие минуты я ощущала приятную легкую тоску по минувшим дням, как если ты случайно натыкаешься на давно забытую песню, что когда-то любил. Такие чувства не проходят, они лишь притупляются, чтоб позже возникнуть с новой силой.

– Почему в темноте?

– Так лучше думается, - произнес Сириус, а после довольно продолжительной паузы добавил: – Все эти парни с темной стороны так много времени проводят во мраке. Мне показалось, что если постоять здесь пару часов с выключенным светом, я смогу почувствовать себя одним из них, и тогда, возможно, мне удастся понять, что же все-таки произошло с Джеком там, у тринадцатого. Глупо, должно быть.

Я не видела его лица, но чувствовала странную уверенность в том, что сейчас оно выражало куда больше эмоций, чем обычно.

– Совсем не глупо. Тебя мучает случившееся здесь, к тому же Метьюз был тебе другом, так что твое желание разобраться вполне нормально.

– Но я так ни к чему и не пришел...

Он зажег небольшую подвесную лампу у дивана, и, прищурившись, сел рядом со мной.

– Я тоже все время думаю об этом, а отсутствие Старлайта буквально заставило меня полностью сосредоточиться на чертовых толчках. Даже поспать толком не удается. Но, знаешь, это правильно. Я имею ввиду, я ведь капитан и все-таки отвечаю за жизни этих людей. Не думаю, что Хатс стал бы вести себя иначе.

В тусклом свете лампы я заметила тень улыбки, проскользнувшую на лице Сириуса.

– Старина Хатс, он был примером для нас.

Я подбадривающе ткнула его локтем под бок.

– Еще каким.

– Так что ты хотела сказать мне, Отем? – вспомнил Сириус.

Я рассказала ему о ситуации с новостями и тем, какой результат дали мои поиски

– С моей стороны было крайне наивно полагать, что дела могут быть иначе, - закончила я.

– Да уж, - вздохнул старпом. – Мы все еще не можем быть на 100% уверены во вмешательстве третей стороны, но люди должны знать о возможности подстерегающей их опасности. Пускай пока она и таится на темной стороне.

– Знай мы, с чем имеем дело, было бы гораздо проще. Но у меня по-прежнему нет ни одной подходящей догадки.

Выждав еще пару минут, я продолжила.

– В последнее время я все чаще вспоминаю ту историю с «Алым Орионом», – после небольшой паузы произнесла я.

– Такое сложно забыть, – тут же нашелся Сириус.

– Да, но мне постоянно не дает покоя главный вопрос: зачем?

– Отем, они пираты. Для таких людей не существует никаких «зачем».

– Но на все должна быть своя причина.

Старпом вздохнул.

– Послушай, – продолжала я, – они не хотели просто захватить коттеджный городок. Штатские лишь играли роль живого щита. В ту ночь в их планы входило нечто большее – захватить Луну.

– Что? – Сириус взглянул на меня с недоверием. – Ты, должно быть, шутишь.

– Вовсе нет. Я входила в наряд разведки, если ты не забыл.

– Да…

– Мне многое удалось услышать, прежде чем открыли огонь.

Закончив это предложение, я в ожидании посмотрела на старпома. Сейчас он выглядел еще более обескураженным, чем когда-либо. Складка морщин, появившаяся на его лбу за годы службы на м83, бесследно исчезла. Сириус даже не хмурился – таким я давно его не видела.

– Но для чего это было нужно? – тихо произнес он.

Я подняла брови.

– Ну, а я тебе о чем говорю?

Старпом молчал.

– Знаешь, иногда мне жаль, что я стала капитаном так поздно, – призналась я.

– Поздно? – переспросил Сириус. – Ты хотела сказать «рано»? Тебе ведь еще даже тридцати нет.

Я слегка улыбнулась.

– Ты прав. Наверное, я просто родилась слишком поздно. Я имею ввиду, что хотела бы лично поговорить с теми внезаконниками.

– И что бы изменилось, будь ты лет на десять старше?

– Возможно, мне бы удалось узнать ответ на свой вопрос. Выменять его на их жизни, например. Я уже говорила, что и по сей день не перестаю думать о той ночи. Став капитаном, я просмотрела личные дела всего экипажа «Ориона». Все до одного оказались вполне благочестивыми гражданами. Это странно, ты не находишь?

– Такие люди способны до последнего скрываться под маской чести, – ответил Сириус.

– Ты звучишь как сенатор Куинн.

Он пожал плечами.

– Но это правда, – протянул Сириус.

– Даже не знаю, – ответила я, – Все эти мысли не дают мне покоя.

– Ну, если сейчас тут и впрямь имеет место быть подобное вмешательство, то это определенно точно не пираты, – уверенно произнес Сириус.

– Согласна, - кивнула я. – Это было бы совсем нелогично. Зачем им может понадобиться бурильщик? Да и сроки не те. Прошло уже достаточно времени для них, чтобы заявить о себе.

– А мы ведь обыскали каждый сантиметр.

– Тогда что это?

Сириус не ответил. Просто потому что ни один из нас больше не знал что сказать.