---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---


# Долина Снежных Холмов {#18}

Странные ощущения окутали меня при взгляде на старую семейную усадьбу. Я сошел с конечной остановки скоростного метро около часа назад, и все это время шел по некогда цветущим окрестностям трассы шестьдесят шесть. Разумней было бы воспользоваться взятым в прокат автомобилем, но еще вчера на меня накатило внезапное чувство ностальгии, так что очень хотелось пройти этот путь именно так, как когда-то мне приходилось делать это бесчисленное количество раз.

Долина Снежных Холмов находится в тридцати трех километрах к северу от центра Денали. Многие годы назад это место было восхитительным заповедником, но, невзирая на настигнувшее ее опустошение, долина по-прежнему входит в число моих любимейших мест на планете.

Время близилось к полудню, а я стоял на обочине дороги, где и брала свое начало долина. Вдалеке за несколькими заброшенными домами виднелась хорошо знакомая крыша родительской усадьбы. Она была расположена у самого подножья холма. Глядя на верхушку своего домика, я подумал, что чего-то определенно не хватает, хотя вроде как все было на месте. Тогда я закрыл глаза, вернулся мыслями в прошлое, открыл их... и тут же понял, в чем дело. С левой стороны крыши была каминная труба, из недр которой в холода многие годы подряд валил дым. Теперь же, без этой совсем маленькой детали, родной дом уже не казался мне таким уютным. А посему, достигнув усадьбы, я первым делом решил развести пламя в камине. И когда я сделал это и вновь взглянул на усадьбу с улицы, мне словно стало гораздо легче дышать.

Закончив все дела в городе, я вернулся к тому, с чего начинал. Вскоре мне предстояло отправиться на м83, начать там новый проект, а вместе с тем — и новую жизнь, и я, конечно, был рад этому, но сейчас у меня все еще оставалось пять дней, которые я мог и хотел провести именно здесь. Ведь, по сути, больше ничто не удерживало меня на Земле, кроме как эта усадьба, и воспоминания, связанные с ней. Но последние всегда будут храниться в моем сердце, а там, далеко за звездами, меня ждала Отем и дело всей моей жизни, оттого выбор совсем не был сложным. Однако, прежде чем вновь покинуть Землю, у меня оставалось еще одно дельце.

Улыбнувшись этим мыслям, я вернулся обратно в усадьбу. Снаружи стоял тихий, но морозный зимний вечер, а в камине маняще потрескивали угольки, когда, развалившись на мягком диване, я допивал бутылку красного вина 25.. года. В этот раз я не стал обращаться к любимым альбомам — музыки вокруг было вполне достаточно.

Чуть позже за окном выпал снег и вся долина окрасилась в белые тона, что полностью соответствовало ее названию.

В соседней комнате, когда-то служившей моей семье гостиной, по-прежнему стоял дедовский рояль. Вся его поверхность была укрыта толстенным слоем пыли, и я еще несколько раз чихнул, прежде чем удалось привести все в порядок.

И вот, я, наконец, смог ощутить всю красоту звучания знакомых с детства мелодий. Ностальгия — приятное чувство, особенно когда ты находишься в таком месте как это, - я взглянул на висевшую над пианино картину, - но нужно двигаться дальше, к лавандовым долинам и выше. Скоро я покину долину снежных холмов, прихватив с собой несколько пластинок и эту фотографию. Возможно, что-то и забуду, но о главной вещи я все время помнил. Сейчас она лежала всего в нескольких сантиметрах от моей руки и уже многие годы ждала возможности увидеть мир.