---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Ледяные озера {#19}

Я уже несколько часов обнимал Отем, будучи не в силах выпустить ее из своих объятий. Ее глаза светились любовью, а длинные волосы, раскинувшиеся на подушке, напоминали морские волны. Как же я соскучился.

Месяц, проведенных на Земле, обернулся для меня вечностью, но я ни на минуту не переставал думать об Отем. Все это время мое сердце оставалось здесь, на м83, а эта разлука только помогла мне убедиться в том, что я и так знал с самой нашей встречи. Я хотел быть с Отем. Всегда. Не важно, на какой из планет или звезд нам пришлось бы жить — ради нее я был готов облететь целую Вселенную. Одного взгляда ее синих глаз оказалось достаточно, дабы понять это.

Но дело было вовсе не в ее внешности или волшебстве, окружавшем нас. Я знал, что если бы встретил Отем при совершенно иных обстоятельствах, то непременно полюбил бы ее так же крепко и с первого взгляда. Все заключалось в душе и том светлом неописуемом чувстве, которое мне каждый раз навевали одни лишь мысли о ней — такие моменты не исчезают. Они вечны.

– Как там твоя усадьба? – спросила Отем.

Она лежала рядом со мной, наполовину укрывшись тонким одеялом. Я провел рукой по ее снежной коже.

– Прекрасно, - ответил я. – Дожидается тебя.

Отем улыбнулась.

– А как дела с твоими переживаниями? - вспомнил я. – Удалось узнать что-нибудь новое?

– Совсем немного, – она потянулась. – Я расскажу тебе обо всем, но только не сейчас. Это может немного подождать, потому что я уже устала тосковать по тебе.

После этих слов Отем прижалась ко мне.

– А теперь иди ко мне, – улыбаясь, прошептал я, и поцеловал свою любимую.

\*

Мне всегда нравились Рэйдиохед. За восемь неполных лет, проведенных на темной стороне Луны, я слушал их музыку изо дня в день, бесконечное количество раз, но что еще хуже, чаще всего я просто чувствовал себя живущим из этих унылых песен.

Ложка молотого кофе, еще одна сухих сливок, три кубика сахара — и можно начинать день. Хотя какой же это день? Я живу и работаю в кромешной тьме. Существую словно под тесным куполом. И это не было метафорой. После давнишней истерики старика Терренса нам не разрешалось покидать пределы темной стороны на протяжении всего рабочего времени. Я имею ввиду, бурильщикам. Так что все мы здесь бродили под этим колпаком одиночества.

Мой контракт был заключен на десять лет, большую часть из которых я уже отработал. Оставалось всего ничего. В другой ситуации я бы, наверное, ни за что не согласился взяться за подобную работу, но в тот момент обстоятельства буквально вынудили меня согласиться. Говоря об обстоятельствах, я, конечно же, имею ввиду женщину. Все дело в ней, всегда в ней. Лия, моя белокурая девчушка, ушла, а я просто не смог вынести это предательство. Удар был слишком болезненным и попал прямо в сердце.

То утро оказалось худшим из всего, что мне приходилось пережить за свои неполные сорок лет. Хотелось просто исчезнуть, раствориться и стать всеми забытым. Тогда-то мне и попалось на глаза объявление, гласившее о наборе команды на м83. Конечно, о бурении в нем не было ни слова, как и о самой базе. Говорились только то, что нужны сотрудники для непыльной работы далеко от дома и сроком на продолжительное время. Меня это вполне устраивало.

До последнего момента я не имел ни малейшего понятия о том, где буду находиться в ближайшие десять лет своей жизни. Мне представлялась безымянная пустыня или тихий необитаемый остров, пускай таких уже и не осталось на свете. Как бы там не сложилось, я надеялся провести эти годы с пользой, а самое важное – я был уверен, что избавлюсь от этой боли и сам изменюсь до неузнаваемости. Но я не смог. Время здесь продолжало стоять на месте, а я все так же оставался тем самым человеком с разбитым сердцем и покрасневшими от тоски глазами, одиноко стоявшем на крыльце своего дома пасмурным ноябрьским утром в надежде на то, что она вернется, обязательно вернется ко мне.

Компания ежедневно выплачивала мне кругленькую сумму, но на Луне деньги были мне не к чему. Возможно, это было единственной причиной, по которой мне еще могло нравиться это место.

Я дремал, полулежа на своем рабочем месте с закинутыми на стол ногами. В последнее время я частенько позволял себе этот грешок. Не знаю, почему. Такое странное состояние вновь окутало меня, когда ты вроде как и не бодрствуешь, но при этом слышишь все, что происходит вокруг, и отлично понимаешь, где находишься.

Вскоре я открыл глаза, но продолжал лежать неподвижно. Так, словно еще и не просыпался. В небольшом окошке над моей головой блестели звезды. Удивившись про себя, я заметил, что грусть рэйдиохедовских мелодий куда-то исчезла. На смену ей пришел бессмертный альбом Джонни Кеша – «Среди звезд». Всегда поражался его умению писать музыку с того света.

Я ухмыльнулся. Хотя я и не мог вспомнить, как и когда успел сменить плэйлист, перемена эта была очень кстати: мое настроение тут же улучшилось. Музыка и впрямь способна исцелять.

«Еще немного, – подумал я, не сводя глаз с клочка открывающегося мне звездного неба, – и заживу полной жизнью».

Спустя какое-то время в колонках заскрипели Джой Дивижн, а прямо перед моими глазами проскользнула падающая звезда.

«Надо же, мне виден такой крошечный отрезок неба, а звезду эту заметил именно я…» – я улыбнулся про себя.

Но мне нечего было загадывать.

Хотя нет, ошибаюсь. Больше всего на свете я хотел быть счастливым.

С такими мыслями я сомкнул глаза и вновь погрузился в сон, на этот раз более крепкий. Мне виделась Лия, тем злосчастным утром сидевшая у изголовья моей кровати. Но здесь утро не было таковым и девушка не спешила исчезать из моего дома, а вместе с тем и моей жизни. Сейчас Лия лишь сидела около меня и ласково улыбалась. В руках она держала белую фарфоровую чашку, из которой исходил пар. Скорей всего, зеленый чай – ее любимый напиток по утрам.

Однако, привстав, я учуял в воздухе знакомый приторный запах, какой вряд ли стал бы исходить от чая.

– Что это? – спросил я, указав на чашку.

– Глинтвейн, – спокойно ответила Лия, и игриво накрутила на палец прядь золотых волос.

Меня сводили с ума ее локоны, и Лия об этом знала.

– Не рановато ли для спиртного? – вновь спросил я.

Сам я на дух не выносил глинтвейн, и сейчас удивлялся тому, как Лия вообще могла держать его в руках.

Услышав мой вопрос, Лия улыбнулась еще шире. До невозможности шире, и постепенно ее улыбка превратилась в странную гримасу, от которой по моей коже пробежала дрожь.

Девушка покачала головой.

– Нет, я праздную, – весело говорила она. – И ты тоже празднуешь. Посмотри.

Лия подняла руку и направила свой указательный палец в мою сторону. Проследив за ним взглядом, я неожиданно для самого себя заметил, что держу в руках такую же чашку с глинтвейном. После этого я тут же почувствовал тошнотворно-сладкий привкус напитка у себя во рту.

– Гляди язык не обожги, – беззаботно сказала Лия. – Я его только пять минут как с плиты сняла, так что он должен быть еще очень…

– Постой-постой, – перебил ее я. – А что именно мы празднуем?

Внутри меня таилось странное чувство тревоги. Где-то глубоко в душе я совершенно не желал задавать этот вопрос. И все же я уже спросил.

– Как это что? Твое окончание работы на темной стороне, глупенький.

– Но, я ведь еще не отработал оговоренного срока, – поспешил разубедить ее я. – По контракту мне полагается пробыть здесь еще два года.

– К черту контракт, – ответила Лия. Теперь ее улыбка была настолько широкой, что больше походила на оскал. – Ты только послушай это.

Я уже хотел спросить, о чем это она говорит, но секунду спустя тоже услышал. Оглушительный гул, нарастающий с каждой минутой, раздавался из всех уголков комнаты, подступая ко мне все ближе и ближе.

– Что это такое?! – крикнул я.

– Фанфары, – с улыбкой ответила Лия. – Теперь ты свободен.

Я открыл глаза и в замешательстве посмотрел по сторонам. Я по-прежнему был на своем месте в тринадцатом. Сон как рукой сняло, но в голове все еще раздавался тот пугающий гул.

Прошло несколько секунд, а шум никуда не уходил. С замершим сердцем я обернулся и понял, что этот гул был вовсе не в моей голове, он исходил от машинной панели позади меня. Центральная кнопка, на которую я до этого не обращал внимания, пылала красным светом, а стрелка счетчика, отвечающего за давление под землей, с неистовой силой молотилась о стеклянный корпус.

Я подсочил со стула и, спотыкаясь, помчался к панели: происходящее вокруг выглядело весьма пугающе.

\*

Следующей четвертью Отем показала мне Озерный край – восхитительное место на светлой стороне Луны, между Циановым лесом и Звездной гаванью, находящееся ближе всего к базе м83. Сегодня была необычная ночь, ночь звездопадов, а каждый, кому хоть раз посчастливилось побывать здесь, знал, что лучше всего наблюдать за звездопадами, стоя на одном из снежных холмов Озерного края. Именно по этой причине я и выбрал сегодняшнюю ночь для того, чтоб сделать Отем предложение.

Оставив свои луноходы около первого попавшегося на нашем пути холма, мы получше запахнули свои пальто, (ведь здесь было довольно морозно) и, взявшись за руки, зашагали в обход снежного склона. Он оказался гораздо больше, чем мне виделось издали, и нам понадобилось около двадцати минут, дабы полностью обойти склон. Когда, наконец, удалось сделать это, моему взгляду открылась невиданная доселе красота снежного края. Словно изображенная на холсте умелого художника, перед нами раскинулась долина, густо укрытая снежным покровом, которую со всех сторон окружали холмы, визуально отгораживая ее от внешнего мира. В центре долины виднелось множество озер. Все они были разной формы и размера, но самым очаровательным оказались подснежники, то тут, то там выглядывающие на поверхность.

– Остановимся здесь? – предложил я.

Мы пересекли уже практически половину долины, и сейчас были в центре застывшего озера, по краям которого находилось несколько высоких резных лавочек из черного метала.

– Давай лучше присядем в беседке, – ответила Отем.

– Беседке? – переспросил я.

Она указала мне на следующее озеро, имевшее тонкую форму полумесяца. Я присмотрелся, и увидел в центре него небольшую утонченную беседку, выполненную из витиеватых черных прутьев стали.

– Конечно, – улыбнулся я, и мы продолжили свой путь.

Шагая по толстому слою льда, я слушал рассказ Отем о газетных выдержках, добытых для нее каким-то Гастингсом, но, признаться, был невнимателен. Все мои мысли были заняты другим, ведь несмотря на то что я всеми силами старался взять себя в руки, тогда как волнение все сильней охватывало меня с каждой минутой неведенья.

«В конце концов, главное – спросить», – решил я.

– Как хорошо, что ты вернулся, Старлайт, – вдруг произнесла Отем.

Отвлекшись от своих мыслей, я увидел, что мы уже пришли.

– Иначе и быть не могло, – ласково ответил я.

Мы вошли в беседку, и лишь тогда я заметил, что верх у нее был открытым. Должно быть, это было сделано для наблюдения за звездопадами.

Отем откинулась на перила беседки и взглянула на меня.

– В твое отсутствие я много думала о нас, – начала она. – О тебе. Я жалела ,что перед твоим отъездом так и не сказала самого важного. С тобой я забываю обо всех тревогах. Наверное, это не совсем правильно, учитывая то, какую роль я играю на м83, но сейчас это абсолютно неважно, как неважно и все остальное. Я люблю тебя, Старлайт, и это единственное, что имеет значение, потому что я еще никогда не была так счастлива, как в этот самый момент.

Я улыбнулся и прижал ее к себе.

– Я и сам никогда прежде не был так счастлив, – искренне произнес я.

В ее глазах, отражаясь, сияли звезды.

– Смотри, началось, – улыбнулась Отем.

Подняв голову, я увидел, как с невероятной скоростью десятки звезд проскальзывают по небесному полотну, одна за другой исчезая в темноте. Но стило им лишь померкнуть, тут же появлялись другие. Звездопад начался. Я затаил дыхание: настолько прекрасной оказалась эта картина. Падающие звезды были повсюду. Они отражались и в ледяной поверхности озер, отчего создавалось впечатление, что мы в открытом космосе.

«Вот он, идеальный момент», – подумал я.

Мои пальцы нашли во внутреннем кармане пальто объемное кольцо, когда-то давно принадлежащее матери моего отца. Оно было сделано из белого золота, а посередине кольца сиял прекрасный темно синий камень, название которого я уже не помнил.

– Отем, дорогая моя, – произнес я, и взял ее тонкую белую ручку в свои ладони.

Девушка отвлеклась от звездопада и умиротворенно посмотрела на меня.

Я думал об этом моменте на протяжении всего последнего месяца, но сейчас все мысли и речи, что я не раз прокручивал в своей голове, куда-то исчезли, и мне не оставалось ничего, как просто спросить:

– Ты выйдешь за меня?

Она молчала всего мгновенье, но и оно показалось мне вечностью.

– Значит, Исландия? – с улыбкой спросила Отем.

Я надел кольцо на ее палец и, улыбаясь в ответ, поцеловал свою невесту.

– Я так счастлив, что готов умереть.

\*

Вокруг нас было спокойно и тихо. Никакого ветра. Звездопад прекратился около часа назад. Обычно они длились пару минут, не более, но это всегда стоило того, чтобы посмотреть. Сегодняшний же звездопад стал особенным для меня, и я навсегда запомню его.

Набродившись по сугробам, мы оба изрядно вымотались и теперь уставшие направлялись обратно. Старлайт шел рядом со мной. Его лицо по-прежнему освещала та самая улыбка, в которую я была так сильно влюблена.

Вдруг где-то вдалеке раздался гул, эхом разносясь по окрестностям. Земля под ногами задрожала, и я бы непременно упала, если бы Старлайт вовремя не подхватил меня.

– Милая, ты в порядке?

Не выпуская моей руки, он встревожено смотрел на меня.

– Кажется, да, – я ошарашено оглянулась по сторонам, пытаясь понять, что только что произошло.

Местами земля укрылась трещинами, а кое-где даже отделилась от поверхности и теперь нависла над ней бесформенными пластами, напоминавшими края рваной раны. Сейчас окружающий нас пейзаж уже не выглядел столь прекрасным, как каких-то десять секунд назад. Он попросту казался мне фальшивкой: из-под сдвинувшихся с места снежных пластин пробивались стабилизаторы температуры. Их работа была нарушена появлением толчков, и теперь снег постепенно начинал таять. Я знала, что уже через час он и вовсе исчезнет под лучами искусственного освещения, которое, к счастью, не пострадало. Я подняла голову, желая убедиться в этом наверняка, но тут же с ужасом вскрикнула. Прямо в лежавшем над нами пространстве образовалась немыслимых размеров трещина. Она тянулась от самых лавандовых полей – той части, где брал свое начало колпак, наполненный синим воздухом, – и заканчивалась высоко над ледяными озерами.

– Отем? – еще сильней встревожился Старлайт.

– Взгляни в небо, – не сводя глаз с трещины, произнесла я. – Баланс воздуха нарушен.

– Вижу…

Я крепче сжала его руку.

– Пойдем. Нужно скорей вернуться на базу. Находится здесь небезопасно.

Он согласился.

– Но что это было? – все спрашивал Старлайт, когда мы быстрой походкой направлялись к луноходам. Гуляя, мы зашли довольно-таки далеко, и до них оставалось еще минут тридцать ходьбы.

– Я не знаю, Стар, – говорила я, – но вскоре обязательно выясню это.

Я вдруг остановилась.

– В чем дело? – удивился Старлайт.

– Нужно объявить военную тревогу, – решила я.

– Давай скорей.

Быстрее чем когда-либо, я запустила свой браслет, и вот уже вызывала Сириуса, но сигнал внезапно прервался. Выругавшись, я предприняла еще одну попытку. На этот раз мне повезло. Пускай и с помехами, но мне удалось дозвониться…

– Сенатор Куинн? – удивилась я, увидев его лицо вместо ожидаемого лица Сириуса. – Как это вышло? – я тут же одернула себя: неподходящее я время выбрала для расспросов. – Я собираюсь объявить тревогу. Код красный.

– Нет нужды объявлять красный код, капитан Раст, – ответил сенатор со всей присущей ему невозмутимостью, да так спокойно, что я просто онемела от удивления и негодования, одновременно охвативших меня.

– Что?!

– На другой стороне Луны сейчас проходят учения, – размеренно говорил сенатор. – То, что Вы могли только что услышать – это всего лишь их результат, не более.

– Я не только услышала что-то… – повысив голос, ответила я, но не успела закончить фразу. Куинн тут же перебил меня.

– Вы одна сейчас? – спросил он.

– Да, одна, – соврала я.

– Замечательно, – сказал сенатор, и хотя я видела мало замечательного в этой ситуации, я позволила ему закончить фразу. – Возвращайтесь в штаб. И повторяю: не поднимайте военную тревогу.

Он отключился.

– Мудила гребаный! – вскипела я, и вновь попыталась дозвониться Сириусу. – Черт возьми, связи нет. Такое чувство, что ее блокируют с самого штаба.

Земля задрожала еще раз. Теперь толчок раздался уже гораздо ближе к нам, и по небу поползла очередная трещина. И без того приглушенный свет постепенно начинал гаснуть.

«Хорошо, хоть звезды настоящие», – мелькнуло в голове.

Старлайт потащил меня за руку.

– Быстрее, Отем, нужно уходить.

Мы не шли, а уже практически бежали, приближаясь к снежному склону, за которым были оставлены наши луноходы. Рисковать, ступая по озерному льду, мы не стали. Без стабилизатора температуры он мог треснуть в любую минуту, так что мы были вынуждены идти под холмами, по самому краю берега.

За спиной раздавались все новые удары, и удержать равновесие, не упав наземь, было весьма сложно. Вокруг становилось заметно холодней, а освещение уже почти померкло. Я видела перед собой небольшие клубы пара, появляющиеся вместе с моим дыханием. Времени идти в обход практически не оставалось. Нужно было забраться на холм и очень осторожно спуститься по нему к луноходам.

Меня настигло странное чувство, словно я нахожусь на темной стороне Луны и, задыхаясь, бегу по ее ледяной поверхности.

Забираться вверх по склону было нелегко. Приходилось выискивать в полумраке отслоившиеся от него куски поверхности и подниматься дальше, цепляясь за них. Один из таких пластов оказался слишком маленьким и уже почти отошел от земли. Взявшись за него, я чуть не завалилась назад. К счастью, Старлайт поднялся на склон первым, и успел ухватить мою руку, тем самым предотвратив падение. Одним рывком он поднял меня наверх, и вот мы оба стояли на снежном возвышении. Луноходы оставались внизу, до них было еще метров я десять.

Отдышавшись, я взглянула на местность, оставленную позади. Многое было разрушено, а в самом начале восьмого участка, прямиком на его поверхности, образовалась огромных размеров дыра.

Новый удар пришелся совсем близко. Это сбило нас с ног. Старлайт тут же подскочил и помог мне подняться. Должно быть, при падении он ушибся: я увидела алые подтеки около его висков.

Земля продолжала трястись и содрогаться. Мы вновь и вновь падали, не будучи в состоянии спуститься вниз. Тогда я услышала доносящийся из темноты шум, словно кто-то одновременно разбил за нашими спинами тысячи зеркал. Я поняла, что этот треск исходил от озер.

Я вновь взглянула вниз в сторону луноходов.

– Будем прыгать! – крикнула я, стараясь перебить продолжающийся шум.

– Черт возьми, – чуть слышно произнес Старлайт. – Курт не ошибался…

Я обернулась. Словно завороженный, Старлайт стоял у другого края холма и внимательно смотрел на что-то внизу. Еще мгновение, и мне тоже открылось _это_. Ужас сковал меня, когда я увидела десятки землистых щупалец, появившихся со средины озера. Они были гигантских размеров и с невероятной скоростью метались из стороны в сторону, уничтожая все на своем пути. Эти чудовищные существа крушили саму долину и деревья, растущие в ней, утаскивая их обломки под землю.

Пазлы в моей голове сложились, и тогда я все поняла, но все вокруг происходило так быстро, что мне едва ли удавалось дышать.

– Беги, Отем! – раздался голос Старлайта.

Он оттолкнул меня с того места, которое спустя долю секунды настигла подземная тварь. Холод и острая боль током пронзили все мое тело, когда, падая, я неслась по склону. Приземлившись, я сломала запястье правой руки. Перелом оказался открытым, но я совершенно не чувствовала руку и не могла пошевелить пальцами.

Здесь повсюду было слишком темно, дабы я сразу же смогла разобрать что к чему. Откинув с лица запутавшиеся волосы, я бродила взглядом в окружающем меня мраке. Кое-как мне удалось нащупать в нем луноходы, но я нигде не видела Старлайта.

– Старлайт?! – я звала его по имени снова и снова, но не слышала ничего в ответ. Падение со склона оглушило меня, так что поначалу до меня не доходил даже звук собственного голоса.

Чувство тревоги нарастало. Но ведь прошло всего несколько секунд…

Интуиция подсказала мне поднять взгляд к небу. Тогда я увидела Старлайта и в ужасе закричала. Мерзкие щупальца обхватили его за торс и подняли высоко над тем, что когда-то было озерным краем. Сейчас как ни старался, он не мог вырваться: монстр сомкнулся вокруг его тела мертвой хваткой.

С широко распахнутыми от страха глазами, я по привычке потянулась к поясу, но, само собой, там не оказалось ни оружия, ни ремня для него. Да и откуда им здесь взяться? Я была в штатском и ничем не отличалась от простых туристов.

– Уходи, Отем, – задыхаясь, произнес Старлайт.

Но я не могла уйти. Хотя и сделать что-то я тоже не могла. Собственное тело не желало меня слушать. Оно покрылось невидимыми иголками, сердце замерло в груди, а ватные ноги то и дело подкашивались. Нет, я не могла уйти.

Собрав последние силы, я вернулась к луноходу, но тот никак не желал заводиться, и бросив его, я нашла в темноте другой. В тот момент я еще не знала, что буду делать, но ясно понимала, что больше не могу находиться в стороне.

То, что произошло в следующее мгновенье, остановило все. Мое сердце замерло на веки, а полная счастья жизнь оборвалась, когда я увидела внушающую дрожь картину: осьминогообразные щупальце, державшее Старлайта, выпустило из своих недр еще несколько подобных себе конечностей. Они с новой силой обхватили моего любимого и в один миг разорвали его на части, залил остатки льда алой кровью.

Я почувствовала, как вместе с жизнью Старлайта уходит и моя, и, честно говоря, была совсем не против этого. Смерть казалась мне простейшим путем к спасению от вечной боли и пустоты, которые мне предстояло ощущать на протяжении всей жизни.

Но вместе с тем пришло еще кое-что – озарение. Случившееся на темной стороне с Метьюзом, страх старика Терренса, слова Корнуэлла… Все прояснилось. Проблема была в том, что никто больше не видел происходящего здесь, а значит, некому было остановить их, остановить саму смерть.

Стараясь пересилить сковавшую все тело боль, я поднялась на ноги. Позади все трещало и разлеталось, исчезая в дыре, образовавшейся посреди озера. С большим трудом мне удалось завести луноход, не желавшей слушаться рукой. Только лишь у меня получилось, я на бешеной скорости помчалась прочь из этого проклятого места.

Луноход Старлайта остался ждать своего хозяина под некогда снежным холмом. Вскоре и он исчез в подземных руинах. Следом отправился и сам холм, и окружающие его аллеи со скамейками и беседками – все вокруг.

Пролетая над Луной, я видела, что большая ее часть уже была разрушена. Уцелевшим местам также оставалось существовать совсем недолго: внизу было полно монстров, вроде того, что погубил Старлайта, и все они двигались с огромной скоростью. Вот под моими ногами разошлись горы и подобно тонущему кораблю исчезли в пучине темноты. За горами последовали деревья, целые перки и леса, упавшие словно по взмаху огромной косы.

Не смотря ни на что, удача сегодня была на стороне человечества. Это был вечер понедельника, ни одного туриста. Луна пустовала. Пострадал лишь многовековой труд сотен людей. Язык не поворачивался назвать подобное везением, но, в конце концов, больше никто не погиб. Никто, кроме самого важного для меня человека во всей Вселенной.