---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Зал Совета {#20}

Несмотря на то, что еженедельный совет по обыкновению должен был состояться только завтрашним утром, этой ночью каждый из нас получил сообщение от сенатора Куинна с просьбой незамедлительно явиться в Зал Совета. На тот момент я уже крепко спал, а потому был последним из прибывших на ЭСКМО.

За столом уже собрались все семь капитанов, включая меня. Не доставало только Отем Раст с м83.

– Предлагаю начать совет, господа, – произнес сенатор, сложив перед собой руки.

– А как же Капитан Раст? – поднявшись, спросил Дискейн. Место подле него пустовало. Джеймс всегда сидел напротив меня и каждый вторник предлагал Отем Раст кофе с молоком.

– Думаю, Капитан Раст уже вряд ли явится сегодня, – улыбнулся ему сенатор. – Я лично переговорю с ней при первой же возможности.

Не найдя, что ответить, Дискейн молча опустился в свое кресло.

В коридоре послышались быстро приближающиеся шаги, и вскоре кто-то со всей силы зарядил по дубовой двери зала. Та пошатнулась, но продолжала оставаться закрытой. Некоторые из нас подскочили от резкого звука. Удар повторился, и дверь отворилась.

Сперва никто из присутствующих даже не понял, что перед нами стоит Отем Раст. Вид у нее был воистину жуткий: длинные волосы, обычно аккуратно уложенные синими волнами, сейчас перепутались и потускнели от грязи; несколько мокрых прядей прилипло ко лбу; одежда девушки была изорвана и местами просто превратилась в клочья, на ней повсюду виднелись пятна крови, смешавшейся с грязью. Но больше всего ужасала ее правая рука: пальцы неестественно выгнулись в обратную сторону, а на сгибе запястья виднелся торчащий край белоснежной кости. У локтя рана была перетянута какой-то тряпкой, похожей на пояс от пальто, но это так до конца и не остановило кровотечение и пол под ногами девушки стал покрываться алыми пятнами.

Весь совет в оцепенении смотрел на Отем Раст, кто в ужасе, кто с удивлением.

– Ох, Капитан Раст, – в своей привычной манере протянул Куинн. – Я рад, что Вы смогли присоединиться к нам.

И глазом не моргая, сенатор смотрел на Отем Раст. Кажется, он был единственным из присутствующих в этой комнате, кого ни капли не удивлял ее внешний вид.

– КАКИЕ К ЧЕРТУ УЧЕНИЯ?! – с порога крикнула Отем.

Не знаю, что в тот момент ошарашило меня сильней: ее внезапное появление, или повышенный тон, которым Отем Раст вдруг позволила себе говорить с сенатором. Быстрым шагом она пересекла зал прежде, чем Куинн успел что-либо ответить, и остановилась у обратного края стола. Буквально в половине шага от сенатора.

– На темной стороне таится опасность, – надорванным голосом произнесла Отем Раст, – И я не потерплю от тебя очередной порции ничего не объясняющего бреда.

Она сделала глубокий вдох, стараясь привести нервы в порядок.

– Присядьте для начала, капитан Раст, – наконец, ответил сенатор.

Он указал рукой на единственное пустующее кресло.

– Сейчас уже поздняя ночь, и очевидно, что Вы просто переутомились. У этого даже есть название – нервное истощение, кажется.

– ПЛЕВАТЬ Я ХОТЕЛА НА ТВОИ ПРОСЬБЫ! – вновь вспылила капитан, оставаясь стоять на месте. – На этот раз придется прислушаться ко мне, и, ввиду всеобщей безопасности, советую сделать это как можно быстрее.

Многие из присутствующих уже слегка оправились от шока, и, понизив голос, понемногу начинали обсуждать происходящее, не сводя глаз с Отем Раст и сенатора Куинна. Только я молча продолжал наблюдать за творившимся в зале. На лице каждого был написан вопрос, который пока еще никто не осмеливался задать.

Страшно было даже допустить саму мысль о том, чтобы встрять в их разговор. Ясно-синие глаза Отем Раст потускнели, и теперь в них виднелась лишь испепеляющая ярость. Такой я не видел ее никогда, да и вообще не припомню хотя бы один случай, в котором кто-то из жителей орбиты вел себя подобным образом. Это казалось невозможным, ведь синий водух отнимал и подавлял большинство наших эмоций.

Заметив нарастающую в зале суету, сенатор поднял ладони, призывая капитанов к тишине.

– Прошу прощения, что держал вас всех в неведении, господа. Теперь я намерен незамедлительно прояснить ситуацию.

Его слова произвели должное впечатление. Зал окунулся в полную тишину, а Отем Раст, скрестив на груди руки, все так же пристально продолжала смотреть на сенатора. В этом взгляде сквозило одно лишь недоверие.

Все застыли в ожидании.

– Ни для кого не секрет, что капитану Раст пришлось много и усердно трудиться в последнее время, – начал Куинн. – На фоне последних событий, затронувших м83, я самолично решил провести ряд учений, имевших место быть на темной стороне Луны, забыв предупредить об этом капитана, что попросту сбило ее с толку. К сожалению, часть этих учений оказалось плохо спланированной, и потерпела…

– Достаточно! – прервала его Отем.

Она со всей силы ударила рукой по столу, прямо перед лицом сенатора, что тут же заставило последнего притихнуть. По моей спине пробежала дрожь, а внутри все неприятно заколотилось, когда я понял, что Отем по привычке сделала это правой рукой. Рана принялась кровоточить с новой силой, а по стеклянной поверхности стола теперь расползалась тонкая паутина трещин, которую перекрывал кровавый отпечаток кулака. Сама Отем и внимания на него не обратила, словно не чувствовала никакой боли.

Все происходящее было настолько маловероятным, что мне тут же захотелось ущипнуть себя и наверняка убедиться, что я не сплю.

Дальше Отем Раст произнесла короткую фразу, заставившую сенатора резко измениться в лице.

– Я видела _их_, – сказала она.

Здесь было бы уместно спросить, о чем она толкует. Но Куинн не спрашивал, и у меня сложилось впечатление, что он действительно в курсе происходящего, и его оно явно не радовало. Сенатор поджал тонкие губы, отчего те сразу же побледнели и практически исчезли с его лица. На протяжении какого-то времени он просто смотрел куда-то перед собой до невозможности расширенными зрачками, изредка бросая взгляд на Отем и алый отпечаток ее руки.

– Безумство, – заявил он. – Мне нужны доказательства.

– Смерть Старлайта не достаточно яркое доказательство? – на этой фразе ее голос сорвался.

– Что?! – удивленно взвизгнул сенатор. – Профессор Рок погиб?! Но как это могло произойти, ведь кроме Вас там никого не было…

Фальшивая улыбка медленно сползала с его лица.

Отем не отвечала. Она продолжала стоять над Куинном, не сводя с него глаз.

Он вдруг поднялся, и я подумал, что это, наверное, впервые, когда я вижу сенатора не сидящим в своем огромном белом кресле. Куинн оказался гораздо меньше, чем мне представлялось. Он был одного роста с Отем Раст, если не ниже.

– Что ж, – протянул сенатор с каменным выражением лица, едва ли напоминающим сочувствие, – профессор Рок безусловно представлял большую ценность как для м83, так и для нашей компании в целом, но проектирование его трасс уже практически окончено, а для полного завершения строительства помощь самого профессора нам не понадобится.

Отем ошарашено смотрела на сенатора. Теперь она не находила что ответить.

– Я хочу сказать, – продолжал тот, – что не стоит делать из этой ситуации трагедию. На Земле еще полно специалистов, с радостью готовых в любую минуту начать с нами сотрудничество.

– ДА ТВОЮ МАТЬ, КУИНН! – не выдержала девушка. – РЕЧЬ ИДЕТ О ЧЕЛОВЕЧЕСКОЙ ЖИЗНИ!

– Всего лишь _одной_ человеческой жизни, – спокойно уточнил сенатор. – Подобные вещи не имеют значения, когда вопрос стоит о целой системе. Вам это ясно, Капитан?

– Системе? – переспросила Отем. – Неужели ты все еще собираешься возить в это проклятое место людей?!

– Разумеется, собираюсь, – отрезал сенатор. – Этой ночью произошел небольшой сбой. Из-за бурения темной стороны, как я понимаю. Мы тщательно исследуем этот вопрос и на время прекратим внедрение в лунную поверхность ниже дозволенного уровня, а после отреставрируем все затронутые участки. Не думаю, что их окажется много.

Я видел, как, слушая речи сенатора, Отем безостановочно сжимала здоровую руку в кулак, стараясь сдерживать порывы ярости, что одолевали ее все сильней с каждым сказанным Куинном словом. Делая это скорей интуитивно, девушка и не заметила, что вскоре на ее ладони проступило несколько алых царапин, оставленным сломанными ногтями. Хотя, наверное, ей просто было все равно.

– Все участки затронуты, – осевшим голосом произнесла Отем.

Холодная улыбка вновь заняла свое место на лице Куинна.

– Ну, это, конечно, займет какое-то время, но, скорей всего, в следующем году уже можно будет возобновить туристический бизнес.

– Немыслимо…

– О, не волнуйтесь, – поспешно добавил сенатор, – все затраты тут же окупятся.

Видимо, Отем Раст никак не ожидала такого ответа. Широко распахнутыми глазами она неподвижно смотрела на сенатора, не будучи в состоянии промолвить и слова. Она с силой продолжала сжимать левую руку.

– Что касается профессора Рока, я разделяю Ваше беспокойство, Капитан, но и это сущий пустяк в нашем общем деле. Обещаю, мы найдем для Вас другого мужчину, более подходящего по геному…

Куинн не успел договорить. Сказанные им только что слова оказались последней каплей. На мгновенье Отем прекратила сжимать руку в кулак. Она откинула с глаз болотную прядь волос и, резко замахнувшись, заехала Куинну прямиком в нос. Тот издал громкий хруст, напомнивший мне звук, исходящий от попкорна во время жарки.

Удар не свалил сенатора на пол, а только оттолкнул назад, и сейчас, пошатываясь, тот вжимался в стену. Еще мгновение, и белоснежный воротник его костюма окрасился в алый цвет. Испуганный сенатор двумя руками прикрыл разбитый нос, ожидая нового удара, а когда понял, что тот не последует, лишь выкрикнул что-то нечленораздельное.

Казалось, Отем и сама не ожидала от себя такого. Она удивленно смотрела на свой по-прежнему сжатый кулак и теперь имела весьма растерянный вид. Однако она быстро взяла себя в руки.

Чуть ли не дрожащий сенатор отлепился от стены. Он пошатнулся, но смог удержать равновесие. Мне показалось, что сейчас Отем вновь замахнется, но и этого не произошло.

– Больше ни одна жизни не прервется по твоей вине, – четко выговаривая каждое слово, произнесла капитан Раст.

Ее голос звучал ясно и спокойно, и, несмотря на свой внешний вид, она уже больше походила на руководителя лунной базы.

– Ни одна, – повторила девушка.

Не оборачиваясь, она вышла из зала совета. Алый след тянулся за ней до самой двери.

Пока Отем Раст находилась среди нас, никто не позволял себе говорить громче, чем шепотом, но стоило двери лишь закрыться за ее спиной, и от всеобщего молчания не осталось и следа. Едва ли уловимый прежде шепот тут же перерос в жужжащий гул. Только Дискейн оставался на своем месте и безмолвно смотрел на закрытую дверь.