---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Целься в Луну {#21}

Я держалась. Я действительно держалась до последнего момента.

Вернувшись в корабль, я привела себя в порядок, насколько это было возможно, а покидая его, спрятала в карман изодранного пальто изувеченную руку. К счастью, держать ее на виду было необязательно: мой браслет по-прежнему оставался на левой руке. На своем пути обратно к м83, и шагая привычными коридорами базы, я не подавала виду. Старалась выглядеть естественно и вести себя точно так же, как и в другие дни.

Вот только стоило мне добраться до собственной комнаты, как все разом обрушилось на меня. Место, на которое пришелся перелом, буквально горело, голова гудела и разрывалась, а к горлу то и дело подступала тошнота. Но все это было сущим пустяком по сравнению с другой болью, таившейся где-то внутри меня, и лишь теперь вырвавшейся на свободу. Я чувствовала громадную дыру в сердце и исходящую из нее тоску, унять которую, казалось, было невозможно. Никогда прежде я не была так одинока, беспомощна и абсолютно разбита, как сейчас. Я бы могла поклясться, что ощущала эту боль физически, и это было похлеще любых переломанных конечностей.

Теперь нужно было наведаться в госпиталь и как можно скорее: рука выглядела просто ужасно, да и чувствовала я себя таким же образом. Мне стоило титанических усилий принять душ и надеть на себя чистую одежду. За эти сорок с лишним минут резкая боль в запястье лишь продолжала расти, а я с ужасом осознала, что в моей комнате нет ни одной таблетки. Даже от бессонницы. А ведь когда-то я и ночи не могла без них провести. Затем в моей жизни появились вещи, гораздо важнее недостатка сна, и сейчас я видела, как они исчезали, растворяясь в темноте.

В конце концов, мне удалось накинуть на себя какие-то домашние лосины, о существовании которых я и не подозревала до сегодняшнего дня, и просторную клетчатую рубашку Старлайта. Она была первой вещью, попавшейся мне под руку, но будь она хоть последней, я бы все равно выбрала ее. В таком виде я поплелась в госпиталь.  
Усталость валила меня с ног. До нужного крыла оставалось бесчисленное количество этажей. Этой ночью лифт двигался невыносимо медленно.

Я уже давно потеряла счет времени. Часы, мысли... Все плыло в голове. Картина перед глазами постепенно начинала меркнуть. Я пошатнулась, и, побоявшись потерять сознание, взялась здоровой рукой за поручень у стены лифта. Стоило мне хоть на миг закрыть глаза, и я тут же видела его лицо.

Последние слова Старлайта эхом разносились в моем сознании, бесповоротно заполняя его.

«Кто такой Курт?» - крутилось в голове.

Следом пришло воспоминание об одном из теплых дней, проведенных в городке. Мы ведь успели сходить в тот кинотеатр, а после заглянуть в крохотный бар с единственным в нем музыкальным автоматом. Этот вечер был одним из счастливейших моментов, которые мне довелось пережить. Никто прежде не смотрел на меня так, как это делал Стар. Я не могла поверить в то, что больше никогда не встречусь взглядом с его любящими глазами, никогда не услышу его бархатного голоса и не смогу сказать, как же сильно я люблю его. Счастье навсегда оставило меня, и я буквально чувствовала, как оно покидало мою душу.

Какое же это все-таки неприятное и даже страшное слово – «успели».

Дверь лифта бесшумно отворилась. Стоя спиной к выходу, я не сразу поняла, что уже на месте. В глаза ударил поток света, еще более яркий, чем в коридорах остальных этажей. Все верно, я была в правом крыле девятого этажа.

Честно говоря, действие синего воздуха даже порадовало меня той ночью: никто из медперсонала и словом не обмолвился о том, что же со мной произошло. Никаких изумленных или сочувствующих взглядов, никаких расспросов, они лишь делали свою работу.
Меня привели в порядок, а после и заштопали довольно быстро, наложив на перелом гипсовую повязку.

– Сейчас будет больно, – спокойно произнесла медсестра прежде чем вправить мне кость. – Всего на пару секунд.

По обыкновению, я прикрыла глаза, но так ничего и не почувствовала. Наверное, потому что мне было больно и прежде. Я вся обратилась сплошной болью.

Приняв две таблетки обезболивающего, я направилась обратно к себе. Не знаю, начали ли они действовать так быстро, но в сон меня теперь клонило сильней. Уже вернувшись в комнату, я пожалела о том, что не прихватила с собой из госпиталя еще и успокоительного. Хотя я сомневаюсь, что подобное лекарство в принципе могло быть здесь. К тому же лишнее беспокойство мне также не было нужно. Раны на теле объяснить несложно, а вот душевные – куда трудней.

Я пыталась абстрагироваться от мыслей о смерти Старлайта, но с каждой попыткой они все туже затягивали петлю вокруг моей шеи, мешая думать, или хотя бы дышать.

Войдя в своею комнату, я поспешно закрыла за собой дверь, и тут же опустилась прямиком на пол. У стены валялось одеяло, которое я второпях отбросила, опаздывая на встречу со Старлайтом всего несколько часов назад. Нет, в этот момент меня не преследовало чувство, словно это было так давно. Напротив, было сложно поверить в произошедшее после. Казалось, разум просто отказывался воспринимать тот факт, что моей путеводной звезды больше не было рядом со мной, и я не смогу отыскать его ни в одном их уголков Вселенной, насколько бы бесконечной она не была.

Притянув одеяло ближе к себе, я укуталась в него и, прислонившись к стене, уронила голову, прикрыв руками лицо, а когда опустила их, мельком взглянула на собственные ладони. Удивительно, но они были мокрыми. Я не роняла слез так давно, что уже практически не помнила, каково это. Но на протяжении всей этой ночи слезы непрестанно струились по моим щекам, а я просто не знала, как остановить их. Я лишь неподвижно лежала лицом к стене, слегка прикрыв глаза.

\*

Случившееся минувшей ночью не было кошмарным сном. Я поняла это по холодной постели и ноющему запястью. Как оказалось, спала я всего два часа, а ощущала себя так, словно провела без сознания несколько суток.

Привстав, я потянулась, и окончательно убедилась в том, что больше не хочу спать. Тупая боль пронзала каждый сантиметр моего тела. Тогда я осторожно поднялась с постели. Привычной кружки холодного кофе сегодня не было на месте: вчера я так и не взялась за то, чтобы сварить его. Можно было сделать это и сейчас, но мне совсем не хотелось кофе. Ничего не хотелось.

С чувством глубокой тоски в сердце, я стояла посреди комнаты, медленно обводя ее взглядом. Меня одолевало безразличие ко всем тем ценностям и правилам, что еще недавно были так важны. Сейчас они уже не имели никакого значения и казались мне глупым миражем. Практически забытым.

Я сделала несколько неуверенных шагов к зеркалу. Взглянув в него, я даже не узнала себя, настолько потрепанной и безжизненной я была этим утром.

Вместе с тем, я видела напротив другую Отем. Семнадцатилетнюю, одинокую и депрессивную. Границы последних десяти лет растаяли, отбросив меня далеко назад, в самые мрачные времена моей жизни на Земле. Теперь они казались мне ближе, чем вчерашний день. Бессонница вновь смотрела на меня из зеркала покрасневшими от слез глазами. Я помнила этот взгляд, не смотря на то, что так долго пыталась забыть о нем. Как и о губительном чувстве одиночества.

Осознав, что слезы вот-вот подступят, я отвела взгляд.

С самого момента пробуждения я чувствовала на себе холод, растекающийся по всему телу, и ни повышение температуры в комнате, ни несколько одеял никак не могли унять его. Сильней всего мерзли руки. Я отошла от зеркала и осторожно потерла их одну о другую, пытаясь согреться. Пальцы коснулись чего-то круглого, и тут мое сердце замерло. Кольцо. Ведь я и забыла о нем.

Я вытянула перед собой левую руку. Те крупицы света, что еще ютились в комнате, блестящими искрами отображались на темной поверхности камня, что находился в центре кольца. Сейчас он был таким темным, практически черным, хотя еще вчера казался мне ясно синим. Может, все дело была в освещении, а, может, в моем расположении духа – не знаю.

В конечном счете, мне, все-таки, пришлось приготовить себе кофе, дабы хоть немного согреться. Наполнив чашку обжигающим напитком, я подошла к окну. Странно. Я совсем не чувствовала боли, несмотря на то, что мои пальцы уже с полминуты соприкасались с горячей поверхностью. Все мысли (если таковым еще оставалось место в моей голове) были заняты совершенно иным.

Как же слепа я была прежде. Все то, во что я так беспрекословно верила на протяжении этих долгих десяти лет, обернулось лишь пустым миражем. Рассыпалось, как и все те макеты, установленные на лунной поверхности. Такие ошибки неисправимы.

Эти мысли вызвали в моей голове другие – воспоминания о записке Корнуэлла, оставленной на одной из страниц «Листьев Травы». Той самой, где свое начало брала поема под названием «О, Капитан мой, Капитан».

Мне не понадобилось много времени для того, чтоб найти томик Уитмена, а вот поиски зажигалки, или какого-нибудь еще источника огня, продолжались куда дольше. Кухонное оборудование уже давненько изготовлялось по иному принципу, да и я с восемнадцати лет не держала в руках сигарету.

– Сигареты! – горячо вскрикнула я, и, накинув поверх рубашки теплую кофту, чуть ли не помчалась в комнату Старлайта.

Прибывая на м83, многие бросали курение, даже если прежде этого и не было в их планах. Я могла перечислить на пальцах одной руки тех, кто все еще продолжал появляться на базе с сигаретой в руках. Само собой разумеется, в их число не входили военные, как и сотрудники, находящиеся на темной стороне Луны. В основном, это были люди, работающие в ИИЛП: доктора и инженеры.

Старлайт говорил, что, живя на Земле, курил уже очень давно. Здесь же ему (как им мне) пришлось оставить эту привычку: в штабе курение было запрещено. Однако, несколько раз он позволял себе выкурить сигарету-две, прогуливаясь улочками коттеджного городка.

Войдя в комнату Стара, я на пару секунд задержалась на пороге. Как же непривычно было находиться одной в этом месте, зная, что он уже никогда не появится в дверном проеме. Я закрыла глаза и тряхнула головой, словно стараясь выкинуть из нее все отвлекающие меня мысли.

Пачка сигарет лежала там же, где я видела ее несколько месяцев назад – в верхнем ящике комода, что стоял около окна. Внутри еще оставалось несколько сигарет. Зажигалки рядом не нашлось: сигареты оказались самоподжигающимися, но это тоже подойдет. Взяв их, я поспешно вернулась в свою комнату, и дважды проверила, закрылась ли за мной дверь.

Внутри меня проснулся интерес, смешавшийся с неким опасением. Конечно, сейчас мне всего лишь предстояло узнать пароль, который поможет мне открыть ячейку с последним посланием Корнуэлла, но, зная его не первый год, я отлично понимала, что и в этот момент он непременно вложит свой смысл.

Я подождала еще немного, и, убедившись, что готова узнать правду, нажала на край сигареты. Она тут же зашуршала, а на конце появились небольшие искорки. Тогда я взяла с бара бутылку абсента и наполнила бокал. После чего опустила в него сигарету так, чтоб она слегка касалась поверхности напитка.

С первого раза ничего не вышло, потому мне пришлось проделать все снова. Вот, еще минута, и над бокалом заиграло пламя. Стоило этому произойти, и я тут же схватила со стола заблаговременно вырванную из книги страницу и поднесла ее к огню.

Прошло всего секунд тридцать, которые обернулись для меня вечностью. Затем, увидев проступающую на бумаге надпись, я затаила дыхание. Еще немного и ее можно будет прочесть.

Вдруг мой браслет издал короткий сигнал, оповещающий о новом входящем сообщении. Я отвлеклась всего на мгновенье, а когда вновь взглянула на книжную страницу, увидела в центре нее всего три слова.

«Целься в Луну» – гласило послание.

\*

Сейчас я даже не помнила, как прошлой ночью добралась до постели. Это было неважно. Не знаю, в котором часу я покинула свою комнату, но коридоры здания штаба все еще пустовали, когда я спускалась в холл. Увидев меня, дежурный, как и полагается, отдал честь. Кивнув ему в ответ, я направилась к выходу.

На улице оказалось прохладно и даже сыро, если дорогу, окруженную мрачными сооружениями из стекла и стали, можно было назвать улицей. На протяжении всего пути меня окутывало чувство невообразимого одиночества, но сейчас я всеми силами старалась сосредоточиться на послании Корнуэлла, так что даже мысли о Старлайте отступили на задний план (конечно, я не смогла бы полностью избавиться от них даже перед лицом собственной смерти).

Соприкоснувшись с пламенем, пожелтевшая страница «Листьев Травы» явила мне всего три слова – совсем ничего для того, чтобы прочесть, но так много для размышлений. Целься в Луну. В памяти застыла проступающая на бумаге надпись, и тогда я представила, как сидя в своем излюбленном плетеном кресле, Джуд Корнуэлл бережно наносил на книжную страницу лимонный сок. Так, словно это было не здесь и сейчас, а многие столетья назад, в каком-то другом практически забытом всеми мире. Эти мысли вызвали на моем лице мрачную улыбку. Ненадолго. Нужно было действовать как можно скорей.

Убедившись в том, что поблизости нет никого, способного остановить на мне свой любопытный взгляд, я поспешно вошла в здание пятого сектора, и быстрыми шагами поднялась в квартиру Корнуэлла.

В нос тут же ударил знакомый запах винила и красного дерева. Я бы смогла узнать это место даже с закрытыми глазами. Впереди мне предстояло завершить уйму дел, ко многим из которых я еще и не преступала, однако сейчас мне хотелось иного. Я просто знала, что должна придти именно сюда.

Вздохнув, я подняла темную крышку рояля и присела на небольшое кресло с замшевой обивкой, что стояло перед инструментом. Поставила руки на клавиши так, как учил меня Старлайт… и, все-таки, невероятно сложным для меня оказалось сдержать слезы. Они тут же подступили, стоило лишь прозвучать первой ноте. Пришлось остановиться, дабы убрать стекающие по щекам слезы. Я провела по ним просторным рукавом кофты, и начала мелодию заново.

22

шеренга солдат уже заполнила весь холл, когда я спустилась на первый этаж.

Не произнеся ни слова, я миновала ее, поначалу не замечая удивленных, а кое-где и смущенных взглядов. Лишь пройдя треть своего пути, я обратила на это внимание.