---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Подвесная Терраса {#22}

Приведя нервы в порядок, я отправилась на космодром и отыскала среди камер хранения предназначенную для меня ячейку. В ней оказался очередной конверт. Он был толстым – внутри находилось страниц с десять, не меньше. Открывать его прямо здесь было бы крайне опрометчиво. Даже пребывая в затуманенном состоянии, я понимала это. Нужно было найти пустующее место и заглянуть в конверт вдали от всех. Коттеджный городок оказался первым, что пришло мне в голову, да и сейчас он как раз находился под рукой, так что я не стала долго раздумывать над своим решением, и отправилась прямиком туда.

По пути в городок я заметила, что иду медленней обычного. Видимо, после случившегося накануне, двух часов сна оказалось недостаточно для того, чтобы хоть немного придти в себя. Хотя, честно говоря, я не верила в то, что мне вообще когда-либо удастся оправиться. Все что я делала, я делала для своей любви. Старлайта больше не было со мной, но я не могла позволить стать его смерти напрасной. Человечество нужно предупредить об опасности и оградить от нее. Корнуэлл был прав всегда и во всем, и сейчас я собиралась взорвать эту гребанную Луну. Уничтожить все, что может поспособствовать посещению человеком этого места.

Только эти мысли и намерения заставляли меня все еще держаться на ногах. Возможно, я еще не раз пожалею о том, что не позволила себе погибнуть прошлой ночью. Просто остаться лежать на холодной земле в ожидании конца. Может быть, так было бы для меня лучше, но я уже никогда этого не узнаю. Еще было что разрешить.

В городке все было заперто, а сам он пустовал. Можно было бы войти в один из коттеджей, или любое другое здание, но я предпочла остаться снаружи. Мне нравилось находиться здесь: так я чувствовала себя менее одинокой, чем являлась на самом деле. Казалось, Корнуэлл был где-то рядом. Сидел в своем кресле, готовый утешить меня в любую минуту.

Не в силах больше ждать, я присела на обочине пустующей дороги и достала торчащий из кармана конверт. Новая волна боли отозвалась в запястье, когда я разворачивала письмо. Странная штука – самовнушение, ведь еще пару часов назад, касаясь мелодичных клавиш рояля, я не чувствовала этой боли. Несмотря ни на что, мне казалось, что даже когда кости полностью срастутся, рука все равно не перестанет болеть. И я не ошибалась. Спустя полгода я все так же чувствовала эту боль, напоминающую мне о событиях той злосчастной ночи.

Я скрестила под собой ноги, и развернула письмо.

_Моя дорогая Отем,_

_Я не буду вдаваться в описания душевных метаний глупого старика, тем самым тревожа твое, должно быть, и без того обеспокоенное сердце, а посему сразу же перехожу к делу. Как ты можешь увидеть, эти страницы далеко не первой свежести, а значит, написал я их задолго до того, как отдал тебе, хотя, надеюсь, что до этого так и не дошло._

_Сегодня двенадцатое октября 25… года – день когда ты стала капитаном, чему лично я несомненно рад, но теперь, пока есть время и возможность, я хочу передать бумаге все свои тревоги и подозрения, что, возможно, поможет тебе в будущем._

_Уже долгое время меня терзают сомнения насчет безопасности мира, созданию которого я способствовал. Все началось девятнадцать лет тому назад, когда по завершению рабочего дня, я привычно прогуливался по вишневым садам и их окрестностям. Не знаю, была ли это внезапно очнувшаяся ото сна интуиция, или сама Вселенная благосклонно решила подать мне знак, но я вдруг почувствовал, что нахожусь не один в этом месте. Как сейчас помню тот вечер: по спине скользнул холодок, а в сердце закралось тревожное чувство. Я сразу же огляделся по сторонам, но, естественно, ничего не увидел. В тот день я ушел домой ни с чем, но это необъяснимое волнение продолжало преследовать меня на протяжении всех грядущих лет._

_Признаюсь, я привык доверять своей интуиции. Однажды я уже ослушался ее, и это стоило мне семьи._

Я оторвалась от чтения, и удивленно подняла брови. Семьи? Корнуэлл никогда не упоминал о них. Мне казалось, что он такой же одиночка, какой всю жизнь была я… и вот сейчас вновь стала.

Отогнав от себя унылые мысли, я вернулась к письму.

_В следующий раз это повторилось только спустя восемь лет. Тогда я отправился проведать своего старого знакомца, работавшего в пятом пункте бурения. Напевая какую-то забытую мелодию, я шел по тоннелю, ведущему от базы на темную сторону Луны._

_Тогда еще все было обустроено иначе, сотрудникам приходилось использовать луноходы и тяжеленные скафандры, дабы перемещаться по территории. Но главное оставалось неизменным: надземный стеклянный тоннель был уже тогда, разве что тянулся он на несколько десятков метров меньше, достигая лишь первого пункта. Далее приходилось добираться с помощью лунного транспорта._

_Я уже почти достиг двери, ведущей в бурильный пункт, как вдруг краем глаза заметил какое-то движение за толстой стеной коридора. Остановившись, я повернулся и вплотную подошел к стеклу. За ним было тихо. На меня смотрела лишь темнота, но я был уверен, что еще несколько секунд назад уловил что-то по ту сторону стекла. Для этого отрезка Луны еще не был спроектирован макет, так что и ветра здесь быть не могло._

_Позже я указал на это место своему товарищу, Теодору Эриксону. Тот сказал, что участок, о котором я спрашиваю, как раз был занят под бурение, и, скорей всего, я просто видел камни, вылетающие из-под оборудования. Должен заметить, что самого Теда мои сомнения нисколько не озадачили, а вот мне интуиция подсказывала обратное. Но в этот раз у меня вновь не оказалось доказательств, что смогли бы хоть сколько-нибудь подтвердить мои опасения._

_Мне стали видеться сны. Ужасные кошмары, очнувшись от которых, я еще долгое время сидел на кровати, будучи не в силах придти в себя. Я дрожал от страха, словно был не стариком, а по-прежнему оставался мальчишкой, и ничего не мог с этим поделать. Спасало лишь чтение, помогавшее мне собраться с мыслями и сосредоточиться на работе._

_В своих снах я шел по тоннелю, или ягодному полю, а иногда просто сидел в своем кабинете… Место действия не имело значения, потому что кошмары мои всегда заканчивались одинаково: все то, над чем я трудился более семидесяти лет, и что успел немало полюбить за эти годы, рушилось прямиком на моих глазах, унося с собой жизни ни в чем не повинных людей. Это ужасало меня._

_Отдышавшись после кошмаров, я размышлял о незавершившихся гештальтах, но так и не мог понять, к чему все это приведет._

_Я не боюсь собственной смерти. Откровенно говоря, я давненько мечтаю о ней. Жизнь становится в тягость, когда знаешь, что уже отходил свое. Особенно жизнь в одиночестве. Но я опасаюсь за человечество. Уровень желающих посетить окрестности Луны растет с каждым днем, и это не остановить._

_Каждое живое существо имеет особую значимость и предназначение. Неважно, сколько людей может погибнуть из-за неосмотрительности других – один или тысяча – это все равно станет трагедией._

_Тогда я не мог поделиться своими кошмарами ни с тобой, ни с действующим капитаном, но одним из давно минувших ноябрьских вечеров, я, все же, рассказал о них, сидя за кружкой бренди в узком кругу своих приятелей из нескольких пунктов бурения. Выслушав меня, они поведали о недавно переведшемся к ним Ките Терренсе. Безумец – так они его называли. Этот молчаливый малый вел себя так, словно был не от мира сего и постоянно невесть чего страшился. Не знаю, было ли это вызвано моим преклонным возрастом, или роль здесь сыграла солидарность, появившаяся из-за моих собственных опасений, но я пропитался к бедняге немалым состраданием._

_Я решил лично переговорить с Терренсом, и как-то, встретив его у входа в туристический космодром, не смог упустить такую возможность._

_Стоит ли говорить, что эта оказалась далеко не лучшей из моих идей? Возраст ничего не значит, когда дело касается ума. На самом деле я просто недооценил уровень страха, пленившего Терренса, а впоследствии и паники._

_Тем утром я подошел к нему, и, представившись, предложил выпить кофе. Увидев, что к нему идут, Кит что было сил схватился за ручку стеклянной двери. Поразмыслив несколько секунд, он наконец оставил ее в покое, и, не сказав мне ни слова, направился в сторону кафе, что находилось в центре зала, прямиком за постаментом падающей звезды. Я пропустил вперед веселую парочку туристов, оживленно обсуждающих проведенные на Луне выходные, и последовал за Терренсом._

_Я заметил, как идущая передо мной рыжеволосая девушка повернулась к своему спутнику, и с немного печальной улыбкой произнесла: «Как же не хочется возвращаться в Пасадену. Здесь так спокойно…». Эта ненароком подслушанная фраза только предала мне решимости._

_Я догнал Терренса и мы присели за самый дальний столик. Не стану описывать последующий разговор с официанткой и прочие мелочи. Перейду сразу к тому моменту, когда я склонился к Киту и еле слышно рассказал свою историю. Он слушал меня со стеклянным взглядом, а когда я закончил, то предложил ему взять луноходы и проехаться к тому самому месту, где на днях заметил какое-то движение._

_Пойми меня правильно, Отем, я и подумать не мог, что собеседник мой был_ **_настолько_** _подвержен собственным фобиям: парни из блока порой любили приукрасить. В общем, я надеялся, что Терренс поможет мне добраться до нужного бурильного участка (ведь сам я не привык управляться с подобным транспортом и оборудованием в одиночку). Уже спустя мгновенье я осознал, как глупо поступил._

_Услышав о возможном визите темной местности за пределами пункта, Терренс резко подскочил на ноги и закрыл лицо руками. Он вертел головой так, словно пытался вытрясти из нее какие-то ужасные воспоминания, известные лишь ему одному, и постепенно отступал назад, при этом повторяя лишь одно слово – «Нет». Растерявшись, я не знал, что и поделать, а голос Терренса тем временем звучал все громче, превращаясь в крик. Наконец, я пришел в себя и тоже поднялся на ноги, желая успокоить беднягу. Завидев мое приближение, тот вдруг начал пятиться быстрее и вскоре завалился на пол, споткнувшись о ножку стоявшего позади него стола. На шум сбежались удивленные туристы и встревоженные работники космодрома, а Терренс упал на пол и продолжал биться в истерике._

_Медики прибыли быстро. Они дали ему лошадиную долю транквилизаторов и поспешно увезли в госпиталь, подальше от глаз всполошившейся толпы. Именно после этого случая работникам темной стороны Луны было запрещено покидать ее пределы вплоть до истечения сроков их контрактов. Сенатор Куинн полагал, что такая выходка может повториться, так как, в отличие от базы и светлой стороны Луны, другая ее часть не находилась под колпаком, а значит, работавшие там люди (к большому, с его слов, сожалению) не подвергались воздействию синего вохдуха, и оттого больше остальных были склонны к подобной эмоциональности._

_Когда я узнал, что после выписки из госпиталя Кит Терренс не только не был уволен компанией, а к тому же еще и переведен работать подальше от внушавшего ему страх места, то восхитился добротой сенатора, в очередной раз проявив глупость. Кто бы мог подумать, что я с такой легкостью смогу спутать расчетливость с милосердием?_

_Прошло еще какое-то время. Сейчас я убежден в том, что действующая власть все знала и попросту хотела держать Терренса под рукой, боясь что его поведение отпугнет посетителей, в разы сократив прибыль, получаемую ЭСКМО от туристических поездок. Мне хочется думать, что виной этому было влияние Луны… да что угодно, затмившее разум нашего руководства, ведь так сложно поверить в то, что человеческое сердце способно на подобную жестокость._

_Вчера я встретил почтенного капитана Хилла. Полагаю, теперь принято говорить, покинувшего службу капитана Хилла. Тот выглядел до невозможности изнеможенным. Еще не зная о его уходе, я счел, что виной его усталости послужила операция «Алый Орион»._

_– С добрым утром, капитан Хилл, – протянул руку я, и мы обменялись приветственными рукопожатиями._

_– Сожалею, что не могу поговорить дольше, мистер Корнуэлл, – сказал тогда Хилл._

_Я отмахнулся._

_– Уйма забот, я все понимаю, – ответил я. – Особенно в такие времена._

_Он многозначительно кивнул._

_– Надеюсь, Вы заглянете в городок на этих выходных, – продолжал я. – Хэллоуин на носу, так что предвидится море гостей. Мы с ребятами планируем устроить настоящий фестиваль ужасов._

_Я улыбнулся._

_– Вряд ли я смогу, – негромко проговорил капитан. – Я так устал, Джуд._

_Что-то насторожило меня в его печальном взгляде._

_– Что ж, тогда, конечно, лучше отдохнуть как следует, – ответил я._

_На том мы и распрощались._

Здесь письмо обрывалось. За ним последовало еще несколько листов, написанных беглым, менее аккуратным почерком, по которому было заметно, что Корнуэлл спешил.

_Прошло практически три года с того дня, когда я сел писать предыдущее письмо, но так и не смог его закончить. Меня прервали. По иронии судьбы, это была ты, Отем. Ты зашла ко мне, желая поделиться новостью о твоем повышении, про которое я, конечно же, уже знал. Честно говоря, я все это время откладывал написание письма, не желая вспоминать то, что и так непрестанно будоражит мою душу. А сегодня я узнал, что в скором будущем должен буду покинуть м83, а потому решил закончить свое послание._

_Итак, Винсент Хиилл не мог больше жить со знанием того, что сотни людей ежедневно подверглись опасности, находясь здесь. Как тебе известно, он покинул службу и пустил себе пулю в лоб, только лишь добравшись до дома. Я же ни на минуту не верю в то, что это было самоубийство. Идти против действующих властей более чем опасно. Сделав такой шаг, лучше убраться с орбиты подальше, пока они не убрали тебя._

_Так вот, когда Хилл собрался с духом и дал отпор сенатору, тот сразу же принялся подыскивать на пост капитана кого-то менее опытного. Человека, который не смог бы возразить ему. Выбор пал на тебя. Ввиду того, как самоотверженно ты повела себя в ту кровавую ночь, твое повышение казалось вполне логичным, а сам Куинн был убежден в том, что ты-то уж точно не стала бы ему противоречить. И он ошибался._

_Мне же приходилось молчать, дабы не быть постигнутым той же печальной участью, что и капитан Хилл. Но я всегда знал, что в свое время ты обязательно придешь к разгадке, и был несказанно рад этой мысли._

_Со временем тревожные сны не прекратились, а лишь обрушились на меня с новой силой. Говоря о кошмарах, ты никогда не задумывалась о том, для чего кому-то понадобилось захватывать Луну? Вот я не раз спрашивал себя об этом. Воспользовавшись помощью нескольких своих друзей (чьи имена я не стану упоминать, опасаясь, что это письмо может попасть не в те руки) я нарушил ряд правил, но узнал, что репутация всех людей, участвовавших в захвате коттеджного городка, вплоть до той кровавой ночи была кристально чистой. Я также узнал, что главарь той банды – Дэвид Норрингтон – приходился сыном Уильяму Норрингтону, поступившему служить на м83 шестнадцать лет назад. Одной злосчастной ночью Уильям Норрингтон пропал, а спустя несколько часов был объявлен дезертиром после десяти лет безукоризненной работы. Как оказалось, на Землю он так и не прибыл. Думаю, ты уже догадалась, к чему я веду. В планы Давида Норрингтона едва ли входили убийства, за которые он был казнен. Наоборот, он всего лишь хотел уберечь человечество от грядущей катастрофы._

_Что ж, теперь я рассказал все, что хотел. Не знаю, что именно подстерегает нас за стенами стеклянного тоннеля и как долго оно будет там оставаться, но понимаю, что узнав правду, ты наверняка не согласишься быть равнодушной к происходящему, а потому прошу тебя, Отем, будь осторожна._

_С пожеланиями скорейшего наступления_

_лучших для всех нас времен и бесконечной_

_любовью,_

_твой друг, Дж. К._

_P.S. Сегодня, стоя у окна гостиной, я запаковывал некоторые вещи, что решил забрать с собой на Землю, когда увидел молодого человека, несущегося над трассой на луноходе. Удивительно, как же сильно он напомнил мне тебя, впервые прибывшую на м83. «Наверное, новенький» – подумал я. И, все же, порой так приятно увидеть искреннюю улыбку в этом замерзшем стальном мире._

Я сложила письмо в конверт и спрятала его подальше в карман своей кофты. Там же я нашла сигареты Старлайта, и, не раздумывая, закурила, растянувшись прямиком посреди дороги.

\*

Открыв глаза, я обнаружила, что по-прежнему лежу на трассе, сжимая в пальцах здоровой руки давно погаснувший окурок. Судя по количеству снега, образовавшегося на моей одежде, я пробыла здесь довольно долгое время. Не смотря на это, мне все еще жутко хотелось спать.

Отряхнув свою одежду, я (с немалыми усилиями) поднялась и неспешно зашагала обратно по заснеженной дороге.

Когда я вернулась в штаб, шеренга солдат уже заполнила весь холл таким образом, что миновать их, оставаясь незамеченной, было просто невозможно. Шагая вдоль нее, я поначалу и не замечала удивленных, а то и смущенных взглядов, направленных на меня. Я поняла это, пройдя уже четверть своего пути, и уже хотела осведомиться, в чем тут дело, но, повернувшись, увидела в стекле свое замученное отражение, и вопрос отпал сам собой.

Кто-то позади коснулся моего плеча. Обернувшись, я увидела Сириуса встревоженного как никогда. Я даже не заметила его приближения, но мне не показалось это странным: сейчас я вообще медленно соображала.

– Отем, на пару слов, – произнес он.

Я ничего не ответила и последовала за старпомом по холлу.

Оставив десант позади, мы вошли в просторный конференц-зал, что находился в самом конце коридора.

–Присядешь? – предложил Сириус.

Я отрицательно покачала головой. К этому моменту навалившая на меня усталость сказывалась ярче прежнего. Я ощущала небывалую слабость и побоялась, что стоит мне присесть, и я вновь тут же погружусь в сон, а это могло бы стоить мне жизни.

– Хорошо, тогда я начну, – Сириус закрыл за нами дверь и подступил ближе. – Мне не хочется говорить тебе это, но ты не можешь появляться перед солдатами в таком виде.

Я машинально окинула взглядом свою одежду и лишь пожала плечами.

– Дело даже не в этом… – продолжал Сириус. – Черт возьми! Да ты ведь смотришься так, словно даже не знаешь, какой сегодня день.

– Вторник? - неуверенно предположила я.

– Почти, - ответил старпом. - Сегодня среда.

Я вздохнула.

– Я встревожен. Ты отсутствовала на базе больше суток, пропустила три построения, но, что еще хуже, не была на вчерашнем заседании Совета.

– Оно состоялось? – удивилась я. Этого я уж точно никак не ожидала.

– Да. Было перенесено на третью четверть. Разве ты не получила уведомление?

– Наверное. Я не проверяла.

– А должна была проверить, Отем! – он слегка повысил голос, но тут же опомнился и продолжил говорить свойственным ему ровным тоном. – Вот это как раз то, о чем я сейчас говорю. Складывается такое впечатление, что тебе стали совершенно безразличны внутренние дела нашей компании.

Я не нашлась, что ответить.

– Послушай, я не могу понять, как такое возможно на м83, но вижу, как много Старлайт Рок значил для тебя, но сейчас очень неподходящее время для того, чтобы опускать руки.

Я видела, что Сириусу этот разговор давался куда тяжелей, чем мне, и, наконец, жестом остановила его. Старпом тут же замолчал, и теперь в ожидании смотрел на меня.

– А сейчас присядь и выслушай меня очень внимательно, Сириус, – произнесла я.

Говоря о старпоме, я всегда могла быть в нем уверена, а потому и рассказала Сириусу все, что знала сама и то, о чем могла только догадываться. Он ни разу не прервал меня, но я видела, как по ходу рассказа менялось его выражение лица. С каждым моим словом Сириус Уайт все больше погружался в то, что одни зовут катастрофой, другие же — мыслями.

\*

Однажды мне посчастливилось провести неделю в Париже. Было это практически за год до окончания моей учебы в Космической Академии. Я прибыла туда ранним весенним утром и провела целые сутки без сна, гуляя по старинным улочкам Страны Садов, а с наступлением темноты поднялась на Эйфелеву башню. Восхищение всецело охватило меня, когда я оказалась на самом верху: таким чарующим был открывающийся впереди меня вид. Пейзаж, застывший у меня перед глазами и чувства, что я испытывала в тот самый момент, были прекрасны, но, что еще важней, я была не одна. Неважно, чем закончился этот роман и какой он меня сделал, ведь в итоге, спустя столько лет, значение имел лишь этот миг, когда, стоя у мостика обзорной площади с широко раскрытыми глазами и чувством умиротворения, я, не замечая ветра, наслаждалась картиной вечернего города.

Подобные ощущения я испытала, впервые увидев окрестности Луны. Еще более волшебным оказался тот вечер, проведенный со Старлайтом на лавандовых полях. Возможно, прежде я не осознавала этого, но я любила м83, любила Луну с ее восхитительными садами и парками. Но сильней всего я любила Старлайта, и теперь его не было со мной, как и былого волшебства на лунной поверхности. Она обернулась для меня лишь очередным дремлющим небесным телом, чей холод окутывал все вокруг. Теперь здесь стало небезопасно. С каждым новым днем все то, что с таким трудом создавалось на протяжении многих десятилетий, разрушалось, поспешно исчезая во мраке.

Стояла глубокая ночь когда, пробравшись сквозь мрачные тени своего кабинета, я вышла на подвесную террасу. До этого момента все делалось в ужасной спешке, и вот теперь я остановилась, решив насладиться моментом (насколько мне позволяло время). Уже через несколько часов я буду на Земле, сидеть, глядя на Луну, где-то там, в одной из круглосуточных забегаловок у дороги. Скорей всего, это последний раз, когда я так смотрю на м83, по крайней мере, я вряд ли еще увижу базу такой, какая она сейчас.

Капитан покидает корабль — так неправильно и несвоевременно, но другого выхода попросту нет. Глупо геройствовать, оставаясь здесь в ожидании ареста, а то и смерти. Мне нужно, нет, я обязана двигаться дальше, дабы предотвратить катастрофу.

«Я спасаю мир, но не могу спасти тебя», – скользнула в голове мысль.

Пока вокруг все было тихо, но к утру меня тут же хватятся, так что нельзя рисковать, надеясь на лучшее. Важно, чтоб меня не перехватили по дороге на Землю, потому маршрутами компании я пользоваться не могла. К счастью, у меня оставался тестовый корабль Старлайта с его звездными картами. На нем я должна буду обогнуть Луну и, выйдя в открытый космос, взять курс на Землю. Времени это займет дольше, но так я могу быть уверена, что мне не помешают.

По привычке смахнув упавшую на глаза прядь волос, я в последний раз взглянула на коттеджный городок, стараясь как можно лучше запомнить этот момент. В свете луча его огни выглядели особенно завораживающими. Словно время здесь остановилось и событий последних сорока восьми часов не существовало и вовсе. Все было так же, как и в мой первый день на м83. Корнуэлл показал мне это место, а спустя десять лет я показала его Старлайту.  

Меня вновь охватила тоска. В голове звучали строки «Печальной Луны» Элвиса, и я перевела взгляд.

Я направлялась к «Рокстару», а над м83 все так же возвышалась голубая Луна. Казалось, ей было все равно.