---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Голубая Луна {#23}

Холодное дуло пистолета было приставлено к виску Джуда Корнуэлла, но, полностью поглощенный своими мыслями, он практически не замечал этого. Мартин взвел курок и повторил свой вопрос.

– Куда направляется Отем Раст?

Они пробыли здесь уже двенадцать часов, парни в черных костюмах, представившиеся ФБР-овцами. Хотя Корнуэлл прекрасно знал кто они, он все же впустил их: он не хотел лишней шумихи вокруг своего дома, а эти ребята все равно бы вошли.

Все это время они донимали Корнуэлла бесконечными расспросами, вновь и вновь задавая все те же вопросы, на которые он не смог бы ответить даже если бы захотел.

– Не имею ни малейшего понятия, – в который раз повторил Корнуэлл. – Я не говорил с Капитаном с самого своего отъезда. Это запрещено, вы ведь знаете.

Правой рукой он провел над верхней губой – нос был разбит еще пару часов назад и никак не прекращал кровоточить. На руке теперь недоставало двух пальцев, но это не волновало Корнуэлла, он мог держать сигарету и в левой руке.

От ярости на лбу Мартина вздулась вена, его приводил в бешенство спокойный тон старика. Он уже замахнулся кастетом, намереваясь нанести очередной удар по лицу Корнуэлла, когда услышал голос Фреда Девенпорта.

– Оставь его, Джонни! Надоели уже твои крики! – раздраженно бросил тот.

Фред листал электронные страницы отчетов, присланных сенатором Куинном. Отчеты были за десять лет, последние три года их составляла Отем Раст, а до этого ее предшественник – капитан Винсент Хилл. Все страницы были заполнены идеально прагматично и невероятно нудно. Ничего личного, а потому – ни единой зацепки.

– Не доверяю я ему, – ответил Мартин, опуская руку. – Старик определенно что-то знает. Не зря же он ей те коробки слал.

Затем он повернулся к Гансу Браунингу – третьему и самому молодому из пришедших тем вечером в дом Корнуэлла мужчин. Тот дежурил около телефона, периодически меряя шагами расстояние от окна до журнального столика и назад.

– Сделай мне еще кофе, – бросил ему Мартин. – И на этот раз разбавь коньяком как следует!

– Я тебе не нанимался, – еле слышно буркнул Ганс, но, встретившись взглядом с Мартином, послушно отправился на кухню.

Хотя в документах и сообщалось, что Корнуэлл вернулся на Землю около пяти месяцев назад, по всей его квартире по-прежнему были расставлены коробки с вещами, и неуклюжий Ганс тут же споткнулся через одну из них. Он громко выругался и потянулся за виски.

– Осторожно на обратном пути, мистер Браунинг, – послышался голос Корнуэлла. – Джонни не из тех, кто любит, когда его _кофе_ проливают, – предпоследнее слово он произнес особенно ярко.

Никто ему не ответил, и Корнуэлл закурил очередную сигарету – ему нужно было подумать. Он действительно не знал о планах Капитана, зато уже давно догадывался об опасности, таившейся на темной стороне Луны. Он наблюдал за этим многие годы, и, как только его опасения начали подтверждаться, Корнуэлл сразу же открыл этот вопрос. Но не в зале совета. Он хотел поговорить с сенатором с глазу на глаз, что оказалось неверным решением. Стоило лишь сделать это, и он тут же был отослан с м83 под липовым предлогом.

И, все же, Корнуэлл был рад, что говорил тем утром именно с Отем Раст. Тогда он не врал ей, а действительно боялся, но не смерти. По крайней мере, не своей собственной. Старлайт Рок погиб – он услышал об этом от Мартина. Корнуэлл не знал, в действительности ли это было случайностью, но понимал, что впереди еще много смертей. Главным вопросом был: удастся ли остановить катастрофу прежде, чем она коснется Земли?

Но сейчас ему нужно было думать не об этом. Что если Капитан сразу же явится к нему, или, еще хуже, прямо к властям? Как сейчас предупредить ее? Стоило бы отправить послание, но каким образом? За ним следили каждую минуту, да и местонахождение Капитана уже никому не известно.

Корнуэлл перебирал в голове всевозможные варианты, но никак не мог найти ответа, хотя и чувствовал, что тот находится где-то совсем рядом, на поверхности.

Так он просидел еще часа полтора, погруженный в собственные размышления, не заметив, что сигарета в руке давно потухла.

Тишину прервал телефонный звонок. Пронзительный и резкий он словно рассекал пространство вокруг Корнуэлла. Сердце старика забилось сильней, но Джуд не подал виду, а лишь вопросительно взглянул на Мартина. Тот криво ухмыльнулся и схватил телефон, стоило лишь звонку повториться.

– Слушаю.

– Джонни, твою мать! Какого черта ты снимаешь трубку? – он услышал знакомый голос того, кто никогда не называл своего имени. Между собой они называли его Тихоня Билл. Но сейчас звонивший был явно недоволен. Сенатор Куинн давил на него каждую свободную минуту. – Я же ясно выразился: к телефону подходит только Корнуэлл.

Мартин заметно потускнел.

– Простите, сер, он…

– Вам удалось что-то найти? – перебил его звонивший.

– Пока что ничего, сер, но мы не прекращаем поиски.

– Ясно. Ищите дальше. Я перезвоню позже, и, не приведи небеса, я услышу, что ты снова подскочил к телефону.

Джонни хотел еще что-то сказать, но связь уже оборвалась. Он положил трубку на место и бросил раздраженный взгляд на телефон. Аппарат был старше всех их вместе взятых. Корнуэлл приобрел его много лет назад в Голливуде, на аукционе, посвященном предметам из черно-белого кино. Этому телефону удалось засветиться в летне «Некоторые любят погарячее». Корнуэлл хранил его в память о старых временах, в которые никогда не жил, но коими был очарован с самого детства. Сейчас можно было запросить целое состояние за такой предмет.

– Где ты только берешь это старье? – прошипел Джонни. – Весь дом им набит.

Корнуэлл ему не ответил. Он в очередной раз стер с верхней губы кровь, и подумал, что стоит попросить Ганса заварить ему чай.

– Тихоня Билл звонил, – продолжал говорить Мартин. – Спрашивал, не нашли ли мы чего полезного в этом захолустье.

– Да, я уже понял, – ответил Девенпорт, который все так же копался в документах.

– Не там ищите, – вдруг сказал Корнуэлл.

Все трое повернулись к нему. Первым среагировал Мартин. Он достал из внутреннего кармана револьвер, и быстрым шагом направился к старику.

– Тогда, может, уже скажешь нам, где искать?! – с нетерпением крикнул он. – Или мне отстрелить тебе оставшиеся пальцы?

Корнуэлл устало выдохнул.

– Отем Раст незачем здесь появляться, – начал он, но тут телефон вновь зазвонил.

– Это Тихоня Билл, – бросил своим парням Мартин. Он мигом повернулся обратно к Корнуэллу. – Поднимайся и сними трубку.

Старик сделал попытку встать, но ноги онемели от многочасового сидения в одной и той же позе. В итоге, кое-как ему удалось дойти до журнального столика. Он поднес к уху трубку.

– Джуд Корнуэлл.

– Как хорошо, что я застала Вас дома, – послышался в трубке низкий женский голос. Уже не такой монотонный, как прежде, но Корнуэлл сразу же узнал его, и на этот раз ему не удалось скрыть волнение.

– Это она, – прошептал Девенпорт. Он обратился к Гансу. – Проверь, идет ли запись.

Браунинг кивнул.

– У меня большие проблемы, мистер Корнуэлл, – говорила Отем. – Я вынуждена просить Вас об услуге.

Теперь ее слышали все четверо.

– Что угодно, дорогая, – ответил Корнуэлл.

Холодное дуло револьвера вернулось к его виску.

– Узнай, где она, – требовательно произнес Мартин, понизив голос.

Джуд понимал, что сейчас ему придется послушаться Джонни, но этого не понадобилось.

– Я уже сутки как в открытом космосе, – произнесла Отем. – Не могу найти дороги домой. Связь только появилась и может пропасть в любую минуту. Мне нужны координаты какой-нибудь пустоши, или космодрома. Любые. Только бы выбраться из этой темноты.

– Одну минуту, Капитан.

Корнуэлл опустил трубку. Все трое уставились на него.

– Чего ты ждешь? – спросил Мартин и взвел курок. – Дай координаты своего дома. Возьмем ее прямо здесь.

– И узнай, где она сейчас находится, – добавил Девенпорт.

Ганс молчал.

Корнуэлл медленно кивнул. Он поднес аппарат обратно к уху.

– Сколько на твоем циферблате? – спросил он.

– Данные все время меняются, – последовал ответ. – Сейчас посмотрю.

– Хорошо. Сейчас я продиктую координаты своего дома в Кентуки. Но прежде ответь мне, теперь-то ты разобралась в себе, Капитан?

– Определенно, – отрезала Отем. – Кстати, координаты: все по нулям.

– Что? – удивился Корнуэлл. – Но это ведь похоже на…– он вовремя замолчал.

Взгляд старика упал на одну из валявшихся в коридоре коробок, из которой виднелся край выцветшей пластинки Элвиса. Кажется, это была «Голубая Луна».

Корнуэлл улыбнулся. Он знал, что делать.