project:
  type: book
  output-dir: ../docs

book:
  title: "SciFi"
  author: "Александра Булгакова"
  # date: "2016"
  chapters:
    - index.qmd
    - ../01.Rmd
    - ../02.Rmd
    - ../03.Rmd
    - ../04.Rmd
    - ../05.Rmd
    - ../06.Rmd
    - ../07.Rmd
    - ../08.Rmd
    - ../09.Rmd
    - ../10.Rmd
    - ../11.Rmd
    - ../12.Rmd
    - ../13.Rmd
    - ../14.Rmd
    - ../15.Rmd
    - ../16.Rmd
    - ../17.Rmd
    - ../18.Rmd
    - ../19.Rmd
    - ../20.Rmd
    - ../21.Rmd
    - ../22.Rmd
    - ../23.Rmd
    
    

format:
  pdf:
    output-file: "scifi.pdf"
    pdf-engine: lualatex
    # toc-depth: 1
    toc-title: "Оглавление"
    mainfont: Times New Roman
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    documentclass: scrreprt
    papersize: a5paper
  docx:
    output-file: "scifi.docx"
    toc-title: "Оглавление"
  epub:
    output-file: "scifi.epub"



